<!DOCTYPE html>
<html lang="es"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Prof.&nbsp;Maximiliano Lucas Romei">
  <title>Sociedades Civiles y Comerciales – Clase 13 — SA - Asamblea</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-0427d8d92a431aa6a6430e53ec02a470.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
  <script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
  <link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Clase 13 — SA - Asamblea</h1>
  <p class="subtitle">Sociedades Civiles y Comerciales · UBA · Curso intensivo 2026</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Maximiliano Lucas Romei 
</div>
</div>
</div>

</section>
<section id="asamblea" class="slide level1">
<h1>Asamblea</h1>
<p>Concepto</p>
<p>Es el organo esencial no permanente de la sociedad que reune a dichos accionistas, y eventualmente a las personas a quienes la ley o el estatuto establecen que deben ser convocadas, con el objeto de tomar decisiones respecto del gobierno de la sociedad en materias que son de su competencia</p>
<p>Según Vitolo</p>
<blockquote>
<p>expresa y forma la voluntad social del ente en aquellas materias que le son asignadas como competencia exclusiva y excluyente por parte de Ia ley, el estatuto o el reglamento.</p>
</blockquote>
</section>
<section id="clases-de-asambleas" class="slide level1">
<h1>Clases de Asambleas</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
A[Asamblea] --&gt; B[Constitutiva] 
A[Asamblea] --&gt; C[Ordinaria]
A[Asamblea] --&gt; D[Extraordinaria]
A[Asamblea] --&gt; E[Especiales]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="asamblea-constitutiva" class="slide level1">
<h1>Asamblea Constitutiva</h1>
<p>es aquella asamblea convocada al solo efecto de decidir la definitiva constitucion de la sociedad y la misma se encuentra regulada en el articulo 176</p>
<blockquote>
<p>ARTICULO 176. — La asamblea constitutiva debe celebrarse con presencia del banco interviniente y será presidida por un funcionario de la autoridad de contralor; quedará constituida con la mitad más una de las acciones suscriptas.</p>
</blockquote>
<blockquote>
<p>Fracaso de la convocatoria.</p>
</blockquote>
<blockquote>
<p>Si fracasara, se dará por terminada la promoción de la sociedad y se restituirá lo abonado conforme al artículo 173, sin perjuicio de las acciones del artículo 175.</p>
</blockquote>
</section>
<section id="asamblea-ordinaria" class="slide level1">
<h1>Asamblea Ordinaria</h1>
<p>es la que tiene competencia para resolver aquellas cuestiones relacionadas con la gestién de la sociedad conforme a lo que se establece en la ley y alo que pudiera incluirse en el estatuto, como asi también tiene competencia para resolver cualquier medida relativa a la gestion de la sociedad que sometan a su consideracion el directorio, el consejo de vigilancia o los sindicos.</p>
<blockquote>
<p>ARTICULO 234. — Corresponde a la asamblea ordinaria considerar y resolver los siguientes asuntos:</p>
</blockquote>
<pre><code>1) Balance general, estado de los resultados, distribución de ganancias, memoria e informe del síndico y toda otra medida relativa a la gestión de la sociedad que le competa resolver conforme a la ley y el estatuto o que sometan a su decisión el directorio, el consejo de vigilancia o los síndicos;

2) Designación y remoción de directores y síndicos miembros del consejo de vigilancia y fijación de su retribución;

3) Responsabilidad de los directores y síndicos y miembros del consejo de vigilancia;

4) Aumentos del capital conforme al artículo 188.

    Para considerar los puntos 1) y 2) será convocada dentro de los cuatro (4) meses del cierre del ejercicio.</code></pre>
</section>
<section id="asamblea-extraordinaria" class="slide level1">
<h1>Asamblea Extraordinaria</h1>
<p>tiene competencia para el tratamiento de aquellos asuntos que no sean de competencia de la asamblea ordinaria, asi como los relativos a la modificacion del estatuto social.</p>
<blockquote>
<p>ARTICULO 235. — Corresponden a la asamblea extraordinaria todos los asuntos que no sean de competencia de la asamblea ordinaria, la modificación del estatuto y en especial:</p>
</blockquote>
<pre><code>1º) Aumento de capital, salvo el supuesto del artículo 188. Sólo podrá delegar en el directorio la época de la emisión, forma y condiciones de pago;

2º) Reducción y reintegro del capital;

3º) Rescate, reembolso y amortización de acciones;

4º) Fusión, transformación y disolución de la sociedad; nombramiento, remoción y retribución de los liquidadores; escisión; consideración de las cuentas y de los demás asuntos relacionados con la gestión de éstos en la liquidación social, que deban ser objeto de resolución aprobatoria de carácter definitivo;

5º) Limitación o suspensión del derecho de preferencia en la suscripción de nuevas acciones conforme al artículo 197;

6º) Emisión de debentures y su conversión en acciones;

7º) Emisión de bonos.</code></pre>
</section>
<section id="asamblea-extraordinaria-1" class="slide level1">
<h1>Asamblea Extraordinaria</h1>
<p>Mas allá de lo dispuesto por el art. 235 le compete a esta asamblea</p>
<ul>
<li>los aumentos de capital -salvo el caso del articulo 188-</li>
<li>tomar decisiones vinculadas a la reduccién y reintegro del capital social, y al rescate, reembolso y amortizacién de acciones</li>
<li>fusion, transformaci6n, escision y disolucion de la sociedad</li>
<li>nombramiento, remocion y retribucion de los liquidadores sociales;</li>
<li>consideracion de las cuentas y los demas asuntos relacionados con la gestion de los liquidadores que deban ser objeto de resolucion aprobatoria de caracter definitivo</li>
<li>la limitacion o suspension del derecho de preferencia en la suscripcion de nuevas acciones conforme al articulo 197</li>
<li>la emisión de debentures y su conversion en acciones y la emision de bonos,</li>
</ul>
</section>
<section id="asambleas-especiales" class="slide level1">
<h1>Asambleas Especiales</h1>
<p>cuando la asamblea deba adoptar resoluciones que afecten los derechos de una clase de acciones, se requiere el consentimiento o ratificacién de esta clase, la que debe prestarse en asamblea especial regida por las normas de la asamblea ordinaria.</p>
<blockquote>
<p>ARTICULO 250. — Cuando la asamblea deba adoptar resoluciones que afecten los derechos de una clase de acciones, que se requiere el consentimiento o ratificación de esta clase, que se prestará en asamblea especial regida por las normas de la asamblea ordinaria.</p>
</blockquote>
</section>
<section id="modalidades-de-celebración-de-asambleas" class="slide level1">
<h1>MODALIDADES DE CELEBRACIÓN DE ASAMBLEAS</h1>
<div class="columns">
<div class="column" style="width:35%;">
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
A[MODO]
A --&gt; B[PUBLICADA]
A --&gt; C[UNÁNIME]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column" style="width:65%;">
<h3 id="publicadas">Publicadas</h3>
<p>Convocadas mediante las publicaciones previstas en el <strong>art. 237 LGS</strong>. Reunido el quórum, las decisiones se adoptan conforme a las mayorías legales o estatutarias.</p>
<h3 id="unánimes">Unánimes</h3>
<p>Pueden celebrarse sin publicación de la convocatoria cuando está presente la totalidad del capital social y las decisiones se adoptan por unanimidad de las acciones con derecho a voto.</p>
</div></div>
</section>
<section id="lugar-de-reunión" class="slide level1">
<h1>Lugar de reunión</h1>
<p>El articulo 233 de la ley 19.550 establece que las asambleas deben reunirse en la sede social o en otro lugar mientras que el mismo se encuentre dentro de la jurisdiccion del domicilio social; ello, con el objeto de que se permita el facil acceso de todos los accionistas a la asamblea.</p>
<blockquote>
<p>Si es distinto debera disponerlo en forma expresa, ya que el articulo 237 exige que en la convocatoria que se efectte para la celebracion de cualquier asamblea deben incluirse los datos del lugar de reunion.</p>
</blockquote>
</section>
<section class="slide level1">

<center>
<blockquote>
<p>ARTICULO 233. — Las asambleas tienen competencia exclusiva para tratar los asuntos incluidos en los artículos 234 y 235.</p>
</blockquote>
<blockquote>
<p>Lugar de reunión.</p>
</blockquote>
<blockquote>
<p>Deben reunirse en la sede o en el lugar que corresponda a jurisdicción del domicilio social.</p>
</blockquote>
<blockquote>
<p>Obligatoriedad de sus decisiones. Cumplimiento.</p>
</blockquote>
<blockquote>
<p>Sus resoluciones conformes con la ley y el estatuto, son obligatorias para todos los accionistas salvo lo dispuesto en el artículo 245 y deben ser cumplidas por el directorio.</p>
</blockquote>
</center>
</section>
<section id="decisiones-asamblearias-obligatorias" class="slide level1">
<h1>Decisiones asamblearias obligatorias</h1>
<p>Tal como lo menciona el 233 resultan obligatorias para todos los accionistas y que las mismas deben ser cumplidas por el directorio.</p>
<p>La asamblea de accionistas es un cuerpo colegiado y, como tal, forma su voluntad a través del voto de sus integrantes bajo el sistema de mayorias.</p>
<p>Este resultado directo del principio de obligatoriedad de las decisiones asamblearias, como lo recuerda prestigiosa doctrina, determina que: - Las decisiones asamblearias resultan validas incluso en aquellos casos en los cuales pueden resultar perjudiciales para los intereses de alguno o algunos socios en particular; - La decision asamblearia resulta obligatoria no sólo para los accionistas que integraban la sociedad al momento de tomarse la decision, sino también para todos aquellos que se incorporen posteriormente a la sociedad<br>
- Las decisiones asamblearias resultan también obligatorias para los accionistas ausentes, y la suscripcion de acciones de una sociedad comercial importa la aceptacion y sometimiento a las decisiones que los é6rganos de la misma pudieran tomar con adecuacion a la ley, el estatuto y el reglamento.</p>
</section>
<section class="slide level1">

<center>
</center></section>
<section id="asamblea-extraordinaria-2" class="slide level1">
<h1>ASAMBLEA EXTRAORDINARIA</h1>
<p>corresponde a la asamblea extraordinaria considerar todos los asuntos que no sean competencia de la asamblea ordinaria, la modificacion del estatuto y algunos supuestos especificos que en forma particular se enumeran.</p>
<p>La naturaleza extraordinaria de la asamblea esta dada por cuestiones vinculadas a la competencia del organo y no en relacion con el caracter esporadico de su celebracion,</p>

</section>
<section id="asamblea-extraordinaria-3" class="slide level1 scrollable">
<h1>ASAMBLEA EXTRAORDINARIA</h1>
<p>La competencia esta dada por tres rubos</p>
<ol type="1">
<li>Lacompetencia residual asignada por el articulo 235 respecto de todas aquellas decisiones que deban ser tomadas por el érgano de gobierno</li>
<li>La modificacion del estatuto social,</li>
<li>Los supuestos especiales, que son aquellos que en siete (7) incisos menciona el articulo 235.</li>
</ol>
</section>
<section id="competencia-de-asamblea-extraordinaria" class="slide level1">
<h1>COMPETENCIA DE ASAMBLEA EXTRAORDINARIA</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Asamblea Extraordinaria] --&gt; B[Aumento de Capital]
A[Asamblea Extraordinaria] --&gt; C[Reducción y reintegro de capital]
A[Asamblea Extraordinaria] --&gt; D[Rescate de acciones]
A[Asamblea Extraordinaria] --&gt; E[Fusión, Transformación, Escición]
A[Asamblea Extraordinaria] --&gt; F[Disolución]
A[Asamblea Extraordinaria] --&gt; G[Liquidadores]
A[Asamblea Extraordinaria] --&gt; H[Gestión de liquidadores]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="aumento-de-capital" class="slide level1 scrollable">
<h1>Aumento de Capital</h1>
<p>Es competencia de la asamblea extraordinaria:</p>
<ol type="1">
<li>El aumento de capital de la sociedad dentro del quintuplo, cuando el estatuto no ha recogido en forma expresa la facultad otorgada por el articulo 188 de asignar esta competencia a la asamblea ordinaria</li>
<li>Cualquier otro aumento de capital por encima del quintuplo, sin que dicha asamblea pueda delegar la facultad en el 6rgano de administracion ni en otro organo,</li>
</ol>
</section>
<section id="reducción-y-reintegro-de-capital" class="slide level1">
<h1>Reducción y Reintegro de Capital</h1>
<p>En lo que a la reduccion del capital social se refiere, el pronunciamiento de la asamblea extraordinaria y su competencia comprende tanto la de reducci6on voluntaria del capital social, la reduccion por pérdidas y la reduccion obligatoria, cuestiones -todas éstas- contempladas en los articulos 203, 204, 205 y 206. Sin perjuicio de ello debemos recordar que para tomar las resoluciones referidas a la asamblea extraordinaria se debe: 1. En el caso de reduccién voluntaria del capital social, contar con un informe fundado del sindico, en su caso, o un informe de auditoria 2. Para la reduccién por pérdidas, las mismas deben haber afectado el equilibrio existente entre el capital y el patrimonio social; la reducci6n obligatoria o las pérdidas registradas deben haber insumido las reservas y al menos el 50% del capital social.</p>
</section>
<section id="rescate-reembolso-y-amortización-de-acciones" class="slide level1">
<h1>Rescate, reembolso y amortización de acciones</h1>
<ul>
<li>Por rescate de acciones debe entenderse aquellos casos en los cuales la sociedad puede adquirir sus propias acciones con el objeto de cancelarlas, previo acuerdo de reduccion del capital social como sefiala el articulo 220, inciso 1°</li>
</ul>
</section>
<section id="fusión-transformación-y-escición" class="slide level1">
<h1>Fusión, transformación y escición</h1>
<p>Cualquiera de las tres serán descisiones que corresponde ser tomada por la asamblea extraordinaria</p>
</section>
<section id="disolución-de-la-sociedad" class="slide level1">
<h1>Disolución de la sociedad</h1>
<p>Recordemos que en palabras de Vitolo es “el acto juridico que, previa la verificacion de alguna de las causales previstas en la ley, en el contrato o en los estatutos, abre el proceso liquidatorio conducente a la extincion de la sociedad como contrato y como persona juridica.”</p>
<p>Tratandose -la disolucion anticipada- de una alteracion fundamental de las bases sociales pues modifica un elemento y requisito esencial a todo contrato de sociedad, el legislador ha considerado que tal decision sélo puede tomarse por la decision de una asamblea extraordinaria</p>
</section>
<section id="nombramiento-remoción-y-retribución-de-liquidadores." class="slide level1">
<h1>Nombramiento, remoción y retribución de liquidadores.</h1>
<p>Al operarse una causal disolutoria la sociedad no cesa en su existencia sino que pasa al estado de liquidacion conservando su personalidad a ese efecto y rigi¢éndose por las normas correspondientes a su tipo, en cuanto resulten compatibles. La ley 19.550 dispone que el nombramiento, la remocion y la retribucion de quienes acttien como liquidadores en una sociedad anónima en liquidacion resulten competencia exclusiva de la asamblea extraordinaria.</p>
</section>
<section id="consideración-de-la-gestión-de-los-liquidadores." class="slide level1">
<h1>Consideración de la gestión de los liquidadores.</h1>
<p>La consideracién y aprobacion definitiva de las cuentas y de la gestion cumplida por los liquidadores también sera competencia de la asamblea extraordinaria, debiendo considerarse dentro de los otros actos sujetos a aprobacion: 1. El balance final; 2. El proyecto de distribucion.</p>
<p>Aquellas otras gestiones cumplidas por los liquidadores que no tengan necesidad de una aprobacion de caracter definitive se mantendran dentro de la orbita de competencia de la asamblea ordinaria.</p>
</section>
<section id="limitación-o-suspensión-del-derecho-de-preferencia" class="slide level1">
<h1>Limitación o suspensión del derecho de preferencia</h1>
<blockquote>
<p>El derecho de suscripcion preferente es uno de los derechos esenciales del accionista, en la medida en que su decision de participar en la sociedad no solo esta dada en razon de una equivalencia economica respecto del patrimonio del ente ideal, sino también en cuanto a la relevancia de su influencia proporcional en el ejercicio de otros derechos.</p>
</blockquote>
<p>El articulo 194 de la ley 19.550 sefala que el derecho de suscripcion preferente no puede ser suprimido ni condicionado salvo lo dispuesto en el articulo 197, que permite que una asamblea extraordinaria, con las mayorias del ultimo parrafo del articulo 244, pueda resolver en casos particulares y excepcionales, cuando el interés de la sociedad lo exija, la limitacién o suspension del derecho de preferencia en la suscripcion de nuevas acciones bajo dos condiciones: - Que su consideracién se incluya en el orden de dia, y - ue se trate de acciones a integrarse con aportes en especie 0 que se den en pago de acciones preexistentes.</p>
</section>
<section id="emision-de-debentures-y-su-conversion-en-acciones" class="slide level1">
<h1>EMISION DE DEBENTURES Y SU CONVERSION EN ACCIONES</h1>
<p>Los debentures son titulos valores que instrumentan obligaciones sociales otorgando a su tenedor la calidad de acreedor de la sociedad con el derecho a la recepción de los intereses y cuotas de amortizacion pactados.</p>
<p>La circunstancia de que la emisión de un debenture coloque al titular del mismo en la calidad de acreedor proveyéndolo de un titulo valor de circulacion con significativas consecuencias relativas al ejercicio de sus derechos, y la posibilidad de promover acciones directas contra la sociedad, es una decision de gran importancia para la vida societaria, por lo que el legislador ha incluido esta materia dentro de aquellas asignadas en forma exclusiva a la asamblea extraordinaria.</p>
<p>Del mismo modo, la conversión de estos titulos en acciones -ver art. 334-, que importara un aumento de capital posterior a la emision de los titulos, presenta igualmente una decision de gran trascendencia que amerita su inclusion dentro del marco de competencia de la asamblea extraordinaria.</p>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Debentures convertibles.</p>
<p>ARTICULO 334. — Cuando los debentures sean convertibles en acciones:</p>
<pre><code>1º) Los accionistas, cualquiera sea su clase o categoría, gozarán de preferencia para su suscripción en proporción a las acciones que posean, con derecho de acrecer;

2º) Si la emisión fuere bajo la par la conversión no podrá ejecutarse en desmedro de la integridad del capital social;

3º) Pendiente la conversión, está prohibido: amortizar o reducir el capital, aumentarlo por incorporación de reservas o ganancias, distribuir las reservas o modificar el estatuto en cuanto a la distribución de ganancias.</code></pre>
</div>
</div>
</div>
</section>
<section id="emisión-de-bonos" class="slide level1">
<h1>Emisión de bonos</h1>
<p>Importando la emisién de bonos una restricción impuesta a los derechos de los accionistas en cuanto a su derecho a participar de la distribucién de utilidades, esta decision es de resorte exclusivo de la asamblea extraordinaria.</p>
</section>
<section id="retiro-del-régimen-de-oferta-pública" class="slide level1">
<h1>Retiro del régimen de oferta pública</h1>
<p>Las Normas de la Comisién Nacional de Valores disponen que, en caso de que las entidades decidan retirarse del régimen de la oferta publica, deberan considerar el tema como punto expreso del orden del dia en asamblea extraordinaria, cumpliendo con el guorum y mayorias requeridos por los reglamentos de las entidades autorreguladas, en su caso.</p>
</section>
<section id="restitución-de-aportes-irrevocables" class="slide level1">
<h1>Restitución de Aportes Irrevocables</h1>
<p>Al resolverse la restitución -por no haberse aprobado el aumento de capital o por cualquier otra causa-, 0 vencido el plazo para la celebracién de la primera asamblea que se celebre en un plazo que no debera exceder los seis (6) meses a contar desde la aceptacion del aporte irrevocable por el directorio-, cesara su calidad de aporte irrevocable y pasara a integrar el pasivo de la emisora, en caracter de crédito subordinado. La restitucion debera ser resuelta por asamblea extraordinaria y sometida al régimen de avisos para oposicion de acreedores conforme lo dispuesto por el articulo 83, inciso 3°, de la ley 19.550.</p>
</section>
<section id="qué-es-un-aporte-irrevocable" class="slide level1">
<h1>¿Qué es un Aporte irrevocable?</h1>
<blockquote>
<p><strong>Concepto</strong></p>
<p>Son sumas de dinero o bienes entregados a la sociedad por los socios (o eventualmente terceros) con el compromiso de destinarlos a un futuro aumento de capital, sin posibilidad de exigir su restitución mientras se mantengan como tales.</p>
</blockquote>
<h3 id="características">Características</h3>
<ul>
<li>No integran el capital social.</li>
<li>Forman parte del patrimonio neto.</li>
<li>Deben ser capitalizados o restituidos conforme al régimen legal y reglamentario.</li>
<li>No otorgan por sí mismos la calidad de accionista ni derechos políticos.</li>
<li>Requieren una decisión posterior del órgano competente para su capitalización.</li>
</ul>
<h3 id="finalidad">Finalidad</h3>
<ul>
<li>Fortalecer transitoriamente el patrimonio de la sociedad.</li>
<li>Financiar la actividad sin recurrir inmediatamente a un aumento de capital.</li>
<li>Facilitar futuras capitalizaciones.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>Ejemplo</strong></p>
<p>Un accionista entrega $100 millones para fortalecer financieramente a la sociedad. Hasta que la asamblea apruebe el aumento de capital y se emitan las acciones correspondientes, ese dinero constituye un <strong>aporte irrevocable</strong>, no capital social.</p>
</div>
</div>
</div>
<blockquote>
<p>El aporte irrevocable no puede permanecer indefinidamente como tal. Debe resolverse su capitalización o su restitución conforme a la normativa aplicable (particularmente la RG IGJ 7/2015 para las sociedades sujetas a su fiscalización). Esto evita que se utilice como una forma permanente de financiamiento al margen del régimen del capital social.</p>
</blockquote>
</section>
<section id="convocatoria-de-asambleas" class="slide level1">
<h1>Convocatoria de Asambleas</h1>
<p>Es un órgano NO permanente</p>
<p>DEBE convocarse</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>la convocatoria ha sido definida por la doctrina como aguel acto societario a través del cual se requiere de los accionistas que se reinan en forma organizada conforme a la ley y al estatuto para resolver las decisiones vinculadas a las materias cuya competencia le ha sido asignada al érgano de gobierno.</p>
</div>
</div>
</div>
<blockquote>
<p>la convocatoria es un elemento y requisito necesario para la celebraci6n de una asamblea, cualquiera sea la naturaleza que ésta revista.</p>
</blockquote>
</section>
<section id="quiénes-estan-legitimados-para-convocar-a-la-asamblea" class="slide level1">
<h1>¿Quiénes estan legitimados para convocar a la asamblea?</h1>
<p>Dentro de los legitimados previstos por la ley para convocar a las asambleas se encuentran, basicamente, los otros órganos societarios aunque la competencia natural esta asignada al directorio, estableciendo el articulo 236 que en ciertos casos pueda también convocarla la sindicatura y -aunque la ley no lo diga- también podra hacerlo el consejo de vigilancia.</p>
<p>Las asambleas también pueden ser convocadas, en ciertos casos, por las autoridades de contralor y judicial. Tratandose estos dos ultimos casos de situaciones realmente de excepcion.</p>
</section>
<section id="el-directorio" class="slide level1">
<h1>EL DIRECTORIO</h1>
<p>Tiene competencia natural y primaria para convocar</p>
<p>En aquellos casos en los cuales se haya resuelto la intervenci6n judicial de la sociedad, la convocatoria por parte del organo de administracion -directorio- se mantendra incolume cuando judicialmente se hubiere establecido una mera veeduria, debera tomarse en forma conjunta por el directorio y el interventor designado cuando la intervencién consistiere en una coadministracion, o finalmente la convocatoria sera competencia del interventor judicial cuando la intervencion se hubiera establecido con desplazamiento de las autoridades societarias,</p>
</section>
<section id="la-sindicatura" class="slide level1 scrollable">
<h1>LA SINDICATURA</h1>
<p>La sindicatura también se encuentra facultada para convocar a asamblea, lo que podra hacer de un modo originario cuando la ley asi le asigna la atribución, o en forma supletoria o subsidiaria en aquellos casos en los cuales hubiera omitido hacerlo el directorio influyendo las normas legales o estatutarias que hubieran impuesto tal obligación.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>El articulo 294, inciso 7, dispone que es competencia del sindico: 1. Convocar a asambleas extraordinarias cuando lo juzgue necesario; y 2. Convocar a asambleas ordinarias cuando omitiere hacerlo el directorio.</p>
</div>
</div>
</div>
<p>El sindico tiene dentro de sus deberes y obligaciones facultad originaria para convocar a asambleas de accionistas en los siguientes casos:</p>
<ol type="1">
<li><p>Convocar a asamblea extraordinaria cuando lo juzgue necesario -art. 294, inc. 7y</p></li>
<li><p>Convocar a asamblea ordinaria a los efectos de remover al director o gerente incluido en el articulo 264.</p></li>
</ol>
<p>Adicionalmente, con caracter supletorio o subsidiario tiene facultades para convocar a la asamblea ordinaria cuando el directorio omita hacerlo, existiendo obligaci6n legal o estatutaria para ello -es el caso de las asambleas ordinarias, que consideraran las cuestiones contenidas en el articulo 234, incisos 1 y 2; la omision del tratamiento de decisiones efectuadas por accionistas representantes de una participacion superior al 2% del capital social, entre otras-.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>ARTICULO 264. — No pueden ser directores ni gerentes:</p>
<p>1º) Quienes no pueden ejercer el comercio;</p>
<p>2º) Los fallidos por quiebra culpable o fraudulenta hasta diez (10) años después de su rehabilitación, los fallidos por quiebra casual o los concursados hasta cinco (5) años después de su rehabilitación; los directores y administradores de sociedad cuya conducta se calificare de culpable o fraudulenta, hasta diez (10) años después de su rehabilitación.</p>
<p>3º) Los condenados con accesoria de inhabilitación de ejercer cargos públicos; los condenados por hurto, robo, defraudación, cohecho, emisión de cheques sin fondos y delitos contra la fe pública; los condenados por delitos cometidos en la constitución, funcionamiento y liquidación de sociedades. En todos los casos hasta después de diez (10) años de cumplida la condena;</p>
<p>4º) Los funcionarios de la administración pública cuyo desempeño se relacione con el objeto de la sociedad, hasta dos (2) años del cese de sus funciones.</p>
<p>Remoción del inhabilitado.</p>
<p>ARTICULO 265. — El directorio, o en su defecto el síndico, por propia iniciativa o a pedido fundado de cualquier accionista, debe convocar a asamblea ordinaria para la remoción del director o gerente incluido en el artículo 264, que se celebrará dentro de los cuarenta (40) días de solicitada. Denegada la remoción, cualquier accionista, director o síndico, puede requerirla judicialmente.</p>
</div>
</div>
</div>
</section>
<section id="el-consejo-de-vigilancia" class="slide level1 scrollable">
<h1>EL CONSEJO DE VIGILANCIA</h1>
<p>El articulo 281, en su inciso b), otorga al consejo de vigilancia la atribucion de convocar a asamblea cuando lo estime conveniente o cuando lo requieran accionistas que representen por lo menos el cinco por ciento (5%) del capital social, si es que los estatutos no fijaran un porcentaje menor. Tratandose el consejo de vigilancia de un érgano colegiado, la resolucion también debera tomarse bajo la forma de colegio y por el régimen de mayoria absoluta de sus miembros,</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>ARTICULO 281. — El estatuto reglamentará la organización y funcionamiento del consejo de vigilancia.</p>
<p>Atribuciones y deberes.</p>
<p>Son funciones del consejo de vigilancia:</p>
<ol type="a">
<li><p>Fiscalizar la gestión del directorio. Puede examinar la contabilidad social, los bienes sociales, realizar arqueos de caja, sea directamente o por peritos que designe; recabar informes sobre contratos celebrados o en trámite de celebración, aun cuando no excedan de las atribuciones del directorio. Por lo menos trimestralmente, el directorio presentará al consejo informe escrito acerca de la gestión social;</p></li>
<li><p>Convocará la asamblea cuando estime conveniente o lo requieran accionistas conforme al artículo 236;</p></li>
</ol>
<p>Convocatoria: Oportunidad. Plazo.</p>
<p>ARTICULO 236. — Las asambleas ordinarias y extraordinarias serán convocadas por el directorio o el síndico en los casos previstos por la ley, o cuando cualquiera de ellos lo juzgue necesario o cuando sean requeridas por accionistas que representan por lo menos el cinco por ciento (5 %) del capital social, si los estatutos no fijaran una representación menor.</p>
<p>En este último supuesto la petición indicará los temas a tratar y el directorio o el síndico convocará la asamblea para que se celebre en el plazo máximo de cuarenta (40) días de recibida la solicitud.</p>
<p>Si el directorio o el síndico omite hacerlo, la convocatoria podrá hacerse por la autoridad de contralor o judicialmente.</p>
</div>
</div>
</div>
</section>
<section id="es-posible-la-autoconvocatoria" class="slide level1">
<h1>¿Es posible la autoconvocatoria?</h1>
<div class="columns">
<div class="column" style="width:40%;">
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Art. 237 LGS]
B[Art. 158 CCyC]
C[Autoconvocatoria]

A --&gt; C
B --&gt; C
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column" style="width:60%;">
<h3 id="posición-de-vitolo">Posición de Vitolo</h3>
<ul>
<li>El <strong>art. 237 LGS</strong> permite prescindir de la <strong>publicación</strong> de la convocatoria cuando:
<ul>
<li>está presente el <strong>100 % del capital con derecho a voto</strong>; y</li>
<li>las decisiones se adoptan <strong>por unanimidad</strong>.</li>
</ul></li>
<li>El <strong>art. 158 CCyC</strong> autoriza la <strong>autoconvocatoria</strong> de los órganos colegiados cuando existe:
<ul>
<li>asistencia unánime; y</li>
<li>acuerdo unánime sobre el orden del día.</li>
</ul></li>
<li><strong>Vitolo</strong> entiende que ambas normas <strong>se complementan</strong>.</li>
</ul>
</div></div>
<div class="callout callout-note callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Requisitos para la autoconvocatoria en la SA (según Vitolo)</strong></p>
</div>
<div class="callout-content">
<p>✅ Presencia de la totalidad del capital con derecho a voto.</p>
<p>✅ Aceptación unánime de celebrar la reunión.</p>
<p>✅ Acuerdo unánime sobre el orden del día.</p>
<p>✅ Decisiones adoptadas por unanimidad.</p>
</div>
</div>
</div>
</section>
<section id="convocatoria-por-la-autoridad-de-contralor" class="slide level1">
<h1>Convocatoria por la autoridad de contralor</h1>
<blockquote>
<p><strong>Art. 65 RG IGJ 7/2015</strong></p>
</blockquote>
<p>La <strong>Inspección General de Justicia (IGJ)</strong> puede convocar a una asamblea de accionistas en los siguientes supuestos:</p>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[IGJ]

A --&gt; B[De oficio]

A --&gt; C[A pedido de accionistas]

A --&gt; D[A pedido de directores]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="de-oficio">1. De oficio</h3>
<ul>
<li>Cuando constate <strong>graves irregularidades</strong>.</li>
<li>Siempre que la convocatoria resulte necesaria para proteger el <strong>interés público</strong>.</li>
</ul>
<h3 id="a-pedido-de-accionistas">2. A pedido de accionistas</h3>
<ul>
<li>Titulares de <strong>al menos el 5 % del capital social</strong> (o el porcentaje menor previsto en el estatuto).</li>
<li>Deben demostrar que solicitaron previamente la convocatoria al directorio y, en su caso, a la sindicatura, <strong>sin obtener respuesta o ante una negativa infundada</strong>.</li>
</ul>
<h3 id="a-pedido-de-directores">3. A pedido de directores</h3>
<ul>
<li>Cuando el presidente del directorio no convoque la reunión.</li>
<li>Cuando el directorio no pueda reunirse por falta de quórum o rechace injustificadamente la convocatoria.</li>
<li>Si existe sindicatura, también debe acreditarse su inacción o negativa injustificada.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>Excepción:</strong> si el directorio está vacante y no puede formar quórum, y la sindicatura tampoco regulariza la situación (art. 258 LGS), la IGJ puede intervenir sin exigir los recaudos previos.</p>
</div>
</div>
</div>
</section>
<section id="procedimiento-judicial" class="slide level1">
<h1>Procedimiento judicial</h1>
<blockquote>
<p><strong>Art. 15 LGS</strong></p>
</blockquote>
<p>Cuando la Ley General de Sociedades autoriza o prevé una <strong>acción judicial</strong>, ésta debe tramitar por un procedimiento de conocimiento <strong>rápido</strong>.</p>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Art. 15 LGS]
B[Procedimiento sumario]
C[Ley 25.488]
D[Desaparece el juicio sumario]
E[Debate actual]

A --&gt; B
B --&gt; C
C --&gt; D
D --&gt; E
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="evolución">Evolución</h3>
<ul>
<li>Originalmente, el art. 15 remitía al <strong>juicio sumario</strong> previsto en el Código Procesal.</li>
<li>La <strong>Ley 25.488</strong> eliminó ese proceso.</li>
<li>Desde entonces surgió el debate sobre cuál es el procedimiento aplicable.</li>
</ul>
<h3 id="posición-de-vitolo-1">Posición de Vitolo</h3>
<ul>
<li>Debe aplicarse un <strong>procedimiento sumarísimo</strong>.</li>
<li>Se preserva el espíritu del art. 15:
<ul>
<li><strong>celeridad</strong> en la resolución;</li>
<li><strong>debido derecho de defensa</strong> de la sociedad.</li>
</ul></li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>Idea clave:</strong> aunque el antiguo juicio sumario desapareció, la finalidad del art. 15 sigue siendo que los conflictos societarios que la ley remite a la justicia se resuelvan <strong>rápidamente</strong>, sin sacrificar las garantías procesales.</p>
</div>
</div>
</div>
</section>
<section id="publicidad-de-la-convocatoria" class="slide level1">
<h1>Publicidad de la convocatoria</h1>
<div class="columns">
<div class="column" style="width:35%;">
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Convocatoria]

A --&gt; B[Boletín Oficial]

A --&gt; C[Sociedades art. 299]

C --&gt; D[Diario de gran circulación]

A --&gt; E[5 publicaciones]

E --&gt; F[10 a 30 días antes]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column" style="width:65%;">
<h3 id="finalidad-1">Finalidad</h3>
<ul>
<li>Informar a los accionistas sobre la celebración de la asamblea.</li>
<li>Permitir el ejercicio del derecho de asistencia y voto.</li>
<li>Dar publicidad a terceros legitimados.</li>
</ul>
<h3 id="contenido-del-edicto">Contenido del edicto</h3>
<ul>
<li>Denominación social.</li>
<li>Fecha, hora y lugar.</li>
<li>Orden del día.</li>
<li>Recaudos estatutarios para asistir.</li>
</ul>
</div></div>
<div class="callout callout-note callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Consecuencias</strong></p>
</div>
<div class="callout-content">
<p>❌ <strong>Omisión de la publicidad:</strong> la asamblea es <strong>anulable</strong>.</p>
<p>✅ <strong>Excepción:</strong> si concurren accionistas que representan el <strong>100 % del capital con derecho a voto</strong> y todas las decisiones se adoptan <strong>por unanimidad</strong>, el defecto queda <strong>subsanado</strong> (art. 237 LGS).</p>
<p>⚠️ <strong>Defectos en la publicación:</strong> la impugnación corresponde, en principio, a los <strong>accionistas ausentes</strong>. Los presentes sólo podrán invocarla si dejaron constancia de su oposición durante la asamblea.</p>
</div>
</div>
</div>
</section>
<section id="primera-y-segunda-convocatoria" class="slide level1">
<h1>Primera y segunda convocatoria</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Primera convocatoria]

A --&gt;|Hay quórum| B[Se constituye la asamblea]

A --&gt;|No hay quórum| C[Segunda convocatoria]

C --&gt; D[Se celebra la misma asamblea]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="idea-clave">Idea clave</h3>
<ul>
<li>La ley prevé <strong>dos convocatorias</strong> para <strong>una misma asamblea</strong>.</li>
<li>Si la <strong>primera convocatoria</strong> fracasa por falta de quórum, puede realizarse una <strong>segunda convocatoria</strong>.</li>
</ul>
<h3 id="segunda-convocatoria">Segunda convocatoria</h3>
<ul>
<li>Debe celebrarse dentro de los <strong>30 días</strong> siguientes.</li>
<li>La publicación se reduce a <strong>3 días</strong>.</li>
<li>Debe efectuarse con <strong>8 días</strong> de anticipación como mínimo.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>Convocatorias simultáneas</strong></p>
<p>El estatuto puede autorizar que la <strong>primera y la segunda convocatoria</strong> se publiquen conjuntamente.</p>
<ul>
<li>Pueden fijarse para <strong>días distintos</strong>.</li>
<li>También pueden fijarse para el <strong>mismo día</strong>, siempre que exista un intervalo mínimo de <strong>1 hora</strong> entre ambas.</li>
</ul>
</div>
</div>
</div>
<blockquote>
<p><strong>Importante:</strong> no existen dos asambleas distintas; existen <strong>dos convocatorias para un mismo acto asambleario</strong>.</p>
</blockquote>
</section>
<section id="comunicación-de-asistencia-a-la-asamblea" class="slide level1">
<h1>Comunicación de asistencia a la asamblea</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Antes de 1995]
B[Depósito de acciones]

C[Hoy]
D[Comunicación de asistencia]

A --&gt; B
C --&gt; D
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="régimen-actual-art.-238-lgs">Régimen actual (art. 238 LGS)</h3>
<p>Los accionistas deben <strong>comunicar su asistencia</strong> a la sociedad con una anticipación de <strong>3 días hábiles</strong>.</p>
<p>La comunicación debe indicar:</p>
<ul>
<li>✅ La decisión de asistir.</li>
<li>✅ La cantidad de acciones con las que participará.</li>
</ul>
<h3 id="para-qué-sirve">¿Para qué sirve?</h3>
<p>Durante esos tres días la sociedad puede verificar:</p>
<ul>
<li>la legitimación del accionista;</li>
<li>la titularidad de las acciones;</li>
<li>restricciones al ejercicio del voto;</li>
<li>falta de integración del capital;</li>
<li>medidas cautelares o denuncias sobre las acciones.</li>
</ul>
<div class="callout callout-note callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Idea clave</strong></p>
</div>
<div class="callout-content">
<p>Con la <strong>nominatividad obligatoria</strong> (Ley 24.587), el antiguo <strong>depósito de acciones</strong> perdió sentido.</p>
<p>Hoy el requisito esencial para participar en la asamblea es la <strong>comunicación previa de asistencia</strong>, no el depósito de los títulos.</p>
</div>
</div>
</div>
</section>
<section id="libro-de-registro-de-asistencia-a-asambleas" class="slide level1">
<h1>Libro de Registro de Asistencia a Asambleas</h1>
<div class="columns">
<div class="column" style="width:35%;">
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Comunicación de asistencia]

A --&gt; B[Inscripción en el Libro]

B --&gt; C[Control de legitimación]

C --&gt; D[Constitución de la asamblea]

D --&gt; E[Determinación del quórum]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column" style="width:65%;">
<h3 id="qué-registra">¿Qué registra?</h3>
<ul>
<li>Los accionistas que solicitaron participar.</li>
<li>La cantidad de acciones y votos.</li>
<li>Los accionistas efectivamente presentes.</li>
</ul>
<h3 id="para-qué-sirve-1">¿Para qué sirve?</h3>
<ul>
<li>Verificar la legitimación de los asistentes.</li>
<li>Determinar el <strong>quórum</strong>.</li>
<li>Comprobar las mayorías de la asamblea.</li>
</ul>
<h3 id="cierre-del-registro">Cierre del registro</h3>
<ul>
<li>Se realiza <strong>3 días hábiles antes</strong> de la asamblea.</li>
<li>Permite al directorio controlar la situación de las acciones.</li>
</ul>
</div></div>
<div class="callout callout-note callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Reglas importantes</strong></p>
</div>
<div class="callout-content">
<p>✅ Si el accionista <strong>no comunicó</strong> su asistencia, la asamblea sólo podrá admitirlo por <strong>unanimidad</strong>, con presencia de la totalidad del capital.</p>
<p>✅ Si la comunicación fue <strong>tardía</strong>, podrá ser admitido por <strong>mayoría absoluta</strong> de los votos presentes.</p>
<p>✅ Una vez registrada la asistencia, las acciones quedan <strong>bloqueadas para su transferencia</strong> hasta la organización de la asamblea.</p>
</div>
</div>
</div>
</section>
<section id="incidencias-en-la-comunicación-de-asistencia" class="slide level1">
<h1>Incidencias en la comunicación de asistencia</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Comunicación de asistencia]

A --&gt; B[No comunicó]

A --&gt; C[Comunicó fuera de término]

B --&gt; D[Puede ingresar solo por unanimidad&lt;br/&gt;con el 100 % del capital presente]

C --&gt; E[Puede ingresar por mayoría absoluta&lt;br/&gt;de los votos presentes]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="regla-general">Regla general</h3>
<p>El accionista que no comunica oportunamente su asistencia <strong>no tiene derecho</strong> a participar en la asamblea.</p>
<h3 id="excepciones">Excepciones</h3>
<ul>
<li><strong>Sin comunicación:</strong> puede ser admitido únicamente por <strong>unanimidad</strong>, con presencia de la totalidad del capital social.</li>
<li><strong>Comunicación tardía:</strong> puede ser admitido por <strong>mayoría absoluta</strong> de los votos presentes.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>Principio de igualdad</strong></p>
<p>La asamblea debe aplicar el mismo criterio respecto de todos los accionistas que se encuentren en la misma situación.</p>
</div>
</div>
</div>
</section>
<section id="otras-cuestiones-del-registro-de-asistencia" class="slide level1">
<h1>Otras cuestiones del registro de asistencia</h1>
<h3 id="si-la-sociedad-no-inscribe-al-accionista">Si la sociedad no inscribe al accionista</h3>
<ul>
<li>Si el accionista comunicó su asistencia en término, puede acreditar esa circunstancia mediante el comprobante correspondiente.</li>
<li>El presidente debe explicar las razones de la negativa.</li>
<li>Si no existe una causa legal (por ejemplo, mora en la integración), el accionista debe ser incorporado al registro y participar de la asamblea.</li>
</ul>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Comunicación registrada]

--&gt; B[Inscripción en el libro]

--&gt; C[Acciones bloqueadas]

--&gt; D[Celebración de la asamblea]

--&gt; E[Fin del bloqueo]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="bloqueo-de-transferencia">Bloqueo de transferencia</h3>
<p>Una vez inscripta la asistencia:</p>
<ul>
<li>las acciones quedan <strong>bloqueadas</strong>;</li>
<li>no pueden transferirse hasta la organización de la asamblea.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>Finalidad</strong></p>
<p>Evitar que vote quien ya dejó de ser accionista y asegurar que el quórum y las mayorías reflejen la verdadera composición del capital social.</p>
</div>
</div>
</div>
</section>
<section id="actuacion-por-mandatario-en-asamblea" class="slide level1">
<h1>ACTUACION POR MANDATARIO EN ASAMBLEA</h1>
<p>El articulo 239 de la ley 19.550 permite que los accionistas no concurran personalmente a las asambleas que celebre la sociedad y que se hagan representar en ellas a través de mandatarios,</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>Actuación por mandatario.</p>
<p>ARTICULO 239. — Los accionistas pueden hacerse representar en las asambleas. No pueden ser mandatarios los directores, los síndicos, los integrantes del consejo de vigilancia, los gerentes y demás empleados de la sociedad.</p>
<p>Es suficiente el otorgamiento del mandato en instrumento privado, con la firma certificada en forma judicial, notarial o bancaria, salvo disposición en contrario del estatuto.</p>
</div>
</div>
</div>
<p>resulta suficiente el otorgamiento del mandato en instrumento privado, con la firma certificada en forma judicial, notarial o bancaria,</p>
<blockquote>
<p>salvo disposición en contrario del estatuto.</p>
</blockquote>
</section>
<section id="representaciones-prohibidas-art.-239-lgs" class="slide level1">
<h1>Representaciones prohibidas (art. 239 LGS)</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[¿Quién representa al accionista?]

A --&gt; B[Mandato voluntario]

A --&gt; C[Representación legal]

B --&gt; D["❌ Prohibido
(directores, síndicos, consejeros,
gerentes y empleados)"]

C --&gt; E["✅ Permitido
(ej.: presidente de una SA,
socio gerente de una SRL,
padres, tutores, etc.)"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="regla">Regla</h3>
<p>No pueden actuar como mandatarios voluntarios de los accionistas:</p>
<ul>
<li>Directores.</li>
<li>Síndicos.</li>
<li>Integrantes del consejo de vigilancia.</li>
<li>Gerentes.</li>
<li>Empleados de la sociedad.</li>
</ul>
<h3 id="fundamento">Fundamento</h3>
<ul>
<li>Evitar conflictos de intereses.</li>
<li>Proteger la formación de la voluntad social.</li>
<li>Impedir que se eludan las prohibiciones de voto (arts. 241 y concordantes LGS).</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>¿La asamblea es siempre nula?</strong></p>
<p>❌ No.</p>
<p>La decisión solo podrá impugnarse cuando el <strong>voto emitido mediante la representación prohibida haya sido determinante para formar la mayoría</strong>.</p>
<p>Si, aun excluyendo ese voto, la resolución igualmente hubiera sido aprobada, la infracción no invalida la decisión.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>Inhabilitación para votar.</p>
<p>ARTICULO 241. — Los directores, síndicos, miembros del consejo de vigilancia y gerentes generales, no pueden votar en las decisiones vinculadas con la aprobación de sus actos de gestión. Tampoco lo pueden hacer en las resoluciones atinentes a su responsabilidad o remoción con causa</p>
</div>
</div>
</div>
</section>
<section id="intervención-de-directores-síndicos-y-gerentes" class="slide level1">
<h1>Intervención de directores, síndicos y gerentes</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Directores, síndicos, gerentes&lt;br/&gt;y consejo de vigilancia]

A --&gt; B[Deber de asistir]

B --&gt; C[Informar a los accionistas]

C --&gt; D[La asamblea delibera y decide]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="por-qué-deben-asistir">¿Por qué deben asistir?</h3>
<ul>
<li>Es una <strong>obligación legal</strong>.</li>
<li>También constituye un <strong>derecho</strong>: pueden participar aun cuando no sean especialmente convocados.</li>
</ul>
<h3 id="función-durante-la-asamblea">Función durante la asamblea</h3>
<ul>
<li>Brindar información sobre la gestión social.</li>
<li>Responder consultas de los accionistas.</li>
<li>Aclarar los puntos incluidos en el orden del día.</li>
</ul>
<div class="callout callout-note callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Consecuencias de la inasistencia</strong></p>
</div>
<div class="callout-content">
<ul>
<li>Puede generar <strong>responsabilidad</strong> por incumplimiento de sus deberes.</li>
<li>Incluso puede constituir <strong>causal de remoción</strong>.</li>
</ul>
<p><strong>Idea clave:</strong> la presencia de los administradores y fiscalizadores garantiza que los accionistas cuenten con la información necesaria para adoptar decisiones fundadas.</p>
</div>
</div>
</div>
</section>
<section id="intervención-de-directores-síndicos-y-gerentes-1" class="slide level1">
<h1>Intervención de directores, síndicos y gerentes</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Directores, síndicos,
gerentes y consejo
de vigilancia]

A --&gt; B[Voz]

B --&gt; C[Informan y responden consultas]

C --&gt; D[Los accionistas votan]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="regla-art.-240-lgs">Regla (art. 240 LGS)</h3>
<p>Los integrantes de los órganos de:</p>
<ul>
<li>administración;</li>
<li>fiscalización; y</li>
<li>gerencia general,</li>
</ul>
<p><strong>deben asistir</strong> a la asamblea y participan <strong>con voz, pero sin voto</strong>, en ese carácter.</p>
<h3 id="por-qué">¿Por qué?</h3>
<ul>
<li>Informan sobre la gestión.</li>
<li>Responden preguntas de los accionistas.</li>
<li>Facilitan la deliberación.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>Excepción</strong></p>
<p>Si además son <strong>accionistas</strong>, podrán votar <strong>como accionistas</strong>, aunque quedarán sujetos a las prohibiciones del art. 241 LGS.</p>
</div>
</div>
</div>
</section>
<section id="inhabilitación-para-votar-art.-241-lgs" class="slide level1">
<h1>Inhabilitación para votar (art. 241 LGS)</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Director / Síndico /
Gerente / Consejo de vigilancia]

A --&gt; B{¿Qué se vota?}

B --&gt; C[Aprobación de su gestión]

B --&gt; D[Su responsabilidad]

B --&gt; E[Remoción con causa]

C --&gt; F["❌ No puede votar"]
D --&gt; F
E --&gt; F
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="no-pueden-votar-cuando-la-asamblea-decide-sobre">No pueden votar cuando la asamblea decide sobre:</h3>
<ul>
<li>La aprobación de su propia gestión.</li>
<li>Su responsabilidad.</li>
<li>Su remoción con causa.</li>
</ul>
<h3 id="fundamento-1">Fundamento</h3>
<p>Evitar que quien tiene un <strong>interés personal</strong> influya en la formación de la voluntad social.</p>
<div class="callout callout-note callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Consecuencias</strong></p>
</div>
<div class="callout-content">
<ul>
<li>El voto emitido en violación del art. 241 es <strong>nulo</strong>.</li>
<li>Sin embargo, si ese voto <strong>no fue determinante</strong> para formar la mayoría, la resolución asamblearia sigue siendo válida.</li>
<li>El funcionario puede responder por los daños ocasionados (arts. 254, 274, 280 y 298 LGS).</li>
</ul>
</div>
</div>
</div>
</section>
<section id="presidencia-de-la-asamblea-art.-242-lgs" class="slide level1 scrollable">
<h1>Presidencia de la asamblea (art. 242 LGS)</h1>
<div class="columns">
<div class="column" style="width:35%;">
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[¿Quién preside?]

A --&gt; B[Quien indique el estatuto]

A --&gt; C[Presidente del directorio]

A --&gt; D[Persona designada por la asamblea]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column" style="width:65%;">
<h3 id="orden-de-prelación">Orden de prelación</h3>
<ol type="1">
<li>La persona designada por el <strong>estatuto</strong>.</li>
<li>El <strong>presidente del directorio</strong> (o quien lo reemplace).</li>
<li>En su defecto, la persona <strong>elegida por la propia asamblea</strong>.</li>
</ol>
<p><strong>Si la convocatoria es judicial o de la IGJ</strong>, la resolución que la ordena determinará quién ejercerá la presidencia.</p>
</div></div>
<div class="callout callout-note callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Funciones principales del presidente</strong></p>
</div>
<div class="callout-content">
<ul>
<li>✅ Verificar la asistencia y las representaciones.</li>
<li>✅ Comprobar el <strong>quórum</strong> y declarar constituida la asamblea.</li>
<li>✅ Dirigir el debate y mantener el orden.</li>
<li>✅ Someter los puntos del orden del día a votación.</li>
<li>✅ Computar los votos y proclamar los resultados.</li>
<li>✅ Clausurar la asamblea y suscribir el acta.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="quórum-de-las-asambleas" class="slide level1">
<h1>Quórum de las asambleas</h1>
<table class="caption-top">
<colgroup>
<col style="width: 29%">
<col style="width: 35%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Tipo de asamblea</th>
<th style="text-align: center;">Primera convocatoria</th>
<th style="text-align: center;">Segunda convocatoria</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Ordinaria</strong></td>
<td style="text-align: center;">Mayoría de las acciones con derecho a voto</td>
<td style="text-align: center;">Cualquiera sea el número de acciones presentes</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Extraordinaria</strong></td>
<td style="text-align: center;">60 % de las acciones con derecho a voto</td>
<td style="text-align: center;">30 % de las acciones con derecho a voto</td>
</tr>
</tbody>
</table>
<div class="callout callout-note callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Regla para recordar</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Ordinaria:</strong> 50% + 1 → cualquiera.</li>
<li><strong>Extraordinaria:</strong> 60% → 30%.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="particularidades-del-quórum" class="slide level1">
<h1>Particularidades del quórum</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Quórum]

A --&gt; B[Asamblea ordinaria]

A --&gt; C[Asamblea extraordinaria]

B --&gt; D["Régimen imperativo
(no puede modificarse
por el estatuto)"]

C --&gt; E["El estatuto puede
agravar el quórum"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="asamblea-ordinaria-1">Asamblea ordinaria</h3>
<ul>
<li>Primera convocatoria: mayoría de las acciones con derecho a voto.</li>
<li>Segunda convocatoria: sesiona con cualquier número de acciones presentes.</li>
<li><strong>El estatuto no puede aumentar ni disminuir este quórum.</strong></li>
</ul>
<h3 id="asamblea-extraordinaria-4">Asamblea extraordinaria</h3>
<ul>
<li>Primera convocatoria: <strong>60 %</strong> del capital con derecho a voto.</li>
<li>Segunda convocatoria: <strong>30 %</strong>.</li>
<li><strong>El estatuto puede exigir un quórum mayor</strong> (pero no inferior al legal).</li>
</ul>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>¿Qué es el quórum?</strong></p>
<p>Es el <strong>mínimo de acciones con derecho a voto presentes</strong> necesario para que la asamblea pueda constituirse válidamente y comenzar a deliberar.</p>
<p>No debe confundirse con la <strong>mayoría</strong>, que es la cantidad de votos necesaria para aprobar una decisión.</p>
</div>
</div>
</div>
</section>
<section id="ejemplos-de-quórum" class="slide level1">
<h1>Ejemplos de quórum</h1>
<h2 id="ejemplo-1-asamblea-ordinaria">Ejemplo 1 — Asamblea ordinaria</h2>
<p>La sociedad tiene <strong>1.000 acciones con derecho a voto</strong>.</p>
<h3 id="primera-convocatoria">Primera convocatoria</h3>
<ul>
<li>Asisten <strong>520 acciones</strong>.</li>
<li>Se alcanza el quórum (mayoría de las acciones con derecho a voto).</li>
<li>✅ La asamblea puede constituirse.</li>
</ul>
<h3 id="segunda-convocatoria-1">Segunda convocatoria</h3>
<ul>
<li>Asisten <strong>150 acciones</strong>.</li>
<li>La ley permite sesionar cualquiera sea el número de acciones presentes.</li>
<li>✅ La asamblea puede constituirse.</li>
</ul>
</section>
<section id="ejemplo-2-asamblea-extraordinaria" class="slide level1">
<h1>Ejemplo 2 — Asamblea extraordinaria</h1>
<p>La sociedad tiene <strong>1.000 acciones con derecho a voto</strong>.</p>
<h3 id="primera-convocatoria-1">Primera convocatoria</h3>
<ul>
<li>Asisten <strong>580 acciones</strong>.</li>
<li>Se requieren <strong>600</strong> (60%).</li>
<li>❌ No hay quórum.</li>
</ul>
<h3 id="segunda-convocatoria-2">Segunda convocatoria</h3>
<ul>
<li>Asisten <strong>350 acciones</strong>.</li>
<li>Se requieren <strong>300</strong> (30%).</li>
<li>✅ La asamblea puede constituirse.</li>
</ul>
</section>
<section id="ejemplo-3-estatuto-con-quórum-agravado" class="slide level1">
<h1>Ejemplo 3 — Estatuto con quórum agravado</h1>
<p>El estatuto establece que la asamblea extraordinaria requiere:</p>
<ul>
<li><strong>75 %</strong> en primera convocatoria.</li>
</ul>
<p>La sociedad tiene <strong>2.000 acciones</strong>.</p>
<h3 id="primera-convocatoria-2">Primera convocatoria</h3>
<ul>
<li>Asisten <strong>1.300 acciones (65%)</strong>.</li>
<li>La ley exigiría 60%, pero el estatuto exige 75%.</li>
<li>❌ No hay quórum.</li>
</ul>
<h3 id="segunda-convocatoria-3">Segunda convocatoria</h3>
<p>El estatuto mantiene el régimen legal.</p>
<ul>
<li>Asisten <strong>700 acciones (35%)</strong>.</li>
<li>Se supera el mínimo legal del 30%.</li>
<li>✅ La asamblea puede constituirse.</li>
</ul>
</section>
<section id="ejemplo-4-no-confundir-quórum-con-mayoría" class="slide level1">
<h1>Ejemplo 4 — No confundir quórum con mayoría</h1>
<p>La sociedad tiene <strong>1.000 acciones</strong>.</p>
<p>En una asamblea ordinaria de primera convocatoria asisten <strong>700 acciones</strong>.</p>
<p>✅ Hay quórum.</p>
<p>Ahora se vota la aprobación del balance.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Votos</th>
<th style="text-align: right;">Cantidad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A favor</td>
<td style="text-align: right;">360</td>
</tr>
<tr class="even">
<td>En contra</td>
<td style="text-align: right;">340</td>
</tr>
</tbody>
</table>
<p>La resolución queda aprobada.</p>
<blockquote>
<p><strong>Hay quórum</strong> porque asistieron suficientes acciones para constituir la asamblea.</p>
<p><strong>Hay mayoría</strong> porque los votos favorables superan a los votos negativos.</p>
</blockquote>
</section>
<section id="falta-o-pérdida-del-quórum" class="slide level1">
<h1>Falta o pérdida del quórum</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Inicio de la asamblea]

A --&gt; B{¿Hay quórum?}

B --&gt;|No| C["❌ La asamblea no se constituye"]

B --&gt;|Sí| D[Comienza la deliberación]

D --&gt; E{¿Se mantiene el quórum?}

E --&gt;|Sí| F["✅ Continúa la asamblea"]

E --&gt;|No| G["❌ Se levanta la asamblea"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="si-falta-el-quórum">Si falta el quórum</h3>
<p>El presidente debe:</p>
<ul>
<li>informar la cantidad de acciones presentes;</li>
<li>indicar la norma legal o estatutaria que impide constituir la asamblea.</li>
</ul>
<h3 id="si-el-quórum-se-pierde-durante-la-reunión">Si el quórum se pierde durante la reunión</h3>
<p>El presidente debe:</p>
<ul>
<li>verificar si el quórum subsiste;</li>
<li>si no subsiste, levantar la asamblea;</li>
<li>dejar constancia de los puntos del orden del día que ya fueron válidamente votados.</li>
</ul>
<div class="callout callout-note callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Excepción</strong></p>
</div>
<div class="callout-content">
<p>El retiro <strong>breve y transitorio</strong> de accionistas <strong>no rompe el quórum</strong> cuando:</p>
<ul>
<li>es aprobado por la <strong>mayoría absoluta de los votos presentes</strong>;</li>
<li>tiene una duración limitada;</li>
<li>los accionistas permanecen próximos al lugar de la reunión (por ejemplo, para deliberar con asesores o por motivos personales).</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Una SA tiene 1.000 acciones.</p>
<p>La asamblea extraordinaria comienza con 650 acciones presentes, por lo que existe quórum (60%).</p>
<p>Durante el tratamiento del segundo punto del orden del día se retiran accionistas titulares de 400 acciones, quedando presentes solo 250 acciones.</p>
<p>Como ya no se alcanza el quórum mínimo, la asamblea debe levantarse. Las resoluciones adoptadas antes de la pérdida del quórum conservan su validez; las restantes no podrán tratarse.</p>
</div>
</div>
</div>
</section>
<section id="régimen-de-mayorías" class="slide level1">
<h1>Régimen de mayorías</h1>
<h2 id="quórum-mayoría">Quórum ≠ Mayoría</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Quórum]

--&gt; B[La asamblea puede sesionar]

B --&gt; C[Deliberación]

C --&gt; D[Mayoría]

D --&gt; E[La resolución queda aprobada]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="callout callout-tip callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Dos preguntas distintas</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Quórum:</strong> ¿La asamblea puede comenzar a deliberar?</li>
<li><strong>Mayoría:</strong> ¿La propuesta fue aprobada?</li>
</ul>
<p>Primero debe existir <strong>quórum</strong>. Recién después se computan las <strong>mayorías</strong>.</p>
</div>
</div>
</div>
</section>
<section id="mayorías-en-las-asambleas" class="slide level1">
<h1>Mayorías en las asambleas</h1>
<table class="caption-top">
<colgroup>
<col style="width: 56%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Tipo de asamblea</th>
<th style="text-align: left;">Mayoría legal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Ordinaria</strong></td>
<td style="text-align: left;">Mayoría absoluta de los votos presentes que puedan emitirse</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Extraordinaria</strong></td>
<td style="text-align: left;">Mayoría absoluta de los votos presentes que puedan emitirse*</td>
</tr>
</tbody>
</table>
<p>* Salvo los supuestos especiales del art. 244 LGS.</p>
<div class="callout callout-note callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>El estatuto</strong></p>
</div>
<div class="callout-content">
<p>Puede exigir una mayoría <strong>más elevada</strong>, pero <strong>nunca inferior</strong> a la prevista por la ley.</p>
</div>
</div>
</div>
</section>
<section id="ejemplos" class="slide level1">
<h1>Ejemplos</h1>
<h2 id="ejemplo-1">Ejemplo 1</h2>
<p>Asisten <strong>800 acciones</strong>.</p>
<p>Votación:</p>
<ul>
<li>A favor: <strong>410</strong></li>
<li>En contra: <strong>390</strong></li>
</ul>
<p>✅ La resolución queda aprobada.</p>
</section>
<section class="slide level1">

<h2 id="ejemplo-2">Ejemplo 2</h2>
<p>Asisten <strong>800 acciones</strong>.</p>
<p>Votación:</p>
<ul>
<li>A favor: <strong>400</strong></li>
<li>En contra: <strong>400</strong></li>
</ul>
<p>❌ No existe mayoría absoluta.</p>
</section>
<section class="slide level1">

<h2 id="ejemplo-3">Ejemplo 3</h2>
<p>El estatuto exige <strong>2/3 de los votos presentes</strong>.</p>
<p>Asisten <strong>900 acciones</strong>.</p>
<p>Votación:</p>
<ul>
<li>A favor: <strong>580</strong></li>
<li>En contra: <strong>320</strong></li>
</ul>
<p>Aunque existe mayoría simple, <strong>no se alcanzan los 2/3 (600 votos)</strong>.</p>
<p>❌ La resolución no queda aprobada.</p>
</section>
<section id="cómo-se-computan-las-mayorías" class="slide level1 scrollable">
<h1>¿Cómo se computan las mayorías?</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Determinar la base de cálculo]

--&gt; B[Excluir votos inhabilitados]

--&gt; C[Agregar votos excepcionalmente habilitados]

--&gt; D[Calcular la mayoría]

--&gt; E[Proclamar el resultado]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="pasos">Pasos</h3>
<ol type="1">
<li>Determinar cuántos <strong>votos pueden emitirse</strong> en esa decisión.</li>
<li>Excluir las acciones cuyos titulares <strong>no pueden votar</strong> (ej. art. 241 LGS).</li>
<li>Incorporar, si corresponde, acciones sin voto excepcionalmente habilitadas.</li>
<li>Calcular si se alcanzó la mayoría exigida por la ley o el estatuto.</li>
</ol>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La <strong>base de cálculo cambia según el punto del orden del día</strong>.</p>
<p>No siempre coincide con el total de acciones presentes.</p>
</div>
</div>
</div>
</section>
<section id="ejemplo-1-director-inhabilitado-para-votar" class="slide level1">
<h1>Ejemplo 1 — Director inhabilitado para votar</h1>
<p>La sociedad tiene <strong>1.000 acciones con derecho a voto</strong>.</p>
<p>Asisten accionistas titulares de <strong>800 acciones</strong>.</p>
<p>Uno de los accionistas es director y posee <strong>100 acciones</strong>.</p>
<p>Se vota la <strong>aprobación de su gestión</strong> (art. 241 LGS).</p>
<h2 id="base-de-cálculo">Base de cálculo</h2>
<ul>
<li>Acciones presentes: <strong>800</strong></li>
<li>Acciones inhabilitadas: <strong>100</strong></li>
</ul>
<p><strong>Base de cálculo = 700 votos</strong></p>
<h3 id="resultado">Resultado</h3>
<ul>
<li>A favor: <strong>360</strong></li>
<li>En contra: <strong>340</strong></li>
</ul>
<p>✅ La resolución queda aprobada porque obtuvo la mayoría absoluta de <strong>700 votos computables</strong>.</p>
</section>
<section id="ejemplo-2-el-error-más-frecuente" class="slide level1">
<h1>Ejemplo 2 — El error más frecuente</h1>
<p>La sociedad tiene <strong>1.000 acciones</strong>.</p>
<p>Asisten <strong>800 acciones</strong>.</p>
<p>De ellas, <strong>150 no pueden votar</strong> ese punto del orden del día.</p>
<h2 id="cuál-es-la-mayoría">¿Cuál es la mayoría?</h2>
<p>❌ Incorrecto</p>
<blockquote>
<p>La mayoría es 401 votos.</p>
</blockquote>
<p>✔ Correcto</p>
<p>Base de cálculo:</p>
<p>800 − 150 = <strong>650 votos</strong></p>
<p>Mayoría absoluta:</p>
<p><strong>326 votos</strong></p>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La mayoría <strong>no se calcula sobre los presentes</strong>, sino sobre los <strong>votos que pueden emitirse en esa decisión</strong>.</p>
</div>
</div>
</div>
</section>
<section id="etapas-del-acto-asambleario" class="slide level1">
<h1>Etapas del acto asambleario</h1>
<table class="caption-top">
<colgroup>
<col style="width: 38%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Etapa</th>
<th style="text-align: left;">Contenido</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Manifestaciones previas</strong></td>
<td style="text-align: left;">Cuestiones preliminares planteadas antes de comenzar el tratamiento del orden del día.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Registro de asistencia</strong></td>
<td style="text-align: left;">Verificación de la identidad de los accionistas, sus representantes y del quórum.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Participación de los accionistas</strong></td>
<td style="text-align: left;">Uso de la palabra, pedidos de aclaración y ejercicio de los derechos políticos.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Deliberación y votación</strong></td>
<td style="text-align: left;">Debate de cada punto del orden del día y emisión de los votos.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Toma de decisiones</strong></td>
<td style="text-align: left;">Cómputo de las mayorías y proclamación de la resolución adoptada.</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Estas etapas se desarrollan bajo la dirección del <strong>presidente de la asamblea</strong>, quien garantiza el cumplimiento de la ley, del estatuto y del orden del día.</p>
</div>
</div>
</div>
</section>
<section id="quiénes-pueden-participar-en-la-asamblea" class="slide level1">
<h1>¿Quiénes pueden participar en la asamblea?</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Asamblea]

A --&gt; B[Accionistas]

A --&gt; C[Órganos sociales]

A --&gt; D[Organismos de control]

A --&gt; E[Terceros]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<table class="caption-top">
<colgroup>
<col style="width: 42%">
<col style="width: 57%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Categoría</th>
<th style="text-align: left;">Participantes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Accionistas</strong></td>
<td style="text-align: left;">Titulares de acciones con derecho a participar.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Órganos sociales</strong></td>
<td style="text-align: left;">Directores, síndicos, gerentes y miembros del consejo de vigilancia.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Organismos de control</strong></td>
<td style="text-align: left;">Inspectores de Justicia y, en sociedades con oferta pública, funcionarios de la Comisión Nacional de Valores.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Terceros</strong></td>
<td style="text-align: left;">Escribanos, asesores legales o contables, contador certificante, traductores, intérpretes, entre otros.</td>
</tr>
</tbody>
</table>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>No todos los asistentes tienen los mismos derechos.</p>
<ul>
<li><strong>Los accionistas</strong> participan en la deliberación y votación.</li>
<li><strong>Los administradores y fiscalizadores</strong> intervienen principalmente con voz, en cumplimiento de sus funciones.</li>
<li><strong>Los organismos de control y terceros</strong> asisten cuando la ley o las circunstancias del caso lo justifican.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="que-es-el-orden-del-dia" class="slide level1">
<h1>¿QUE ES EL ORDEN DEL DiA?</h1>
<p>Es un listado que esta conformado por la enumeracion de los temas y cuestiones que son sometidos por el ente convocante a la decision de una asamblea determinada.</p>
<p>no sólo constituye un mecanismo para ordenar la celebracion y el desenvolvimiento de la asamblea, sino que también importa una suerte de limitacion respecto de la competencia de ésta en lo relativo a cual es el alcance de lo que pueda ser resuelto en cada oportunidad.</p>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Lectura íntegra]

--&gt; B[Impugnaciones]

--&gt; C[Alteración del orden]

--&gt; D[Tratamiento de los puntos]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="al-iniciarse-la-asamblea">Al iniciarse la asamblea</h3>
<p>El presidente debe:</p>
<ul>
<li>dar lectura al <strong>orden del día completo</strong>;</li>
<li>recibir las impugnaciones que formulen los accionistas;</li>
<li>informar cualquier modificación en la secuencia de tratamiento de los puntos.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La alteración del orden en que se tratarán los puntos es admisible si cuenta con la <strong>mayoría absoluta de los votos presentes</strong>.</p>
<p>Habitualmente, se trata en primer término la <strong>designación de los accionistas que firmarán el acta</strong>.</p>
</div>
</div>
</div>
</section>
<section id="requisitos-y-efectos-del-orden-del-día" class="slide level1">
<h1>Requisitos y efectos del orden del día</h1>
<h3 id="el-orden-del-día-debe-ser">El orden del día debe ser:</h3>
<ul>
<li><strong>Claro</strong>.</li>
<li><strong>Preciso</strong>.</li>
<li><strong>Determinado</strong>.</li>
</ul>
<h3 id="ejemplos-de-cláusulas-inválidas">Ejemplos de cláusulas inválidas</h3>
<ul>
<li>❌ “Asuntos varios”.</li>
<li>❌ “Otros temas a tratar”.</li>
<li>❌ “Cuestiones de interés”.</li>
<li>❌ “Medidas a tomar”.</li>
</ul>
<p>También resulta insuficiente una referencia genérica a una <strong>reforma del estatuto</strong>, sin indicar qué cláusulas serán modificadas.</p>
<div class="callout callout-warning callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Principio de especialidad (art. 246 LGS)</strong></p>
</div>
<div class="callout-content">
<p>La asamblea <strong>solo puede adoptar decisiones sobre los asuntos incluidos en el orden del día</strong>.</p>
<p>Las resoluciones sobre materias extrañas al orden del día son, en principio, <strong>nulas</strong>.</p>
</div>
</div>
</div>
</section>
<section id="excepciones-al-principio-del-orden-del-día-art.-246-lgs" class="slide level1 scrollable">
<h1>Excepciones al principio del orden del día (art. 246 LGS)</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Regla general:
solo pueden tratarse
los temas incluidos
en el orden del día"]

A --&gt; B[Asamblea unánime]

A --&gt; C[Firma del acta]

A --&gt; D[Excepciones legales]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="la-regla">La regla</h3>
<p>La asamblea <strong>no puede adoptar resoluciones</strong> sobre asuntos no incluidos en el orden del día.</p>
<h3 id="excepciones-1">Excepciones</h3>
<ol type="1">
<li><strong>Asamblea unánime</strong>
<ul>
<li>Está representado el <strong>100 % del capital con derecho a voto</strong>.</li>
<li>La decisión se adopta <strong>por unanimidad</strong>.</li>
</ul></li>
<li><strong>Designación de los accionistas que firmarán el acta</strong>
<ul>
<li>Puede resolverse aunque no figure en el orden del día (art. 73 LGS).</li>
</ul></li>
<li><strong>Supuestos expresamente autorizados por la ley</strong>
<ul>
<li>Ej.: remoción de directores y ejercicio de la acción social de responsabilidad cuando la cuestión surge incidentalmente del tratamiento de un punto incluido en el orden del día.</li>
<li>También las cuestiones <strong>directamente conexas y necesarias</strong>.</li>
</ul></li>
</ol>
<div class="callout callout-note callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>Los asistentes pueden <strong>debatir</strong> asuntos no incluidos en el orden del día.</p>
<p>Lo que <strong>no pueden hacer</strong> es adoptar resoluciones sobre ellos, salvo en las excepciones previstas por la ley.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>Orden del día: Efectos.</p>
<p>ARTICULO 246. — Es nula toda decisión sobre materias extrañas a las incluidas en el orden del día, salvo:</p>
<p>1º) Si estuviere presente la totalidad del capital y la decisión se adopte por unanimidad de las acciones con derecho a voto;</p>
<p>2º) Las excepciones que se autorizan expresamente en este Título;</p>
<p>3º) La elección de los encargados de suscribir el acta.</p>
</div>
</div>
</div>
</section>
<section id="cuarto-intermedio-art.-247-lgs" class="slide level1">
<h1>Cuarto intermedio (art. 247 LGS)</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Asamblea constituida]

--&gt; B[Cuarto intermedio]

--&gt; C[Reanudación]

--&gt; D[Continuación del tratamiento]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="qué-es">¿Qué es?</h3>
<p>Es la <strong>suspensión temporal</strong> de una asamblea ya constituida para reanudarla posteriormente.</p>
<h3 id="para-qué-sirve-2">¿Para qué sirve?</h3>
<ul>
<li>Obtener mayor información.</li>
<li>Permitir negociaciones entre los accionistas.</li>
<li>Favorecer la reflexión antes de decidir.</li>
</ul>
<h3 id="requisitos">Requisitos</h3>
<ul>
<li>Debe aprobarse por <strong>mayoría absoluta de los votos presentes</strong>.</li>
<li>En la <strong>asamblea unánime</strong>, por <strong>unanimidad</strong>.</li>
<li>Deben fijarse el <strong>día y la hora</strong> de la reanudación.</li>
<li>Solo puede disponerse <strong>una vez</strong>.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Las interrupciones breves durante el debate (por ejemplo, un receso de algunos minutos) <strong>no constituyen cuarto intermedio</strong>.</p>
</div>
</div>
</div>
</section>
<section id="reanudación-de-la-asamblea" class="slide level1">
<h1>Reanudación de la asamblea</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Registro para la primera reunión]

A --&gt; B[Habilitado para la reanudación]

B --&gt; C[Continúa la asamblea]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="quiénes-pueden-participar">¿Quiénes pueden participar?</h3>
<p>Solo los accionistas que <strong>estaban inscriptos para asistir a la primera reunión</strong>, aunque no hayan concurrido ese día.</p>
<h3 id="además">Además</h3>
<ul>
<li>Pueden asistir personalmente o por mandatario.</li>
<li>Es posible sustituir al mandatario durante el cuarto intermedio, cumpliendo las formalidades correspondientes.</li>
</ul>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>El accionista que no asistió a la primera reunión <strong>puede concurrir a la reanudación</strong>, pero <strong>no puede volver a discutir ni votar</strong> los puntos que ya fueron definitivamente resueltos antes del cuarto intermedio.</p>
</div>
</div>
</div>
</section>
<section id="el-acta-de-la-asamblea" class="slide level1">
<h1>El acta de la asamblea</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Celebración de la asamblea]

--&gt; B[Redacción del acta]

--&gt; C[Firma]

--&gt; D[Valor probatorio]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="qué-es-1">¿Qué es?</h3>
<p>El acta de asamblea es el <strong>documento privado</strong> que deja constancia de:</p>
<ul>
<li>la celebración de la asamblea;</li>
<li>las deliberaciones;</li>
<li>las resoluciones adoptadas.</li>
</ul>
<div class="callout callout-note callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Naturaleza jurídica</strong></p>
</div>
<div class="callout-content">
<p>El acta <strong>no es un requisito de validez</strong> de la asamblea.</p>
<p>Su confección constituye una <strong>obligación legal</strong> (arts. 73 y concordantes LGS) y cumple una función <strong>probatoria</strong>.</p>
</div>
</div>
</div>
</section>
<section id="contenido-esencial-del-acta" class="slide level1">
<h1>Contenido esencial del acta</h1>
<table class="caption-top">
<colgroup>
<col style="width: 60%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Debe contener</th>
<th style="text-align: left;">Ejemplos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Datos de la reunión</strong></td>
<td style="text-align: left;">Lugar, fecha, hora, clase de asamblea y convocatoria.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Constitución</strong></td>
<td style="text-align: left;">Accionistas presentes, acciones, votos y quórum.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Participantes</strong></td>
<td style="text-align: left;">Presidente, directores, síndicos, gerentes, inspectores y terceros.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Orden del día</strong></td>
<td style="text-align: left;">Puntos tratados y alteraciones aprobadas.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Deliberaciones</strong></td>
<td style="text-align: left;">Argumentos, impugnaciones y manifestaciones relevantes.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Votaciones</strong></td>
<td style="text-align: left;">Sentido de los votos, abstenciones y resultado.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Resoluciones</strong></td>
<td style="text-align: left;">Texto preciso de cada decisión adoptada.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Firmas</strong></td>
<td style="text-align: left;">Presidente y accionistas designados.</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>El acta debe reflejar <strong>fielmente</strong> lo ocurrido durante la asamblea.</p>
</div>
</div>
</div>
</section>
<section id="formalidades-y-derecho-de-información" class="slide level1">
<h1>Formalidades y derecho de información</h1>
<h3 id="formalidades">Formalidades</h3>
<ul>
<li>No debe contener espacios en blanco ni raspaduras.</li>
<li>Los errores deben salvarse antes de las firmas.</li>
<li>Si falta el libro de actas, puede confeccionarse un <strong>acta notarial</strong>.</li>
</ul>
<h3 id="copia-del-acta-art.-249-lgs">Copia del acta (art. 249 LGS)</h3>
<p>Todo accionista puede solicitar una copia:</p>
<ul>
<li><strong>a su costa</strong>;</li>
<li>a partir del <strong>quinto día</strong> de celebrada la asamblea.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Si el acta contiene información declarada <strong>confidencial</strong>, el accionista deberá asumir un compromiso de confidencialidad, salvo cuando la información deba utilizarse para ejercer derechos en sede judicial o arbitral.</p>
</div>
</div>
</div>
</section>
<section class="slide level1">

<h2 id="caso">Caso</h2>
<p>Finalizada la asamblea, un accionista solicita una copia del acta al día siguiente de la reunión.</p>
<p><strong>¿Tiene derecho a obtenerla inmediatamente?</strong></p>
<p><strong>Respuesta:</strong> No.</p>
<p>El art. 73 LGS concede hasta <strong>cinco días</strong> para confeccionar y firmar el acta. Recién a partir de ese momento el accionista puede ejercer el derecho previsto en el <strong>art. 249 LGS</strong> y obtener una copia a su costa.</p>
</section>
<section id="impugnacion-de-las-decisiones-asamblearias" class="slide level1">
<h1>IMPUGNACION DE LAS DECISIONES ASAMBLEARIAS</h1>
<p>Las decisiones tomadas por el érgano de gobierno -la asamblea- cuando resulten violatorias de la ley, el estatuto o el reglamento, se encuentran afectadas por un vicio que las torna ineficaces. Como todo acto juridico -aunque con caracteristicas especiales-, las decisiones tomadas por las asambleas pueden resultar -entonces-ineficaces y nulas.</p>
<p>La accion de nulidad de las decisiones tomadas por el 6rgano de gobierno de la sociedad -la asamblea- se encuentra reglamentada por los articulos 251 a 254 de la ley 19.550</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>Impugnación de la decisión asamblearia. Titulares.</p>
<p>ARTICULO 251. — Toda resolución de la asamblea adoptada en violación de la ley, el estatuto o el reglamento, puede ser impugnada de nulidad por los accionistas que no hubieren votado favorablemente en la respectiva decisión y por los ausentes que acrediten la calidad de accionistas a la fecha de la decisión impugnada. Los accionistas que votaron favorablemente pueden impugnarla si su voto es anulable por vicio de la voluntad.</p>
<p>También pueden impugnarla los directores, síndicos, miembros del consejo de vigilancia o la autoridad de contralor.</p>
<p>Promoción de la acción.</p>
<p>La acción se promoverá contra la sociedad, por ante el Juez de su domicilio, dentro de los tres (3) meses de clausurada la asamblea.</p>
<p>Suspensión preventiva de la ejecución.</p>
<p>ARTICULO 252. — El Juez puede suspender a pedido de parte, si existieren motivos graves y no mediare perjuicio para terceros, la ejecución de la resolución impugnada, previa garantía suficiente para responder por los daños que dicha medida pudiere causar a la sociedad.</p>
<p>Sustanciación de la causa. Acumulación de acciones.</p>
<p>ARTICULO 253. — Salvo el supuesto de la medida cautelar a que se refiere el artículo anterior, sólo se proseguirá el juicio después de vencido el término del artículo 251. Cuando exista pluralidad de acciones deberán acumularse, a cuyo efecto el directorio tendrá obligación de denunciar en cada expediente la existencia de las demás.</p>
<p>Representación.</p>
<p>Cuando la acción sea intentada por la mayoría de los directores o de miembros del consejo de vigilancia, los accionistas que votaron favorablemente designarán por mayoría un representante ad hoc, en asamblea especial convocada al efecto conforme al artículo 250. Si no se alcanzare esa mayoría, el representante será designado de entre ellos por el juez.</p>
<p>Responsabilidad de los accionistas.</p>
<p>ARTICULO 254. — Los accionistas que votaran favorablemente las resoluciones que se declaren nulas, responden ilimitada y solidariamente de las consecuencias de las mismas, sin perjuicio de la responsabilidad que corresponda a los directores, síndicos e integrantes del consejo de vigilancia.</p>
<p>Revocación del acuerdo impugnado.</p>
<p>Una asamblea posterior podrá revocar el acuerdo impugnado. Esta resolución surtirá efecto desde entonces y no procederá la iniciación o la continuación del proceso de impugnación. Subsistirá la responsabilidad por los efectos producidos o que sean su consecuencia directa.</p>
</div>
</div>
</div>
</section>
<section id="cuales-son-las-causales-de-impugnacién-de-decisiones-asamblearias-admitidas-por-la-ley" class="slide level1">
<h1>¿Cuales son las causales de impugnacién de decisiones asamblearias admitidas por la ley?</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Impugnación))
    Convocatoria
    Constitución
    Funcionamiento
    Deliberación
    Contenido
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Las decisiones de la asamblea pueden ser impugnadas por vicios que afecten:</p>
<ul>
<li>la <strong>convocatoria</strong>;</li>
<li>la <strong>constitución</strong> de la asamblea;</li>
<li>su <strong>funcionamiento</strong>;</li>
<li>la <strong>deliberación</strong>;</li>
<li>o el <strong>contenido</strong> de la resolución adoptada.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="vicios-en-la-convocatoria" class="slide level1">
<h1>Vicios en la convocatoria</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Convocatoria]

A --&gt; B[¿Se cumplieron las formalidades?]

B --&gt;|No| C[Vicio en la convocatoria]

C --&gt; D[Posible nulidad de la asamblea]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="la-convocatoria-comprende">La convocatoria comprende</h3>
<ul>
<li>La confección del orden del día.</li>
<li>La publicidad exigida por la ley.</li>
<li>El registro de asistencia.</li>
<li>El control de la calidad de accionista.</li>
<li>La verificación de representaciones y mandatos.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La convocatoria no consiste únicamente en <strong>citar a los accionistas</strong>.</p>
<p>Comprende <strong>todo el procedimiento previo</strong> necesario para que la asamblea pueda constituirse regularmente.</p>
</div>
</div>
</div>
</section>
<section id="consecuencias-de-los-vicios-en-la-convocatoria" class="slide level1">
<h1>Consecuencias de los vicios en la convocatoria</h1>
<table class="caption-top">
<colgroup>
<col style="width: 51%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Tipo de vicio</th>
<th style="text-align: left;">Consecuencia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Ausencia absoluta de convocatoria o de formalidades esenciales</strong></td>
<td style="text-align: left;">Nulidad de la asamblea.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Defectos parciales o irregularidades</strong></td>
<td style="text-align: left;">La nulidad dependerá de la entidad del vicio y de si afectó los derechos de los accionistas.</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Criterio general</strong></p>
</div>
<div class="callout-content">
<p>No toda irregularidad invalida una asamblea.</p>
<p>Debe analizarse si el defecto <strong>impidió o dificultó el ejercicio de los derechos de los accionistas</strong> o comprometió la regular formación de la voluntad social.</p>
</div>
</div>
</div>
</section>
<section id="caso-1" class="slide level1">
<h1>Caso</h1>
<p>El directorio convoca a una asamblea extraordinaria, pero omite publicar el aviso en el Boletín Oficial.</p>
<p>Uno de los accionistas no toma conocimiento de la reunión y no puede asistir.</p>
<p><strong>¿Puede impugnarse la asamblea?</strong></p>
<p>✅ <strong>Sí.</strong> La omisión de una formalidad esencial de la convocatoria puede afectar el derecho de participación del accionista y constituir una causal de nulidad.</p>
<p>En cambio, si el aviso fue publicado correctamente pero contiene un error menor que no impidió a los accionistas conocer la convocatoria ni ejercer sus derechos, <strong>no necesariamente</strong> corresponderá declarar la nulidad.</p>
</section>
<section id="vicios-en-el-acto-asambleario" class="slide level1">
<h1>VICIOS EN EL ACTO ASAMBLEARIO</h1>
<p>El acto tiene un régimen propio de funcionamiento y puede presentar vicios en su constitucion al haber cuestiones vinculadas al qudrum, a la representacion de los accionistas y aun también puede presentar problemas a lo largo de su celebracion en cuestiones vinculadas al derecho que tienen los accionistas de deliberar y votar.</p>
<p>Resultara nula -entonces- aquella asamblea en la cual las decisiones se hayan tomado: 1. Ignorando el régimen de quorum, deliberacién, informacién, o mayorias establecido por la ley, el estatuto o el reglamento; 2. En aquella votacion en la que hubieran participado accionistas sin derecho a voto, o inhabilitados para votar cuando, con la concurrencia de esos votos, se hubiera logrado una mayoria formativa de la voluntad social que no hubiera sido alcanzada sin dicha concurrencia.</p>
</section>
<section id="vicios-en-el-contenido-de-las-decisiones-de-la-asamblea" class="slide level1">
<h1>VICIOS EN EL CONTENIDO DE LAS DECISIONES DE LA ASAMBLEA</h1>
<p>La nulidad que afecta un acto asambleario también puede derivar de vicios en el contenido de la decisién particular adoptada.</p>
<p>Se trata de aquellos casos en los cuales la decisién importa adoptar una resolucién violatoria de la ley, el estatuto o el reglamento, debiendo entenderse en este punto que la referencia que el legislador de la ley 19.550 ha efectuado respecto del vocablo /ey no se limita al conjunto de normas contenidas en la ley 19.550 y complementarias sino a todo el ordenamiento juridico en general.</p>
</section>
<section id="quiénes-pueden-impugnar-una-decisión-asamblearia" class="slide level1">
<h1>¿Quiénes pueden impugnar una decisión asamblearia?</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Legitimados))
    Accionistas
      Presentes
      Ausentes
    Directores
    Síndicos
    Consejo de vigilancia
    Autoridad de control
    Terceros afectados
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>El art. 251 LGS reconoce legitimación para impugnar las resoluciones asamblearias a quienes resulten afectados por decisiones contrarias a la ley, el estatuto o el reglamento.</p>
</div>
</div>
</div>
</section>
<section id="accionistas-legitimados" class="slide level1">
<h1>Accionistas legitimados</h1>
<table class="caption-top">
<colgroup>
<col style="width: 40%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Accionista</th>
<th style="text-align: center;">¿Puede impugnar?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Votó en contra</td>
<td style="text-align: center;">✅ Sí</td>
</tr>
<tr class="even">
<td style="text-align: left;">Se abstuvo</td>
<td style="text-align: center;">✅ Sí</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Estuvo ausente</td>
<td style="text-align: center;">✅ Sí</td>
</tr>
<tr class="even">
<td style="text-align: left;">Votó a favor</td>
<td style="text-align: center;">❌ No, salvo que su voto esté viciado (error, dolo, violencia, etc.)</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Dos reglas importantes</strong></p>
</div>
<div class="callout-content">
<ul>
<li>No es necesario dejar constancia en el acta de que se impugnará judicialmente la decisión.</li>
<li>La ley <strong>no exige un porcentaje mínimo de acciones</strong> para promover la acción de impugnación.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="accionistas-ausentes" class="slide level1">
<h1>Accionistas ausentes</h1>
<h3 id="regla-general-1">Regla general</h3>
<p>El accionista que <strong>no asistió a la asamblea</strong> puede impugnar la resolución si:</p>
<ul>
<li>era accionista al momento de celebrarse la asamblea; y</li>
<li>acredita esa calidad al promover la acción.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La legitimación corresponde al <strong>accionista ausente</strong>, no a cualquier adquirente posterior de las acciones.</p>
</div>
</div>
</div>
</section>
<section id="un-debate-doctrinario" class="slide level1">
<h1>Un debate doctrinario</h1>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="régimen-legal">Régimen legal</h3>
<ul>
<li>Sólo puede impugnar quien era accionista al momento de la asamblea.</li>
<li>El adquirente posterior, como regla, <strong>no está legitimado</strong>.</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="crítica-de-vitolo">Crítica de Vitolo</h3>
<p>Quien adquiere acciones sucede al anterior titular en sus derechos.</p>
<p>Por ello, también debería poder impugnar resoluciones nulas mientras no haya vencido el plazo legal.</p>
</div></div>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>En los supuestos de <strong>nulidad absoluta</strong>, parte de la doctrina entiende que la legitimación podría ser más amplia, en virtud del art. 387 CCyC (“cualquier interesado”).</p>
</div>
</div>
</div>
</section>
<section id="casos-especiales-de-legitimación" class="slide level1">
<h1>Casos especiales de legitimación</h1>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Supuesto</th>
<th style="text-align: center;">¿Puede impugnar?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Acciones preferidas sin voto</td>
<td style="text-align: center;">✅ Sí</td>
</tr>
<tr class="even">
<td style="text-align: left;">Accionista con interés contrario (art. 248 LGS)</td>
<td style="text-align: center;">✅ Sí</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Accionista que votó a favor</td>
<td style="text-align: center;">⚠️ Sólo si su voto es anulable</td>
</tr>
</tbody>
</table>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La legitimación no depende únicamente de haber emitido un voto negativo.</p>
<p>También existe cuando la ley impide votar o cuando el consentimiento estuvo viciado.</p>
</div>
</div>
</div>
</section>
<section id="precisiones" class="slide level1">
<h1>Precisiones</h1>
<h3 id="acciones-preferidas-sin-derecho-a-voto">Acciones preferidas sin derecho a voto</h3>
<ul>
<li>Como regla, pueden impugnar porque <strong>no votaron favorablemente</strong>.</li>
<li>Si excepcionalmente tuvieron derecho a voto:
<ul>
<li>pueden impugnar si votaron en contra;</li>
<li>si se abstuvieron;</li>
<li>o si su voto favorable estuvo viciado.</li>
</ul></li>
</ul>
</section>
<section class="slide level1">

<h3 id="accionista-con-interés-contrario">Accionista con interés contrario</h3>
<p>El accionista impedido de votar por el art. 248 LGS conserva legitimación para impugnar.</p>
<p>No puede interpretarse que la prohibición de votar habilite a la mayoría a adoptar resoluciones ilegales.</p>
</section>
<section class="slide level1">

<h3 id="accionista-que-votó-favorablemente">Accionista que votó favorablemente</h3>
<p>Sólo conserva legitimación cuando demuestra que su voto fue emitido con <strong>error, dolo o violencia</strong>, es decir, que el consentimiento se encontraba viciado.</p>
</section>
<section id="directores-síndicos-y-consejo-de-vigilancia" class="slide level1">
<h1>Directores, síndicos y consejo de vigilancia</h1>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Legitimado</th>
<th style="text-align: left;">Fundamento</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Directores</strong></td>
<td style="text-align: left;">Deben impugnar las resoluciones contrarias a la ley, al estatuto, al reglamento o al interés social.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Síndicos</strong></td>
<td style="text-align: left;">Deben velar por la legalidad de los actos sociales e impugnar las decisiones inválidas.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Consejo de vigilancia</strong></td>
<td style="text-align: left;">Tiene el mismo deber de control de legalidad.</td>
</tr>
</tbody>
</table>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Para estos órganos, la impugnación <strong>no es sólo una facultad</strong>: constituye un <strong>deber derivado de sus funciones de administración o fiscalización</strong>.</p>
</div>
</div>
</div>
</section>
<section id="precisiones-1" class="slide level1">
<h1>Precisiones</h1>
<ul>
<li>Sólo están legitimados los <strong>directores titulares</strong>, no los suplentes.</li>
<li>El director debe ejercer el cargo al promover la demanda.</li>
<li>Si luego es removido, <strong>conserva la legitimación</strong>.</li>
<li>Si renuncia voluntariamente, la pierde.</li>
</ul>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Si la mayoría del directorio promueve la impugnación, la sociedad deberá ser representada en juicio por un <strong>representante ad hoc</strong> designado por los accionistas que sostienen la validez de la resolución (art. 253 LGS).</p>
</div>
</div>
</div>
</section>
<section id="contra-quién-se-dirige-la-demanda" class="slide level1">
<h1>¿Contra quién se dirige la demanda?</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Acción de impugnación] --&gt; B[Sociedad]

B --&gt; C[Representación por el Directorio]

C --&gt; D[Excepción: art. 253 LGS&lt;br/&gt;Representante ad hoc]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La demanda se dirige <strong>contra la sociedad</strong>, ya que es ella quien expresa su voluntad a través de la asamblea.</p>
</div>
</div>
</div>
</section>
<section id="acumulación-de-pretensiones" class="slide level1">
<h1>Acumulación de pretensiones</h1>
<p>Además de solicitar la nulidad de la resolución, el actor puede reclamar la responsabilidad de quienes participaron en el acto.</p>
<p>Ejemplos:</p>
<ul>
<li>Directores responsables (art. 254 LGS).</li>
<li>Accionistas cuya actuación haya generado el perjuicio.</li>
</ul>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>En ese caso, las acciones se acumulan en un mismo proceso y los responsables deben ser citados al juicio.</p>
</div>
</div>
</div>
</section>
<section id="plazo-y-juez-competente" class="slide level1">
<h1>Plazo y juez competente</h1>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Aspecto</th>
<th style="text-align: left;">Régimen</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Plazo</strong></td>
<td style="text-align: left;">3 meses</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Inicio del cómputo</strong></td>
<td style="text-align: left;">Clausura de la asamblea</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Juez competente</strong></td>
<td style="text-align: left;">Juez del domicilio social</td>
</tr>
</tbody>
</table>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>En la Ciudad Autónoma de Buenos Aires, la demanda requiere <strong>mediación previa obligatoria</strong> (Ley 26.589).</p>
</div>
</div>
</div>
</section>
<section id="efectos-de-la-sentencia" class="slide level1">
<h1>Efectos de la sentencia</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Sentencia que declara la nulidad]

A --&gt; B[La resolución queda sin efecto]

B --&gt; C[Obliga a la sociedad]

B --&gt; D[Obliga a todos los accionistas]

B --&gt; E[Obliga a los órganos sociales]

B --&gt; F[Produce efectos frente a terceros]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Los terceros que contrataron <strong>de buena fe</strong> confiando en la validez de la decisión podrán reclamar a la sociedad la indemnización de los daños sufridos.</p>
</div>
</div>
</div>
</section>
<section id="suspensión-preventiva-de-la-ejecución-art.-252-lgs" class="slide level1">
<h1>Suspensión preventiva de la ejecución (art. 252 LGS)</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Impugnación judicial]

A --&gt; B[Pedido de suspensión]

B --&gt; C{Requisitos}

C --&gt; D[Motivos graves]

C --&gt; E[Sin perjuicio para terceros]

C --&gt; F[Contracautela]

C --&gt; G[Verosimilitud del derecho y peligro en la demora]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La suspensión <strong>no invalida</strong> la resolución.</p>
<p>Simplemente <strong>impide su ejecución</strong> hasta que se dicte sentencia.</p>
</div>
</div>
</div>
</section>
<section id="naturaleza-de-la-suspensión-preventiva" class="slide level1">
<h1>Naturaleza de la suspensión preventiva</h1>
<h3 id="es-una-medida-cautelar">Es una medida cautelar</h3>
<ul>
<li>Tiene carácter <strong>provisorio</strong>.</li>
<li>Es accesoria de la acción de impugnación.</li>
<li>Busca evitar que la sentencia definitiva resulte ilusoria.</li>
</ul>
<h3 id="requisitos-principales">Requisitos principales</h3>
<ul>
<li>verosimilitud del derecho;</li>
<li>peligro en la demora;</li>
<li>contracautela;</li>
<li>inexistencia de perjuicio para terceros.</li>
</ul>
</section>
<section id="acumulación-de-acciones-art.-253-lgs" class="slide level1">
<h1>Acumulación de acciones (art. 253 LGS)</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Impugnación 1]

B[Impugnación 2]

C[Impugnación 3]

A --&gt; D[Un único proceso]

B --&gt; D

C --&gt; D
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Todas las acciones promovidas contra una misma resolución deben acumularse para evitar sentencias contradictorias.</p>
</div>
</div>
</div>
</section>
<section id="responsabilidad-por-la-decisión-impugnada" class="slide level1">
<h1>Responsabilidad por la decisión impugnada</h1>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Sujetos</th>
<th style="text-align: left;">Responsabilidad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Accionistas que votaron a favor</td>
<td style="text-align: left;">Ilimitada y solidaria</td>
</tr>
<tr class="even">
<td style="text-align: left;">Directores</td>
<td style="text-align: left;">Si incumplieron sus deberes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Síndicos</td>
<td style="text-align: left;">Si omitieron el control debido</td>
</tr>
<tr class="even">
<td style="text-align: left;">Consejo de vigilancia</td>
<td style="text-align: left;">En los mismos términos</td>
</tr>
</tbody>
</table>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La nulidad de la resolución no excluye la responsabilidad por los daños ocasionados.</p>
</div>
</div>
</div>
</section>
<section id="revocación-del-acuerdo-art.-254-lgs" class="slide level1">
<h1>Revocación del acuerdo (art. 254 LGS)</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Asamblea posterior]

A --&gt; B[Revoca el acuerdo]

B --&gt; C[La impugnación pierde objeto]

C --&gt; D[Pero subsiste la responsabilidad]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La sociedad puede dejar sin efecto el acuerdo impugnado.</p>
<p>Sin embargo, ello <strong>no libera de responsabilidad</strong> a quienes ocasionaron los daños mientras la resolución produjo efectos.</p>
</div>
</div>
</div>
</section>
<section id="fallo-kahl-c.-degas-s.a." class="slide level1">
<h1>Fallo: <em>Kahl c.&nbsp;Degas S.A.</em></h1>
<p><strong>CNCom., Sala E, 12 de mayo de 2006</strong></p>
<h3 id="tema">Tema</h3>
<p>Impugnación de una asamblea extraordinaria que dispuso un aumento de capital mediante capitalización de aportes irrevocables.</p>
<p>La accionante sostuvo que la decisión tuvo como finalidad diluir ilegítimamente su participación societaria.</p>
</section>
<section id="hechos" class="slide level1">
<h1>Hechos</h1>
<p>La sociedad resolvió:</p>
<ul>
<li>aumentar el capital social;</li>
<li>capitalizar aportes irrevocables;</li>
<li>hacerlo mediante una asamblea cuya convocatoria fue cuestionada.</li>
</ul>
<p>La accionista sostuvo que el verdadero objetivo era <strong>licuar su participación del 50 %</strong>, vulnerando sus derechos como socia.</p>
</section>
<section id="caducidad-o-prescripción" class="slide level1">
<h1>¿Caducidad o prescripción?</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Art. 251 LGS]

A --&gt; B[Regla: 3 meses]

A --&gt; C[Excepción]

C --&gt; D[Violación de derechos inderogables u orden público]

D --&gt; E[No rige la caducidad]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La Cámara entendió que, cuando la impugnación se funda en la lesión de derechos inderogables del socio o del orden público, <strong>no resulta aplicable el plazo de caducidad del art. 251 LGS</strong>. :contentReference<span data-index="3">oaicite:3</span></p>
</div>
</div>
</div>
</section>
<section id="legitimación-e-interés-social" class="slide level1">
<h1>Legitimación e interés social</h1>
<p>La sociedad sostuvo que la actora no estaba legitimada porque no había acreditado adecuadamente su calidad de socia.</p>
<p>La Cámara rechazó esa defensa y afirmó que:</p>
<ul>
<li>la calidad de socio puede probarse por distintos medios;</li>
<li>la acción de impugnación protege el <strong>interés social</strong>, pero también puede ejercerse para tutelar el <strong>interés personal del socio</strong>, cuando ese interés deriva de su condición de accionista.</li>
</ul>
</section>
<section id="enseñanzas-del-fallo" class="slide level1">
<h1>Enseñanzas del fallo</h1>
<h3 id="principios-que-deja">Principios que deja</h3>
<ul>
<li>Un aumento de capital no puede utilizarse para excluir o diluir arbitrariamente a un accionista.</li>
<li>La impugnación protege tanto el interés social como los derechos esenciales de los socios.</li>
<li>La legitimación no depende exclusivamente de la exhibición de los títulos accionarios.</li>
<li>Cuando se afectan derechos inderogables, el régimen del art. 251 LGS debe interpretarse de manera restrictiva. :contentReference<span data-index="6">oaicite:6</span></li>
</ul>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>Idea central</strong></p>
<p>La mayoría no puede utilizar los mecanismos societarios para alterar abusivamente el equilibrio entre los socios.</p>
</div>
</div>
</div>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 4.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiado");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiado");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>