<!DOCTYPE html>
<html lang="es"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Prof.&nbsp;Maximiliano Lucas Romei">
  <title>Sociedades Civiles y Comerciales – Clase 13 — SA - Representación</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-0427d8d92a431aa6a6430e53ec02a470.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
  <script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
  <link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Clase 13 — SA - Representación</h1>
  <p class="subtitle">Sociedades Civiles y Comerciales · UBA · Curso intensivo 2026</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Maximiliano Lucas Romei 
</div>
</div>
</div>

</section>
<section id="el-directorio" class="slide level1">
<h1>El directorio</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Sociedad Anónima]

A --&gt; B[Asamblea]

A --&gt; C[Directorio]

A --&gt; D[Fiscalización]

C --&gt; E[Administra]

E --&gt; F[Gestiona diariamente la sociedad]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h2 id="el-directorio-1">El directorio</h2>
<ul>
<li>Es el <strong>órgano de administración</strong> de la sociedad anónima.</li>
<li>Tiene carácter <strong>necesario</strong> y <strong>permanente</strong>.</li>
<li>Dirige la actividad cotidiana de la sociedad.</li>
<li>Ejecuta las decisiones necesarias para el desarrollo de la empresa.</li>
</ul>
</section>
<section id="por-qué-existe-el-voto-acumulativo" class="slide level1">
<h1>¿Por qué existe el voto acumulativo?</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Mayoría]

A --&gt; B[Elige todo el directorio]

C[Minoría]

C -.-&gt; D[Queda sin representación]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h2 id="problema">Problema</h2>
<p>Si todos los directores se eligen por mayoría simple, el grupo mayoritario puede ocupar la totalidad del directorio.</p>
<h2 id="objetivo-del-art.-263-lgs">Objetivo del art. 263 LGS</h2>
<p>Permitir que una <strong>minoría relevante</strong> pueda acceder al órgano de administración sin alterar el control de la mayoría.</p>
</section>
<section id="qué-es-el-voto-acumulativo" class="slide level1">
<h1>¿Qué es el voto acumulativo?</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Cada acción = 1 voto]

A --&gt; B[Se multiplican los votos]

B --&gt; C[Se concentran en uno o varios candidatos]

C --&gt; D[La minoría puede obtener un director]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="idea-central">Idea central</h3>
<p>El accionista multiplica los votos que normalmente tendría por el número de directores a elegir y puede concentrarlos en uno o varios candidatos.</p>
<p>No aumenta su participación accionaria.</p>
<p>Aumenta únicamente el <strong>peso de su voto</strong> para la elección del tercio del directorio.</p>
</section>
<section id="requisitos-para-utilizar-el-sistema" class="slide level1">
<h1>Requisitos para utilizar el sistema</h1>
<ul>
<li>Directorio plural.</li>
<li>Al menos <strong>tres directores</strong>.</li>
<li>Sólo puede utilizarse respecto de <strong>hasta un tercio de las vacantes</strong>.</li>
<li>No procede cuando el estatuto prevé elección por clases de acciones (art. 262 LGS).</li>
<li>El estatuto no puede eliminar ni dificultar este derecho.</li>
</ul>
</section>
<section id="procedimiento" class="slide level1">
<h1>Procedimiento</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Notificación previa
3 días hábiles]

--&gt; B[La sociedad informa]

--&gt; C[El presidente comunica en la asamblea]

--&gt; D[Todos pueden utilizar el sistema]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="aspectos-importantes">Aspectos importantes</h3>
<ul>
<li>Basta que un accionista comunique su decisión.</li>
<li>Desde ese momento todos los presentes pueden votar acumulativamente.</li>
<li>Luego esa decisión no puede dejar sin efecto el mecanismo.</li>
</ul>
</section>
<section id="ejemplo" class="slide level1">
<h1>Ejemplo</h1>
<h2 id="directorio-de-tres-miembros">Directorio de tres miembros</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Accionista</th>
<th style="text-align: right;">Participación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td style="text-align: right;">70 %</td>
</tr>
<tr class="even">
<td>B</td>
<td style="text-align: right;">30 %</td>
</tr>
</tbody>
</table>
<h3 id="sistema-común">Sistema común</h3>
<p>A designa los <strong>3 directores</strong>.</p>
<h3 id="voto-acumulativo">Voto acumulativo</h3>
<p>El socio B concentra sus votos en un solo candidato y logra elegir <strong>1 director</strong>.</p>
<p>La mayoría conserva <strong>2 directores</strong>.</p>
</section>
<section id="cómo-se-emite-el-voto" class="slide level1">
<h1>¿Cómo se emite el voto?</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Voto ordinario]

--&gt; B[Compite por todos los cargos]

C[Voto acumulativo]

--&gt; D[Compite sólo por el tercio]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Los accionistas que utilizan el sistema ordinario votan por la totalidad del directorio.</p>
<p>Quienes utilizan voto acumulativo concentran sus votos únicamente respecto del tercio reservado.</p>
</section>
<section id="ideas-principales" class="slide level1">
<h1>Ideas principales</h1>
<div class="callout callout-tip callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Recordar</strong></p>
</div>
<div class="callout-content">
<ul>
<li>✔ Protege a la minoría.</li>
<li>✔ No elimina el principio mayoritario.</li>
<li>✔ No modifica la cantidad de acciones.</li>
<li>✔ Sólo modifica la forma de computar los votos.</li>
<li>✔ Es un derecho irrenunciable de los accionistas.</li>
</ul>
</div>
</div>
</div>
<blockquote>
<p><strong>El voto acumulativo procura que la minoría tenga voz en el directorio, pero sin desplazar a la mayoría del control de la sociedad.</strong></p>
</blockquote>
</section>
<section id="ejemplo-de-voto-acumulativo" class="slide level1">
<h1>Ejemplo de voto acumulativo</h1>
<h2 id="sociedad-anónima">Sociedad Anónima</h2>
<ul>
<li>Capital: <strong>100 acciones</strong></li>
<li>Cada acción = <strong>1 voto</strong></li>
<li>Directorio: <strong>3 miembros</strong></li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Accionista</th>
<th style="text-align: right;">Acciones</th>
<th style="text-align: right;">Participación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">70 %</td>
</tr>
<tr class="even">
<td>B</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">30 %</td>
</tr>
</tbody>
</table>
</section>
<section class="slide level1">

<h2 id="sin-voto-acumulativo">Sin voto acumulativo</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Socio A&lt;br/&gt;70 votos]

--&gt; D[Director 1]

--&gt; E[Director 2]

--&gt; F[Director 3]

B[Socio B&lt;br/&gt;30 votos]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h3 id="resultado">Resultado</h3>
<ul>
<li>Director 1 → A</li>
<li>Director 2 → A</li>
<li>Director 3 → A</li>
</ul>
<p><strong>La minoría queda sin representación.</strong></p>
</section>
<section id="el-mismo-ejemplo-con-voto-acumulativo" class="slide level1">
<h1>El mismo ejemplo con voto acumulativo</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Socio A&lt;br/&gt;70 votos]

--&gt; D[Director 1]

--&gt; E[Director 2]

B[Socio B&lt;br/&gt;30 × 3 = 90 votos]

--&gt; F[Director 3]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h2 id="resultado-1">Resultado</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Cargo</th>
<th>Elegido por</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Director 1</td>
<td>Mayoría</td>
</tr>
<tr class="even">
<td>Director 2</td>
<td>Mayoría</td>
</tr>
<tr class="odd">
<td>Director 3</td>
<td>Minoría</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>El socio minoritario <strong>concentra</strong> todos sus votos sobre un único candidato y logra elegir un director.</p>
<p>La mayoría mantiene el control del directorio.</p>
</div>
</div>
</div>
</section>
<section id="qué-ocurre-si-la-minoría-sólo-tiene-el-20" class="slide level1">
<h1>¿Qué ocurre si la minoría sólo tiene el 20 %?</h1>
<h2 id="datos">Datos</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Accionista</th>
<th style="text-align: right;">Participación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td style="text-align: right;">80 %</td>
</tr>
<tr class="even">
<td>B</td>
<td style="text-align: right;">20 %</td>
</tr>
</tbody>
</table>
<h3 id="voto-acumulativo-1">Voto acumulativo</h3>
<ul>
<li>Socio A → 80 votos por candidato.</li>
<li>Socio B → 20 × 3 = <strong>60 votos</strong>.</li>
</ul>
<h2 id="resultado-2">Resultado</h2>
<p>El socio minoritario <strong>ya no alcanza</strong> los votos necesarios para superar a la mayoría.</p>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>El voto acumulativo <strong>no garantiza</strong> representación.</p>
<p>Sólo la facilita cuando la minoría posee una participación suficientemente significativa.</p>
</div>
</div>
</div>
</section>
<section id="reelección-de-los-directores" class="slide level1">
<h1>Reelección de los directores</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Finaliza el mandato]

--&gt; B{Asamblea}

B --&gt;|Reelige| C[Continúa en el cargo]

B --&gt;|No reelige| D[Cesa el mandato]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h2 id="principio">Principio</h2>
<p>El <strong>art. 256 LGS</strong> establece que los directores son <strong>reelegibles</strong>.</p>
<h3 id="consecuencias">Consecuencias</h3>
<ul>
<li>No existe un límite legal a la cantidad de reelecciones.</li>
<li>La continuidad depende exclusivamente de la voluntad del órgano competente.</li>
<li>Cada nuevo mandato requiere una nueva designación por la asamblea.</li>
</ul>
</section>
<section id="revocación-del-director" class="slide level1">
<h1>Revocación del director</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Asamblea]

--&gt; B[Revoca la designación]

--&gt; C[Cesa el director]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h2 id="revocación-ad-nutum">Revocación <em>ad nutum</em></h2>
<p>La asamblea puede remover al director <strong>sin necesidad de invocar una justa causa</strong>.</p>
<h3 id="importante">Importante</h3>
<ul>
<li>La reelección y la remoción requieren una <strong>decisión expresa de la asamblea ordinaria</strong> (art. 234, inc. 2°, LGS).</li>
<li>El estatuto no puede establecer renovaciones automáticas del mandato ni remociones tácitas.</li>
</ul>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>El cargo de director es esencialmente <strong>transitorio</strong>: su permanencia depende de la confianza que le otorgue la asamblea y del adecuado cumplimiento de sus deberes.</p>
</div>
</div>
</div>
</section>
<section id="garantía-de-los-directores" class="slide level1">
<h1>Garantía de los directores</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Director]

--&gt; B[Asume funciones]

--&gt; C[Debe constituir garantía]

--&gt; D[Protección del interés social]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h2 id="fundamento">Fundamento</h2>
<p>El director administra el patrimonio ajeno y responde por los daños que pueda ocasionar en el ejercicio de sus funciones.</p>
<p>Por ello, el <strong>art. 256 LGS</strong> exige que preste una <strong>garantía a favor de la sociedad</strong>.</p>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La garantía procura facilitar la reparación de los daños derivados de una eventual responsabilidad del director.</p>
</div>
</div>
</div>
</section>
<section id="cómo-puede-constituirse-la-garantía" class="slide level1">
<h1>¿Cómo puede constituirse la garantía?</h1>
<p>La <strong>RG IGJ 7/2015</strong> admite, entre otras, las siguientes modalidades:</p>
<ul>
<li>bonos o títulos públicos;</li>
<li>dinero depositado en entidades financieras;</li>
<li>avales o fianzas;</li>
<li>seguro de caución;</li>
<li>seguro de responsabilidad civil.</li>
</ul>
<h3 id="importante-1">Importante</h3>
<ul>
<li>La garantía corresponde a los <strong>directores titulares</strong>.</li>
<li>Los suplentes sólo deben constituirla cuando asumen efectivamente el cargo.</li>
<li>No puede integrarse mediante un simple ingreso de dinero a la caja social.</li>
</ul>
</section>
<section id="aspectos-reglamentarios" class="slide level1">
<h1>Aspectos reglamentarios</h1>
<div class="columns">
<div class="column" style="width:55%;">
<h3 id="la-reglamentación-dispone">La reglamentación dispone</h3>
<ul>
<li>la garantía debe mantenerse durante el plazo previsto para el ejercicio de acciones de responsabilidad;</li>
<li>el monto debe ser uniforme para todos los directores;</li>
<li>la IGJ establece montos mínimos y máximos para las sociedades sujetas a su fiscalización.</li>
</ul>
</div><div class="column" style="width:45%;">
<div class="callout callout-tip callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Idea central</strong></p>
</div>
<div class="callout-content">
<p>La garantía <strong>no reemplaza la responsabilidad</strong> del director.</p>
<p>Simplemente constituye un mecanismo destinado a reforzar la tutela del patrimonio social.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="duración-del-mandato" class="slide level1">
<h1>Duración del mandato</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Designación]

--&gt; B[Mandato]

--&gt; C[Reemplazo]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h2 id="regla-general-art.-255-lgs">Regla general (art. 255 LGS)</h2>
<ul>
<li>El estatuto fija la duración del cargo.</li>
<li>Cada mandato no puede exceder de <strong>tres ejercicios</strong>.</li>
</ul>
<h2 id="excepción">Excepción</h2>
<p>Cuando los directores son designados por el <strong>Consejo de Vigilancia</strong> (art. 281, inc. d), el mandato puede extenderse hasta <strong>cinco ejercicios</strong>.</p>
</section>
<section id="permanencia-en-el-cargo" class="slide level1">
<h1>Permanencia en el cargo</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Vence el mandato]

--&gt; B{¿Hay reemplazo?}

B --&gt;|No| C[Continúa en funciones]

B --&gt;|Sí| D[Cesa el director]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h2 id="principio-de-continuidad">Principio de continuidad</h2>
<p>Aunque el mandato haya vencido, el director <strong>permanece en funciones hasta ser reemplazado</strong>.</p>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Esto evita que la sociedad quede sin órgano de administración por el mero vencimiento del plazo.</p>
</div>
</div>
</div>
</section>
<section id="reemplazo-de-directores" class="slide level1">
<h1>Reemplazo de directores</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Vacancia]

--&gt; B{¿Hay directores suplentes?}

B --&gt;|Sí| C[Asume el suplente]

B --&gt;|No| D[Interviene la sindicatura]

D --&gt; E[Designa reemplazante hasta la próxima asamblea]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h2 id="regla-del-art.-258-lgs">Regla del art. 258 LGS</h2>
<p>El estatuto puede prever la existencia de <strong>directores suplentes</strong>, quienes reemplazan a los titulares cuando se produce una vacancia.</p>
<p>Si no existen suplentes, el reemplazo corresponde a la <strong>sindicatura</strong> hasta la próxima asamblea.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>Reemplazo de los directores.</p>
<p>ARTICULO 258. — El estatuto podrá establecer la elección de suplentes para subsanar la falta de los directores por cualquier causa. Esta previsión es obligatoria en las sociedades que prescinden de sindicatura.</p>
<p>En caso de vacancia, los síndicos designarán el reemplazante hasta la reunión de la próxima asamblea, si el estatuto no prevé otra forma de nombramiento.</p>
</div>
</div>
</div>
</section>
<section id="particularidades" class="slide level1">
<h1>Particularidades</h1>
<h3 id="director-suplente">Director suplente</h3>
<ul>
<li>Reemplaza al titular por cualquier causa.</li>
<li>Asume según el orden de designación.</li>
</ul>
<h3 id="director-elegido-por-clase-de-acciones">Director elegido por clase de acciones</h3>
<p>Si el director titular fue elegido por una determinada <strong>clase de acciones</strong> (art. 262 LGS), debe ser reemplazado por el suplente correspondiente a esa misma clase.</p>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Cuando la sociedad prescinde de sindicatura (art. 284 LGS), la designación de <strong>directores suplentes es obligatoria</strong>, ya que no existirá un órgano que pueda cubrir transitoriamente las vacancias.</p>
</div>
</div>
</div>
</section>
<section id="régimen-especial-de-suplencias" class="slide level1">
<h1>Régimen especial de suplencias</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Director con funciones específicas]

--&gt; B[Vacancia]

--&gt; C[Suplente previamente asignado]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Cuando existen funciones individualizadas, el estatuto, el reglamento o la asamblea pueden prever que <strong>cada director suplente reemplace a un director titular determinado</strong>.</p>
<p>Si la ausencia es definitiva, el reemplazo no presenta dificultades.</p>
<p>Cuando las ausencias son transitorias y sucesivas, los suplentes se incorporarán alternativamente conforme al régimen de reemplazos previsto.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>La ley 19550 no ha creado para las directres y síndicos suplentes obligaciones similares a las de las personas que revisten el cargo de órgano administrativo o de contralor. Sólo en la expectativa de ser llamados a cubrir a vacancia en caso de ausencia de su titular. Al ser suplentes, no tienen responsabilidad ni obligaciones y no integran el órgano directivo, pues el desempeño de la titularidad es excluyente. “lraben SA s/Quiebra” - CNCom. - Sala C - 25/10/1995</p>
</div>
</div>
</div>
</section>
<section id="renuncia-del-director" class="slide level1">
<h1>Renuncia del director</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Renuncia]

--&gt; B[Directorio]

--&gt; C{¿Puede aceptarla?}
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El director puede renunciar en cualquier momento.</p>
<p>Según el <strong>art. 259 LGS</strong>, el directorio debe aceptar la renuncia en la primera reunión posterior a su presentación, siempre que:</p>
<ul>
<li>no afecte el funcionamiento regular del órgano;</li>
<li>no sea dolosa; y</li>
<li>no sea intempestiva.</li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>Renuncia de directores.</p>
<p>ARTICULO 259. — El directorio deberá aceptar la renuncia del director, en la primera reunión que celebre después de presentada siempre que no afectare su funcionamiento regular y no fuere dolosa o intempestiva, lo que deberá constar en el acta pertinente. De lo contrario, el renunciante debe continuar en funciones hasta tanto la próxima asamblea se pronuncie.</p>
</div>
</div>
</div>
</section>
<section id="alcance-del-funcionamiento-regular" class="slide level1">
<h1>Alcance del funcionamiento regular</h1>
<p>Vítolo entiende que la expresión <strong>“afectar el funcionamiento regular del órgano”</strong> debe interpretarse en relación con la posibilidad de que el directorio continúe sesionando válidamente.</p>
<p>No se refiere a la distribución interna de tareas ni a la asignación de áreas específicas de responsabilidad.</p>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Lo que el legislador procura preservar es el <strong>quórum</strong> y la continuidad del órgano de administración.</p>
</div>
</div>
</div>
</section>
<section id="inscripción-de-la-designación-y-cese" class="slide level1">
<h1>Inscripción de la designación y cese</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Designación o cese]

--&gt; B[Registro Público]

--&gt; C[Legajo de la sociedad]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<h2 id="artículo-60-lgs">Artículo 60 LGS</h2>
<p>Toda designación o cesación de administradores debe:</p>
<ul>
<li>inscribirse en el Registro Público;</li>
<li>incorporarse al legajo de la sociedad;</li>
<li>publicarse, cuando corresponda.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La publicidad registral procura brindar seguridad a los terceros que contratan con la sociedad.</p>
</div>
</div>
</div>
</section>
<section id="efectos-de-la-falta-de-inscripción" class="slide level1">
<h1>Efectos de la falta de inscripción</h1>
<p>La falta de inscripción del cese del director constituye una modificación <strong>no inscripta</strong>.</p>
<h3 id="consecuencia">Consecuencia</h3>
<p>La cesación <strong>no es oponible a los terceros</strong>.</p>
<p>Sin embargo, esa inoponibilidad se vincula exclusivamente con el <strong>régimen de representación</strong>.</p>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>El tercero que desconoce la cesación puede considerar vigente la representación del director que aún figura inscripto.</p>
</div>
</div>
</div>
</section>
<section id="inscripción-de-la-renuncia" class="slide level1">
<h1>Inscripción de la renuncia</h1>
<p>El director que cesó en el cargo posee legitimación para solicitar la inscripción de su renuncia.</p>
<p>Si la sociedad no entrega la documentación necesaria ni promueve el trámite registral:</p>
<ul>
<li>el director puede denunciar esa circunstancia ante el Registro Público;</li>
<li>la autoridad de control intimará a la sociedad a cumplir;</li>
<li>el incumplimiento puede dar lugar a la aplicación de sanciones.</li>
</ul>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La inscripción registral evita que el director continúe apareciendo frente a terceros como representante de la sociedad.</p>
</div>
</div>
</div>
</section>
<section id="impugnación-de-las-decisiones-del-directorio" class="slide level1">
<h1>Impugnación de las decisiones del directorio</h1>
<h2 id="un-vacío-de-la-lgs">Un vacío de la LGS</h2>
<p>La Ley General de Sociedades <strong>no regula expresamente</strong> la impugnación de las resoluciones del directorio.</p>
<p>A diferencia de las resoluciones de la asamblea, no existe un régimen específico semejante al previsto en los <strong>arts. 251 a 254 LGS</strong></p>
</section>
<section id="solución-doctrinaria-y-jurisprudencial" class="slide level1">
<h1>Solución doctrinaria y jurisprudencial</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Resolución del directorio]

--&gt; B[Impugnación]

--&gt; C[Aplicación analógica de los arts. 251 a 254 LGS]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La doctrina y la jurisprudencia mayoritarias admiten la impugnación de las decisiones del directorio aplicando <strong>por analogía</strong> el régimen previsto para la impugnación de las resoluciones asamblearias.</p>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Se utilizan las mismas causales y un procedimiento semejante al de los arts. 251 y siguientes de la LGS.</p>
</div>
</div>
</div>
</section>
<section id="legitimación-y-acumulación-de-acciones" class="slide level1">
<h1>Legitimación y acumulación de acciones</h1>
<p>La acción de impugnación debe dirigirse <strong>contra la sociedad</strong>, ya que el acto impugnado emana de uno de sus órganos.</p>
<p>Además, por aplicación analógica del <strong>art. 254 LGS</strong>, puede acumularse:</p>
<ul>
<li>la acción de impugnación; y</li>
<li>la acción de responsabilidad contra los directores que aprobaron la decisión,</li>
</ul>
<p>siempre que el acuerdo haya sido ejecutado y haya ocasionado daños al patrimonio social.</p>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La impugnación procura invalidar la decisión; la acción de responsabilidad busca reparar los daños derivados de su ejecución.</p>
</div>
</div>
</div>
</section>
<section id="remuneración-de-los-directores" class="slide level1">
<h1>Remuneración de los directores</h1>
<p>La función del director se presume <strong>remunerada</strong>.</p>
<p>La remuneración constituye la contraprestación por el ejercicio de la administración de la sociedad y por el cumplimiento de los deberes impuestos por el <strong>art. 59 LGS</strong>.</p>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La relación entre el director y la sociedad es una relación de servicios calificada.</p>
</div>
</div>
</div>
</section>
<section id="quién-fija-la-remuneración" class="slide level1">
<h1>¿Quién fija la remuneración?</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Estatuto]

--&gt; D[Remuneración]

B[Consejo de Vigilancia]

--&gt; D

C[Asamblea Ordinaria]

--&gt; D
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La remuneración puede ser establecida por:</p>
<ul>
<li>el <strong>estatuto</strong>;</li>
<li>el <strong>Consejo de Vigilancia</strong>, cuando corresponda; o</li>
<li>la <strong>Asamblea Ordinaria</strong>, si el estatuto guarda silencio.</li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>Remuneración.</p>
<p>ARTICULO 261. — El estatuto podrá establecer la remuneración del directorio y del consejo de vigilancia; en su defecto, la fijará la asamblea o el consejo de vigilancia en su caso.</p>
<p>El monto máximo de las retribuciones que por todo concepto puedan percibir los miembros del directorio y del consejo de vigilancia en su caso, incluidos sueldos y otras remuneraciones por el desempeño de funciones técnico-administrativas de carácter permanente, no podrán exceder del veinticinco por ciento (25%) de las ganancias.</p>
<p>Dicho monto máximo se limitará al cinco por ciento (5%) cuando no se distribuyan dividendos a los accionistas, y se incrementará proporcionalmente a la distribución, hasta alcanzar aquel límite cuando se reparta el total de las ganancias. A los fines de la aplicación de esta disposición, no se tendrá en cuenta la reducción en la distribución de dividendos, resultante de deducir las retribuciones del Directorio y del Consejo de Vigilancia.</p>
<p>Cuando el ejercicio de comisiones especiales o de funciones técnico administrativas por parte de uno o más directores, frente a lo reducido o a la inexistencia de ganancias impongan la necesidad de exceder los límites prefijados, sólo podrán hacerse efectivas tales remuneraciones en exceso si fuesen expresamente acordadas por la asamblea de accionistas, a cuyo efecto deberá incluirse el asunto como uno de los puntos del orden del día.</p>
</div>
</div>
</div>
</section>
<section id="límites-legales" class="slide level1">
<h1>Límites legales</h1>
<p>El <strong>art. 261 LGS</strong> establece límites máximos a la remuneración del directorio.</p>
<h3 id="regla-general">Regla general</h3>
<ul>
<li>hasta el <strong>25 %</strong> de las ganancias del ejercicio.</li>
</ul>
<h3 id="si-no-se-distribuyen-dividendos">Si no se distribuyen dividendos</h3>
<ul>
<li>el límite se reduce al <strong>5 %</strong>.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>A medida que aumenta la distribución de dividendos, también puede incrementarse la remuneración del directorio, hasta alcanzar el límite del 25 %.</p>
</div>
</div>
</div>
</section>
<section id="excepción-1" class="slide level1">
<h1>Excepción</h1>
<p>La asamblea puede autorizar una remuneración superior a los límites legales cuando:</p>
<ul>
<li>uno o más directores desempeñen <strong>funciones técnico-administrativas</strong> o <strong>comisiones especiales</strong>; y</li>
<li>la remuneración ordinaria resulte insuficiente.</li>
</ul>
<h3 id="requisito">Requisito</h3>
<p>La cuestión debe incluirse <strong>expresamente en el orden del día</strong> y la asamblea debe justificar la razonabilidad de la decisión.</p>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La superación de los límites del art. 261 constituye un supuesto excepcional que requiere una decisión específica de la asamblea.</p>
</div>
</div>
</div>
</section>
<section id="prohibiciones-e-incompatibilidades" class="slide level1">
<h1>Prohibiciones e incompatibilidades</h1>
<h2 id="artículo-264-lgs">Artículo 264 LGS</h2>
<p>La ley establece determinadas <strong>prohibiciones e incompatibilidades</strong> para desempeñarse como director o gerente de una sociedad anónima.</p>
<p>Su finalidad es asegurar que quienes integran el órgano de administración posean:</p>
<ul>
<li>plena capacidad para ejercer sus funciones;</li>
<li>aptitud para asumir las responsabilidades del cargo; y</li>
<li>independencia respecto de situaciones incompatibles con la administración social.</li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>ARTICULO 264. — No pueden ser directores ni gerentes:</p>
<p>1º) Quienes no pueden ejercer el comercio;</p>
<p>2º) Los fallidos por quiebra culpable o fraudulenta hasta diez (10) años después de su rehabilitación, los fallidos por quiebra casual o los concursados hasta cinco (5) años después de su rehabilitación; los directores y administradores de sociedad cuya conducta se calificare de culpable o fraudulenta, hasta diez (10) años después de su rehabilitación.</p>
<p>3º) Los condenados con accesoria de inhabilitación de ejercer cargos públicos; los condenados por hurto, robo, defraudación, cohecho, emisión de cheques sin fondos y delitos contra la fe pública; los condenados por delitos cometidos en la constitución, funcionamiento y liquidación de sociedades. En todos los casos hasta después de diez (10) años de cumplida la condena;</p>
<p>4º) Los funcionarios de la administración pública cuyo desempeño se relacione con el objeto de la sociedad, hasta dos (2) años del cese de sus funciones.</p>
</div>
</div>
</div>
</section>
<section id="personas-incapaces" class="slide level1">
<h1>Personas incapaces</h1>
<h2 id="inciso-1">Inciso 1°</h2>
<p>Tras la entrada en vigencia del Código Civil y Comercial desapareció la noción de <strong>capacidad para ejercer el comercio</strong>.</p>
<p>Según Vítolo, actualmente la norma debe entenderse referida a quienes:</p>
<ul>
<li>no sean mayores de edad; o</li>
<li>carezcan de capacidad para ejercer por sí mismos sus derechos.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La referencia legal al “ejercicio del comercio” debe interpretarse conforme al régimen vigente del Código Civil y Comercial.</p>
</div>
</div>
</div>
</section>
<section id="fallidos" class="slide level1">
<h1>Fallidos</h1>
<h2 id="inciso-2">Inciso 2°</h2>
<p>El art. 264 menciona:</p>
<ul>
<li>los fallidos;</li>
<li>los concursados; y</li>
<li>los administradores cuya conducta hubiera sido calificada como culpable o fraudulenta.</li>
</ul>
<h3 id="interpretación-de-vítolo">Interpretación de Vítolo</h3>
<p>La derogación del régimen de calificación de conducta por la <strong>Ley 24.522</strong> modificó este supuesto.</p>
<p>Una vez rehabilitado, el fallido puede desempeñarse nuevamente como director, salvo los supuestos especiales previstos por la legislación concursal.</p>
</section>
<section id="condenados-penalmente" class="slide level1">
<h1>Condenados penalmente</h1>
<h2 id="inciso-3">Inciso 3°</h2>
<p>No pueden ser directores quienes hubieran sido condenados por:</p>
<ul>
<li>delitos con pena accesoria de inhabilitación;</li>
<li>delitos contra la propiedad;</li>
<li>cohecho;</li>
<li>emisión de cheques sin fondos;</li>
<li>delitos contra la fe pública;</li>
<li>delitos cometidos en la constitución, funcionamiento o liquidación de sociedades.</li>
</ul>
<p>La incompatibilidad subsiste <strong>hasta diez años después de cumplida la condena</strong>.</p>
</section>
<section id="funcionarios-públicos" class="slide level1">
<h1>Funcionarios públicos</h1>
<h2 id="inciso-4">Inciso 4°</h2>
<p>Los funcionarios de la Administración Pública cuyo desempeño se vincule con el objeto de la sociedad no podrán ser directores de ella hasta <strong>dos años después del cese de sus funciones</strong>.</p>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La finalidad es evitar el aprovechamiento de relaciones o influencias derivadas del ejercicio de la función pública.</p>
</div>
</div>
</div>
</section>
<section id="remoción-del-director-inhabilitado" class="slide level1">
<h1>Remoción del director inhabilitado</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Prohibición o incompatibilidad]

--&gt; B[Convocatoria a asamblea]

--&gt; C[Remoción]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La remoción corresponde exclusivamente a la <strong>asamblea</strong>.</p>
<p>Cuando exista una prohibición del art. 264, el <strong>directorio</strong> o, en su defecto, el <strong>síndico</strong>, deben convocar a asamblea.</p>
<p>La convocatoria también puede originarse en un <strong>pedido fundado de cualquier accionista</strong>.</p>
</section>
<section id="falta-de-convocatoria-o-rechazo-de-la-remoción" class="slide level1">
<h1>Falta de convocatoria o rechazo de la remoción</h1>
<p>Si la asamblea no es convocada dentro del plazo legal, cualquier:</p>
<ul>
<li>accionista;</li>
<li>director; o</li>
<li>síndico,</li>
</ul>
<p>puede promover judicialmente la remoción del director.</p>
<p>Si la asamblea decide mantener al director en el cargo, la vía adecuada será la <strong>acción de impugnación de asamblea</strong> prevista en el <strong>art. 251 LGS</strong>, solicitando como consecuencia de la nulidad la remoción del director afectado por la incompatibilidad.</p>
</section>
<section id="periodicidad-de-las-reuniones" class="slide level1">
<h1>Periodicidad de las reuniones</h1>
<h2 id="artículo-267-lgs">Artículo 267 LGS</h2>
<p>El directorio debe reunirse <strong>por lo menos una vez cada tres meses</strong>.</p>
<p>El estatuto puede exigir una frecuencia mayor.</p>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La reforma introducida por la Ley 22.903 sustituyó la exigencia original de una reunión mensual por el actual plazo trimestral.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>Directorio: Reuniones: convocatoria.</p>
<p>ARTICULO 267. — El directorio se reunirá, por lo menos, una vez cada tres (3) meses, salvo que el estatuto exigiere mayor número de reuniones, sin perjuicio de las que se pudieren celebrar por pedido de cualquier director. La convocatoria será hecha, en éste último caso, por el presidente para reunirse dentro del quinto día de recibido el pedido. En su defecto, podrá convocarla cualquiera de los directores.</p>
<p>La convocatoria deberá indicar los temas a tratar.</p>
</div>
</div>
</div>
</section>
<section id="reuniones-extraordinarias" class="slide level1">
<h1>Reuniones extraordinarias</h1>
<p>La reunión trimestral constituye únicamente el <strong>mínimo legal</strong>.</p>
<p>El directorio debe reunirse además:</p>
<ul>
<li>cuando las necesidades de la administración lo requieran;</li>
<li>a pedido del presidente; o</li>
<li>a solicitud de cualquiera de los directores.</li>
</ul>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La omisión de celebrar las reuniones exigidas por el art. 267 puede comprometer la responsabilidad de los directores.</p>
</div>
</div>
</div>
</section>
<section id="convocatoria" class="slide level1">
<h1>Convocatoria</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Presidente]

--&gt; B[Convoca al directorio]

--&gt; C[Reunión]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Como regla general, la convocatoria corresponde al <strong>presidente del directorio</strong>.</p>
<p>La convocatoria debe indicar:</p>
<ul>
<li>día;</li>
<li>hora;</li>
<li>lugar; y</li>
<li>orden del día.</li>
</ul>
</section>
<section id="solicitud-de-convocatoria" class="slide level1">
<h1>Solicitud de convocatoria</h1>
<p>Cualquier director puede solicitar al presidente la convocatoria del directorio.</p>
<p>El presidente debe convocar la reunión para que se celebre <strong>dentro de los cinco días</strong> de recibido el pedido.</p>
<p>Si no lo hace, o fija la reunión para una fecha posterior sin causa justificada, <strong>cualquier director puede convocarla</strong>.</p>
</section>
<section id="comité-ejecutivo" class="slide level1">
<h1>Comité Ejecutivo</h1>
<h2 id="concepto">Concepto</h2>
<p>El <strong>art. 269 LGS</strong> permite que el directorio delegue la gestión de los negocios ordinarios en un <strong>Comité Ejecutivo</strong> integrado por directores.</p>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La delegación no comprende la función de administrar en sentido pleno, sino únicamente la ejecución de determinadas tareas y decisiones.</p>
<p>El cargo de director continúa siendo <strong>personal e indelegable</strong>.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>ARTICULO 266. — El cargo de director es personal e indelegable.</p>
<p>Los directores no podrán votar por correspondencia, pero en caso de ausencia podrán autorizar a otro director a hacerlo en su nombre, si existiera quórum. Su responsabilidad será la de los directores presentes.</p>
<p>Directorio: Comité ejecutivo.</p>
<p>ARTICULO 269. — El estatuto puede organizar un comité ejecutivo integrados por directores que tengan a su cargo únicamente la gestión de los negocios ordinarios. El directorio vigilará la actuación de ese comité ejecutivo y ejercerá las demás atribuciones legales y estatuarias que le correspondan.</p>
<p>Responsabilidad.</p>
<p>Esta organización no modifica las obligaciones y responsabilidades de los directores.</p>
</div>
</div>
</div>
</section>
<section id="constitución-y-funcionamiento" class="slide level1">
<h1>Constitución y funcionamiento</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Estatuto]

--&gt; B[Directorio]

--&gt; C[Comité Ejecutivo]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Para constituir un Comité Ejecutivo se requiere:</p>
<ul>
<li>que el <strong>estatuto</strong> autorice su creación;</li>
<li>que el <strong>directorio</strong> disponga su integración;</li>
<li>que se determinen las funciones que ejercerá.</li>
</ul>
<p>El Comité Ejecutivo está integrado exclusivamente por <strong>directores titulares</strong>.</p>
</section>
<section id="gerentes" class="slide level1">
<h1>Gerentes</h1>
<h2 id="artículo-269-lgs">Artículo 269 LGS</h2>
<p>El directorio puede designar <strong>gerentes generales o especiales</strong> para ejecutar las decisiones vinculadas con la gestión ordinaria de la sociedad.</p>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>El gerente <strong>no integra el órgano de administración</strong>. Actúa bajo la autoridad y vigilancia del directorio.</p>
</div>
</div>
</div>
</section>
<section id="funciones-y-responsabilidad-del-gerente" class="slide level1">
<h1>Funciones y responsabilidad del gerente</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Directorio]

--&gt; B[Define la política empresarial]

B --&gt; C[Gerente]

C --&gt; D[Ejecuta la gestión diaria]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El gerente:</p>
<ul>
<li>ejecuta las políticas fijadas por el directorio;</li>
<li>puede ser designado y removido por éste;</li>
<li>responde frente a la sociedad y a terceros en la misma extensión que los directores.</li>
</ul>
<p>La designación de gerentes <strong>no excluye la responsabilidad del directorio</strong>.</p>
</section>
<section id="contratación-del-director-con-la-sociedad" class="slide level1">
<h1>Contratación del director con la sociedad</h1>
<h2 id="artículo-271-lgs">Artículo 271 LGS</h2>
<p>Como regla, el director puede contratar con la sociedad cuando:</p>
<ul>
<li>el contrato corresponde a la actividad de la sociedad; y</li>
<li>se celebra en condiciones de mercado.</li>
</ul>
<p>Si falta alguno de esos requisitos, el contrato debe ser aprobado por el directorio, con <strong>abstención de voto</strong> del director interesado.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>Prohibición de contratar con la sociedad.</p>
<p>ARTICULO 271. — El director puede celebrar con la sociedad los contratos que sean de la actividad en que éste opere y siempre que se concierten en las condiciones del mercado.</p>
<p>Los contratos que no reúnan los requisitos del párrafo anterior sólo podrán celebrarse previa aprobación del directorio o conformidad de la sindicatura si no existiese quórum. De estas operaciones deberá darse cuenta a la asamblea.</p>
<p>Si desaprobase los contratos celebrados, los directores o la sindicatura en su caso, serán responsables solidariamente por los daños y perjuicios irrogados a la sociedad.</p>
<p>Los contratos celebrados en violación de lo dispuesto en el párrafo segundo y que no fueren ratificados por la asamblea son nulos, sin perjuicio de la responsabilidad prevista en el párrafo tercero.</p>
</div>
</div>
</div>
</section>
<section id="intervención-de-la-asamblea" class="slide level1">
<h1>Intervención de la asamblea</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Contrato]

--&gt; B[Directorio o sindicatura]

--&gt; C[Asamblea]

C --&gt; D[Aprueba]

C --&gt; E[Desaprueba]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La asamblea puede:</p>
<ul>
<li>guardar silencio;</li>
<li>aprobar la contratación; o</li>
<li>desaprobarla.</li>
</ul>
<p>Si la desaprueba, el contrato es nulo y los responsables deben indemnizar los daños causados a la sociedad.</p>
</section>
<section id="director-con-interés-contrario" class="slide level1">
<h1>Director con interés contrario</h1>
<h2 id="artículo-272-lgs">Artículo 272 LGS</h2>
<p>Cuando un director tenga un interés contrario al interés social debe:</p>
<ul>
<li>comunicar esa circunstancia al directorio y, en su caso, a la sindicatura;</li>
<li>abstenerse de participar en la deliberación;</li>
<li>abstenerse de votar.</li>
</ul>
<p>El incumplimiento genera responsabilidad por los daños ocasionados.</p>
<h2 id="finalidad-de-la-prohibición">Finalidad de la prohibición</h2>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Según Vítolo, la finalidad del art. 272 no es sólo reparar daños una vez producidos, sino <strong>evitar que el director haga prevalecer su interés personal sobre el interés social</strong>.</p>
<p>Por ello, la infracción a la prohibición puede conducir a la invalidez del acto, además de generar responsabilidad.</p>
</div>
</div>
</div>
</section>
<section id="actividades-en-competencia" class="slide level1">
<h1>Actividades en competencia</h1>
<h2 id="artículo-273-lgs">Artículo 273 LGS</h2>
<p>El director <strong>no puede desarrollar, por cuenta propia o de terceros, actividades en competencia con la sociedad</strong>, salvo autorización expresa de la asamblea. :contentReference<span data-index="0">oaicite:0</span></p>
<p>La prohibición constituye una manifestación del <strong>deber de lealtad</strong> previsto en el art. 59 LGS.</p>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Sin autorización previa de la asamblea, el director incurre en responsabilidad.</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>“El artículo 273 de la ley de sociedades comerciales, al proscribir a los administradores la realización de actos en competencia con la sociedad, comprende no sálo las actuaciones habituales efectuadas en competencia, sino también las esporádicas, pues dado el cúmulo de poderes y facultades que ostenta el directorio de una sociedad anónima, es dable exigirles a sus integrantes que mantengan una conducta leal, honesta y prudente durante todo su desempeño. ’Pérez Cotapos, Julio c/Hinz, Pablo y otros” - ENCom. -Sala A - 8/3/1995</p>
</div>
</div>
</div>
</section>
<section id="alcance-de-la-prohibición" class="slide level1">
<h1>Alcance de la prohibición</h1>
<p>La prohibición comprende:</p>
<ul>
<li>actividades habituales o esporádicas;</li>
<li>actuaciones por cuenta propia;</li>
<li>actuaciones por cuenta de terceros.</li>
</ul>
<p>La autorización de la asamblea debe ser:</p>
<ul>
<li><strong>expresa</strong>; y</li>
<li><strong>previa</strong> al inicio de la actividad competitiva.</li>
</ul>
<p>La aprobación posterior de la gestión, la renuncia o una transacción <strong>no extinguen la responsabilidad</strong> derivada de la violación del art. 273 LGS.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>Actividades en competencia.</p>
<p>ARTICULO 273. — El director no puede participar por cuenta propia o de terceros, en actividades en competencia con la sociedad, salvo autorización expresa de la asamblea, so pena de incurrir en la responsabilidad del artículo 59.</p>
</div>
</div>
</div>
</section>
<section id="responsabilidad-de-los-directores" class="slide level1">
<h1>Responsabilidad de los directores</h1>
<h2 id="idea-central-2">Idea central</h2>
<p>Los directores responden por el ejercicio de sus funciones frente a:</p>
<ul>
<li>la sociedad;</li>
<li>los accionistas; y</li>
<li>los terceros.</li>
</ul>
<p>El régimen de los <strong>arts. 274 y siguientes LGS</strong> constituye el sistema general de responsabilidad de los administradores de las sociedades por acciones y se aplica supletoriamente a otros tipos sociales.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>ARTICULO 274. — Los directores responden ilimitada y solidariamente hacia la sociedad, los accionistas y los terceros, por el mal desempeño de su cargo, según el criterio del artículo 59, así como por la violación de la ley, el estatuto o el reglamento y por cualquier otro daño producido por dolo, abuso de facultades o culpa grave.</p>
<p>Sin perjuicio de lo dispuesto en el párrafo anterior, la imputación de responsabilidad se hará atendiendo a la actuación individual cuando se hubieren asignado funciones en forma personal de acuerdo con lo establecido en el estatuto, el reglamento o decisión asamblearia. La decisión de la asamblea y la designación de las personas que han de desempeñar las funciones deben ser inscriptas el Registro Público de Comercio como requisito para la aplicación de lo dispuesto en este párrafo.</p>
<p>Exención de responsabilidad.</p>
<p>Queda exento de responsabilidad el director que participó en la deliberación o resolución o que la conoció, si deja constancia escrita de su protesta y diera noticia al síndico antes que su responsabilidad se denuncie al directorio, al síndico, a la asamblea, a la autoridad competente, o se ejerza la acción judicial.</p>
</div>
</div>
</div>
</section>
<section id="jurisprudencia" class="slide level1">
<h1>Jurisprudencia</h1>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>La responsabilidad del director de una saciedad anónima nace de la sola circunstancia de integrar el Órgano de Gobierno; de allí que es función -aun cuando no se la indique expresamente- de cualquier integrante del Órgano de Administración a de controlar la calidad de la gestión empresaria, dando lugar su incumplimiento a una suerte de culpa “in viglando”.</p>
<p>NO obsta a lo expuesto que el presidente del ente haya absorbido la conducción de la empresa con exclusión de los demás, como se alega en el escrito recursivo. Ello no excusa la responsabilidad del recurrente, cuya conducta omisiva puede ocurrir por ignorancia, imprevisin, negligencia, imperica e imprudencia, entre otros, y cualesquiera de ellas revela su falta de aptitud para el cargo, pero no lo excusa de su responsabilidad. Los administradores de la sociedad que omiten ejercersus funciones en la gestión social no están exentos de la culpa in vigilando”. Se estima aplicable al caso lo dispuesto en el artículo 274 de la ley de sociedades comerciales. linkus, GabrielA.c/Video Producciones Internacionales SA y otros” - CNCom. - Sala B-6/11/1996</p>
</div>
</div>
</div>
</section>
<section id="principio-general" class="slide level1">
<h1>Principio general</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Director]

--&gt; B[Deberes legales]

--&gt; C[Responsabilidad]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La responsabilidad deriva tanto de:</p>
<ul>
<li>la actuación del director;</li>
<li>como de sus omisiones;</li>
<li>y de la falta de vigilancia.</li>
</ul>
<p>La delegación de funciones no elimina la responsabilidad, salvo en los casos previstos por la ley.</p>
</section>
<section id="artículo-59-lgs" class="slide level1">
<h1>Artículo 59 LGS</h1>
<h2 id="parámetro-de-conducta">Parámetro de conducta</h2>
<p>El director debe obrar:</p>
<ul>
<li>con <strong>lealtad</strong>;</li>
<li>con la <strong>diligencia del buen hombre de negocios</strong>.</li>
</ul>
<p>Quien falta a sus obligaciones responde ilimitada y solidariamente por los daños ocasionados.</p>
</section>
<section id="qué-significa-actuar-con-lealtad" class="slide level1">
<h1>¿Qué significa actuar con lealtad?</h1>
<p>Implica privilegiar siempre el <strong>interés social</strong> por sobre:</p>
<ul>
<li>el interés personal;</li>
<li>el interés de otros accionistas;</li>
<li>o el interés de terceros.</li>
</ul>
<p>La actuación desleal genera responsabilidad.</p>
</section>
<section id="buen-hombre-de-negocios" class="slide level1">
<h1>Buen hombre de negocios</h1>
<p>No es el parámetro del “buen padre de familia”.</p>
<p>Exige:</p>
<ul>
<li>conocimiento;</li>
<li>prudencia;</li>
<li>experiencia;</li>
<li>actuación activa;</li>
<li>adecuada valoración de los riesgos empresariales.</li>
</ul>
<p>También responde quien <strong>omite actuar</strong> cuando debía hacerlo.</p>
</section>
<section id="artículo-274-lgs" class="slide level1">
<h1>Artículo 274 LGS</h1>
<p>Los directores responden por:</p>
<ul>
<li>mal desempeño del cargo;</li>
<li>violación de la ley;</li>
<li>violación del estatuto;</li>
<li>violación del reglamento;</li>
<li>dolo;</li>
<li>abuso de facultades;</li>
<li>culpa grave</li>
</ul>
</section>
<section id="supuestos-de-responsabilidad" class="slide level1">
<h1>Supuestos de responsabilidad</h1>
<table class="caption-top">
<thead>
<tr class="header">
<th>Supuesto</th>
<th>Factor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mal desempeño</td>
<td>Violación del estándar del art. 59</td>
</tr>
<tr class="even">
<td>Violación de ley, estatuto o reglamento</td>
<td>Objetivo</td>
</tr>
<tr class="odd">
<td>Dolo</td>
<td>Intención de causar daño</td>
</tr>
<tr class="even">
<td>Abuso de facultades</td>
<td>Exceso deliberado en las atribuciones</td>
</tr>
<tr class="odd">
<td>Culpa grave</td>
<td>Negligencia especialmente intensa</td>
</tr>
</tbody>
</table>
</section>
<section id="ideas-principales-1" class="slide level1">
<h1>Ideas principales</h1>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Los directores responden <strong>individualmente</strong>, aunque la responsabilidad pueda ser solidaria.</p>
<p>El directorio, como órgano, <strong>no responde</strong>: quienes responden son las personas físicas que lo integran.</p>
</div>
</div>
</div>
<p>La responsabilidad cesa cuando el director deja efectivamente el cargo, sin perjuicio de los efectos registrales del art. 60 frente a terceros.</p>
</section>
<section id="acciones-de-responsabilidad" class="slide level1">
<h1>Acciones de responsabilidad</h1>
<p>La LGS prevé dos acciones principales contra los directores:</p>
<ul>
<li><strong>Acción social de responsabilidad</strong> (art. 276).</li>
<li><strong>Acción individual de responsabilidad</strong> (art. 279).</li>
</ul>
<p>En las sociedades que hacen oferta pública existe, además, la acción prevista por la Ley de Mercado de Capitales.</p>
</section>
<section id="acción-social-de-responsabilidad" class="slide level1">
<h1>Acción social de responsabilidad</h1>
<h2 id="artículo-276-lgs">Artículo 276 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Asamblea]

--&gt; B[Promueve la acción]

--&gt; C[Sociedad]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Corresponde a la <strong>sociedad</strong>.</p>
<p>Requiere, como regla, una resolución previa de la asamblea.</p>
<p>La resolución produce la <strong>remoción automática</strong> del director demandado y obliga a su reemplazo.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>Acción social de responsabilidad. Condiciones. Efectos, ejercicios.</p>
<p>ARTICULO 276. — La acción social de responsabilidad contra los directores corresponde a la sociedad, previa resolución de la asamblea de accionistas. Puede ser adoptada aunque no conste en el orden del día, si es consecuencia directa de la resolución de asunto incluido en éste. La resolución producirá la remoción del director o directores afectados y obligará a su reemplazo.</p>
<p>Esta acción también podrá ser ejercida por los accionistas que hubieren efectuado la oposición prevista en el artículo 275.</p>
<p>ARTICULO 277. — Si la acción prevista en el primer párrafo del artículo 276 no fuera iniciada dentro del plazo de tres (3) meses, contados desde la fecha del acuerdo, cualquier accionista puede promoverla, sin perjuicio de la responsabilidad que resulte del incumplimiento de la medida ordenada.</p>
</div>
</div>
</div>
</section>
<section id="acción-social-promovida-por-un-accionista" class="slide level1">
<h1>Acción social promovida por un accionista</h1>
<p>Si la asamblea resolvió iniciar la acción pero el directorio <strong>no la promueve dentro de tres meses</strong>, cualquier accionista puede hacerlo.</p>
<p>No importa cómo haya votado en la asamblea.</p>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>El accionista actúa en defensa del interés social, no de un interés propio.</p>
</div>
</div>
</div>
</section>
<section id="jurisprudencia-1" class="slide level1">
<h1>Jurisprudencia</h1>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Nota</strong></p>
</div>
<div class="callout-content">
<p>La doctrina distingue la acción individual de la acción social de responsabilidad ejercida por el socio individualmente, la que se origina por un daño en el parrimonio del socio, producido a través de la figura societaría. La acción individual se reiere a daños que el accionista reciba personalmente y no a los resultantes de mayor daño sufrido porla sociedad. A los fines de la acción individual, no puede computarse como daño causado a la persunia que la ejeree la parte proporcional que le corresponda en el daño causado al patrimonio de la sociedad. La procedencia de la acción individual de responsabilidad contra los directores y consejeros (arts. 278 y 279, LSC) está condicionada a que el acciomista sufra un perjuicio directo en su palrimonio. ’López González c/Belgrano, Manuel C- - CNCom. - Sala E- 11/3/1991</p>
</div>
</div>
</div>
</section>
<section id="acción-individual-de-responsabilidad" class="slide level1">
<h1>Acción individual de responsabilidad</h1>
<h2 id="artículo-279-lgs">Artículo 279 LGS</h2>
<p>Corresponde al:</p>
<ul>
<li>accionista; o</li>
<li>tercero,</li>
</ul>
<p>que haya sufrido un <strong>daño directo en su propio patrimonio</strong> por la actuación del director.</p>
<p>No requiere decisión previa de la asamblea</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>ARTICULO 279. — Los accionistas y los terceros conservan siempre sus acciones individuales contra los directores.</p>
</div>
</div>
</div>
</section>
<section id="acción-social-vs.-acción-individual" class="slide level1">
<h1>Acción social vs.&nbsp;acción individual</h1>
<table class="caption-top">
<colgroup>
<col style="width: 44%">
<col style="width: 55%">
</colgroup>
<thead>
<tr class="header">
<th>Acción social</th>
<th>Acción individual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Protege el patrimonio social</td>
<td>Protege el patrimonio del accionista o tercero</td>
</tr>
<tr class="even">
<td>El actor es la sociedad (o un accionista en su reemplazo)</td>
<td>El actor es el damnificado</td>
</tr>
<tr class="odd">
<td>Requiere decisión asamblearia</td>
<td>No requiere decisión asamblearia</td>
</tr>
<tr class="even">
<td>La indemnización ingresa a la sociedad</td>
<td>La indemnización corresponde al actor</td>
</tr>
<tr class="odd">
<td>Puede producir la remoción del director</td>
<td>No afecta el funcionamiento del órgano</td>
</tr>
</tbody>
</table>
</section>
<section id="responsabilidad-en-la-quiebra" class="slide level1">
<h1>Responsabilidad en la quiebra</h1>
<p>Cuando la sociedad quiebra:</p>
<ul>
<li>la acción es ejercida por el <strong>síndico</strong>;</li>
<li>requiere la autorización prevista por la LCQ;</li>
<li>si el síndico no actúa, puede hacerlo un acreedor interesado.</li>
</ul>
<p>Las acciones tramitan ante el juez de la quiebra.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>ARTICULO 278. — En caso de quiebra de la sociedad, la acción de responsabilidad puede ser ejercida por el representante del concurso y, en su defecto, se ejercerá por los acreedores individualmente.</p>
</div>
</div>
</div>
</section>
<section class="slide level1">



</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 4.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiado");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiado");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>