<!DOCTYPE html>
<html lang="es"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Prof.&nbsp;Maximiliano Lucas Romei">
  <title>Sociedades Civiles y Comerciales – Clase 14 — SA - Fiscalización</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-0427d8d92a431aa6a6430e53ec02a470.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
  <script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
  <link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Clase 14 — SA - Fiscalización</h1>
  <p class="subtitle">Sociedades Civiles y Comerciales · UBA · Curso intensivo 2026</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Maximiliano Lucas Romei 
</div>
</div>
</div>

</section>
<section id="fiscalización-en-las-sociedades-anónimas" class="slide level1">
<h1>FISCALIZACIÓN EN LAS SOCIEDADES ANÓNIMAS</h1>
</section>
<section id="consejo-de-vigilancia" class="slide level1">
<h1>Consejo de Vigilancia</h1>
<h2 id="artículo-280-lgs">Artículo 280 LGS</h2>
<p>El estatuto puede prever un <strong>Consejo de Vigilancia</strong> integrado por <strong>3 a 15 accionistas</strong>, elegidos por la asamblea.</p>
<p>Características:</p>
<ul>
<li>órgano <strong>optativo</strong>;</li>
<li>miembros reelegibles;</li>
<li>libremente revocables por la asamblea.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Su función principal es <strong>fiscalizar la gestión del directorio</strong>.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>ARTICULO 280. — El estatuto podrá organizar un consejo de vigilancia, integrado por tres a quince accionistas designados por la asamblea conforme a los artículos 262 o 263, reelegibles y libremente revocables. Cuando el estatuto prevea el consejo de vigilancia, los artículos 262 y 263 no se aplicarán en la elección de directores si éstos deben ser elegidos por aquél.</p>
</div>
</div>
</div>
</section>
<section id="finalidad-del-consejo-de-vigilancia" class="slide level1">
<h1>Finalidad del Consejo de Vigilancia</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Asamblea]

--&gt; B[Consejo de Vigilancia]

--&gt; C[Control de la gestión]

C --&gt; D[Directorio]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>A diferencia de la sindicatura, el Consejo de Vigilancia no se limita al control de legalidad.</p>
<p>También ejerce un <strong>control sobre el mérito y la oportunidad de la gestión empresarial</strong>.</p>
</section>
<section id="elección-e-integración" class="slide level1">
<h1>Elección e integración</h1>
<p>Los consejeros deben ser <strong>accionistas</strong>.</p>
<p>La elección corresponde a la asamblea y puede realizarse mediante:</p>
<ul>
<li>lista completa;</li>
<li>clases de acciones (si el estatuto lo prevé);</li>
<li>voto acumulativo.</li>
</ul>
<p>Cuando el Consejo de Vigilancia designa directores, <strong>no se aplica</strong> el voto acumulativo ni la elección por clases.</p>
</section>
<section id="escasa-utilización" class="slide level1">
<h1>Escasa utilización</h1>
<p>Vítolo señala que el instituto ha tenido <strong>muy poca aplicación práctica</strong>.</p>
<p>Entre las razones menciona:</p>
<ul>
<li>posible interferencia con la gestión del directorio;</li>
<li>superposición de funciones con la sindicatura;</li>
<li>posibilidad de bloquear determinadas decisiones del directorio.</li>
</ul>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>En la práctica societaria argentina predomina ampliamente el sistema de <strong>directorio + sindicatura</strong>, siendo excepcional la utilización del Consejo de Vigilancia.</p>
</div>
</div>
</div>
</section>
<section id="incompatibilidades" class="slide level1">
<h1>Incompatibilidades</h1>
<p>No pueden integrar el Consejo de Vigilancia:</p>
<ul>
<li>quienes se encuentren alcanzados por las inhabilidades del art. 264 LGS;</li>
<li>los directores, gerentes y empleados de la sociedad, de su controlante o de sus controladas;</li>
<li>los cónyuges y determinados parientes de los directores y gerentes generales.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>El objetivo es preservar la independencia del órgano de fiscalización.</p>
</div>
</div>
</div>
</section>
<section id="responsabilidad-e-inscripción" class="slide level1">
<h1>Responsabilidad e inscripción</h1>
<p>Los miembros del Consejo de Vigilancia:</p>
<ul>
<li>responden si omiten comunicar la configuración de un supuesto del art. 299 LGS;</li>
<li>pueden ser sancionados si eluden la fiscalización estatal.</li>
</ul>
<p>Su designación y cese deben:</p>
<ul>
<li>publicarse;</li>
<li>inscribirse en el Registro Público conforme al art. 60 LGS.</li>
</ul>
<p>La inscripción es <strong>declarativa</strong>: la función nace con la designación, pero la oponibilidad frente a terceros se produce con la inscripción.</p>
</section>
<section id="límites-de-sus-funciones" class="slide level1">
<h1>Límites de sus funciones</h1>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>El Consejo de Vigilancia <strong>no representa</strong> a la sociedad.</p>
<p>Tampoco administra ni gobierna el ente.</p>
<p>Su actuación se limita al <strong>ámbito interno</strong>, ejerciendo funciones de fiscalización sobre la gestión del directorio.</p>
</div>
</div>
</div>
</section>
<section id="funcionamiento" class="slide level1">
<h1>Funcionamiento</h1>
<p>El Consejo de Vigilancia se organiza como un <strong>órgano colegiado</strong>.</p>
<p>Debe:</p>
<ul>
<li>reunirse, al menos, con la periodicidad prevista por el art. 267 LGS;</li>
<li>respetar un quórum no inferior a la mayoría absoluta de sus integrantes;</li>
<li>dejar constancia de sus deliberaciones en un libro de actas.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>El Consejo designa un presidente, encargado de convocar las reuniones.</p>
</div>
</div>
</div>
</section>
<section id="funciones-de-fiscalización" class="slide level1">
<h1>Funciones de fiscalización</h1>
<h2 id="función-principal">Función principal</h2>
<p>El Consejo de Vigilancia controla:</p>
<ul>
<li>la gestión del directorio;</li>
<li>el cumplimiento de la ley, el estatuto y el reglamento;</li>
<li>la ejecución de las resoluciones asamblearias.</li>
</ul>
<p>Para ello puede:</p>
<ul>
<li>examinar la contabilidad;</li>
<li>inspeccionar los bienes sociales;</li>
<li>realizar arqueos de caja;</li>
<li>requerir informes al directorio.</li>
</ul>
</section>
<section id="funciones-integrativas-de-administración" class="slide level1">
<h1>Funciones integrativas de administración</h1>
<p>Además de controlar, el Consejo puede:</p>
<ul>
<li>convocar a la asamblea en los casos previstos por la ley;</li>
<li>convocar a pedido de accionistas legitimados;</li>
<li>aprobar determinados actos o contratos cuando así lo disponga el estatuto.</li>
</ul>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Cuando el estatuto exige su aprobación para determinados actos, el Consejo puede impedir su realización.</p>
<p>Si el directorio insiste, la decisión corresponde a la asamblea.</p>
</div>
</div>
</div>
</section>
<section id="funciones-integrativas-de-gobierno" class="slide level1">
<h1>Funciones integrativas de gobierno</h1>
<p>El estatuto puede atribuir al Consejo de Vigilancia la <strong>designación de los directores</strong>.</p>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A[Consejo de Vigilancia]

--&gt; B[Designa directores]

C[Asamblea]

--&gt; D[Revoca directores]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La facultad de <strong>remover</strong> a los directores continúa siendo exclusiva de la asamblea.</p>
</section>
<section id="disidencias" class="slide level1">
<h1>Disidencias</h1>
<p>Si la oposición reúne <strong>al menos un tercio</strong> de los integrantes del Consejo:</p>
<ul>
<li>la decisión queda suspendida;</li>
<li>los consejeros disidentes pueden convocar a la asamblea.</li>
</ul>
<p>La asamblea resolverá definitivamente la cuestión planteada.</p>
</section>
<section id="esquema-general" class="slide level1">
<h1>Esquema general</h1>
<table class="caption-top">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Función</th>
<th>Ejemplos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fiscalización</td>
<td>Examinar contabilidad, controlar la gestión, requerir informes</td>
</tr>
<tr class="even">
<td>Integrativa de administración</td>
<td>Convocar asambleas, aprobar determinados actos, formular observaciones</td>
</tr>
<tr class="odd">
<td>Integrativa de gobierno</td>
<td>Designar directores cuando lo autorice el estatuto</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>El Consejo de Vigilancia <strong>no administra ni representa</strong> a la sociedad.</p>
<p>Su función es controlar e intervenir en determinados aspectos de la gestión cuando la ley o el estatuto así lo autorizan.</p>
</div>
</div>
</div>
</section>
<section id="consejo-de-vigilancia-y-sindicatura" class="slide level1">
<h1>Consejo de Vigilancia y Sindicatura</h1>
<h2 id="artículo-283-lgs">Artículo 283 LGS</h2>
<p>Si el estatuto organiza un <strong>Consejo de Vigilancia</strong>, la sociedad <strong>puede prescindir de la sindicatura</strong>.</p>
<p>Pero ello exige:</p>
<ul>
<li>una <strong>auditoría anual</strong>;</li>
<li>que el informe sobre los estados contables sea sometido a la asamblea.</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="consejo-de-vigilancia-1">Consejo de Vigilancia</h3>
<ul>
<li>Integrado por accionistas.</li>
<li>Controla la gestión.</li>
<li>Puede ejercer funciones integrativas de administración y gobierno.</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="sindicatura">Sindicatura</h3>
<ul>
<li>Integrada por abogados y/o contadores.</li>
<li>Control técnico de legalidad.</li>
<li>Fiscalización profesional.</li>
</ul>
</div></div>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>El Consejo de Vigilancia y la Sindicatura <strong>no son órganos incompatibles</strong>.</p>
<p>Pueden coexistir. La supresión de la sindicatura es una <strong>opción</strong> que la ley admite únicamente si se cumplen los requisitos del art. 283 LGS.</p>
</div>
</div>
</div>
</section>
<section id="la-sindicatura" class="slide level1">
<h1>La Sindicatura</h1>
<h2 id="concepto">Concepto</h2>
<p>La sindicatura es el <strong>órgano de fiscalización interna</strong> de la sociedad anónima.</p>
<p>Características:</p>
<ul>
<li>órgano necesario en los casos previstos por la ley;</li>
<li>permanente;</li>
<li>elegido por la asamblea;</li>
<li>con atribuciones mínimas inderogables.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Su finalidad es controlar la actuación del directorio en representación de los accionistas.</p>
</div>
</div>
</div>
</section>
<section id="naturaleza-jurídica" class="slide level1">
<h1>Naturaleza jurídica</h1>
<p>El síndico se vincula con la sociedad mediante un <strong>contrato de servicios</strong>.</p>
<p>Su función presenta características particulares:</p>
<ul>
<li>temporal;</li>
<li>personal;</li>
<li>indelegable;</li>
<li>remunerada;</li>
<li>libremente revocable por la asamblea.</li>
</ul>
</section>
<section id="funciones-de-fiscalización-1" class="slide level1">
<h1>Funciones de fiscalización</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A[Fiscalizar la administración]

--&gt; B[Examinar libros]

A --&gt; C[Controlar la contabilidad]

A --&gt; D[Verificar disponibilidades]

A --&gt; E[Solicitar balances]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La principal misión del síndico consiste en ejercer un <strong>control integral de la administración</strong> de la sociedad.</p>
</section>
<section id="otras-atribuciones" class="slide level1">
<h1>Otras atribuciones</h1>
<p>El síndico debe:</p>
<ul>
<li>asistir a las reuniones del directorio, comité ejecutivo y asamblea (con voz y sin voto);</li>
<li>controlar la garantía de los directores;</li>
<li>informar a la asamblea sobre los estados contables;</li>
<li>suministrar información a los accionistas legitimados.</li>
</ul>
</section>
<section id="facultades-especiales" class="slide level1">
<h1>Facultades especiales</h1>
<p>Además, puede:</p>
<ul>
<li>convocar asambleas cuando corresponda;</li>
<li>solicitar la inclusión de puntos en el orden del día;</li>
<li>vigilar el cumplimiento de la ley, el estatuto y las decisiones asamblearias;</li>
<li>investigar denuncias formuladas por accionistas.</li>
</ul>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>El síndico no administra la sociedad: controla el funcionamiento de sus órganos.</p>
</div>
</div>
</div>
</section>
<section id="esquema-general-1" class="slide level1">
<h1>Esquema general</h1>
<table class="caption-top">
<thead>
<tr class="header">
<th>Función</th>
<th>Ejemplos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fiscalización</td>
<td>Libros, contabilidad, bienes, balances</td>
</tr>
<tr class="even">
<td>Información</td>
<td>Informes a la asamblea y a accionistas</td>
</tr>
<tr class="odd">
<td>Control institucional</td>
<td>Directorio, comité ejecutivo y asamblea</td>
</tr>
<tr class="even">
<td>Actuación subsidiaria</td>
<td>Convocar asambleas, investigar denuncias</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La sindicatura es el órgano técnico de fiscalización previsto por la LGS. Su función principal es controlar la legalidad y regularidad de la administración, sin sustituir al directorio en la gestión.</p>
</div>
</div>
</div>
</section>
<section id="artículo-294-lgs" class="slide level1 scrollable">
<h1>Artículo 294 LGS</h1>
<p>En lugar de memorizar once incisos, puede agruparse en cuatro funciones.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Función</th>
<th>Art. 294</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Fiscalizar</strong></td>
<td>Incs. 1, 2, 4 y 9</td>
</tr>
<tr class="even">
<td><strong>Informar</strong></td>
<td>Incs. 5 y 6</td>
</tr>
<tr class="odd">
<td><strong>Participar</strong></td>
<td>Inc.&nbsp;3</td>
</tr>
<tr class="even">
<td><strong>Actuar subsidiariamente</strong></td>
<td>Incs. 7, 8 y 10</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La mayoría de los deberes del síndico responden a una de estas cuatro finalidades:</p>
<ul>
<li><strong>Controlar</strong> la administración.</li>
<li><strong>Informar</strong> a accionistas y asamblea.</li>
<li><strong>Participar</strong> en el funcionamiento de los órganos sociales.</li>
<li><strong>Intervenir</strong> cuando el directorio incumple sus deberes.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>Atribuciones y deberes.</p>
<p>ARTICULO 294. — Son atribuciones y deberes del síndico, sin perjuicio de los demás que esta ley determina y los que le confiera el estatuto:</p>
<p>1º) Fiscalizar la administración de la sociedad, a cuyo efecto examinará los libros y documentación siempre que lo juzgue conveniente y, por lo menos, una vez cada tres (3) meses.</p>
<p>2º) Verificar en igual forma y periodicidad las disponibilidades y títulos valores, así como las obligaciones y su cumplimiento; igualmente puede solicitar la confección de balances de comprobación;</p>
<p>3º) Asistir con voz, pero sin voto, a las reuniones del directorio, del comité ejecutivo y de la asamblea, a todas las cuales debe ser citado;</p>
<p>4º) Controlar la constitución y subsistencia de la garantía de los directores y recabar las medidas necesarias para corregir cualquier irregularidad;</p>
<p>5º) Presentar a la asamblea ordinaria un informe escrito y fundado sobre la situación económica y financiera de la sociedad, dictaminando sobre la memoria, inventario, balance y estado de resultados;</p>
<p>6º) Suministrar a accionistas que representen no menos del Dos por Ciento (2 %) del capital, en cualquier momento que éstos se lo requieran, información sobre las materias que son de su competencia;</p>
<p>7º) Convocar a asamblea extraordinaria, cuando lo juzgue necesario y a asamblea ordinaria o asambleas especiales, cuando omitiere hacerlo el directorio;</p>
<p>8º) Hacer incluir en el orden del día de la asamblea, los puntos que considere procedentes;</p>
<p>9º) Vigilar que los órganos sociales den debido cumplimiento a la ley, estatuto, reglamento y decisiones asamblearias;</p>
<ol start="10" type="1">
<li><p>Fiscalizar la liquidación de la sociedad;</p></li>
<li><p>Investigar las denuncias que le formulen por escrito accionistas que representen no menos del Dos por Ciento (2 %) del capital, mencionarlas en informe verbal a la asamblea y expresar acerca de ellas las consideraciones y proposiciones que correspondan. Convocará de inmediato a asamblea para que resuelva al respecto, cuando la situación investigada no reciba del directorio el tratamiento que conceptúe adecuado y juzgue necesario actuar con urgencia.</p></li>
</ol>
</div>
</div>
</div>
</section>
<section id="qué-controla-el-síndico" class="slide level1">
<h1>¿Qué controla el síndico?</h1>
<p>Existe una discusión doctrinaria sobre el alcance de la función sindical.</p>
<h2 id="dos-posiciones">Dos posiciones</h2>
<ul>
<li><strong>Control de legalidad</strong>.</li>
<li><strong>Control de mérito o gestión</strong>.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Vítolo sostiene que la sindicatura ejerce únicamente un <strong>control de legalidad</strong>.</p>
</div>
</div>
</div>
</section>
<section id="control-de-legalidad" class="slide level1">
<h1>Control de legalidad</h1>
<p>Según Vítolo, el síndico debe verificar:</p>
<ul>
<li>el cumplimiento de la ley;</li>
<li>el cumplimiento del estatuto;</li>
<li>el cumplimiento del reglamento;</li>
<li>la regularidad de la actuación de los órganos sociales.</li>
</ul>
<p>No le corresponde juzgar:</p>
<ul>
<li>la conveniencia de una decisión empresarial;</li>
<li>la oportunidad de un negocio;</li>
<li>el mérito de la gestión del directorio.</li>
</ul>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Las decisiones empresariales corresponden al directorio.</p>
<p>La sindicatura controla su <strong>legalidad</strong>, no su acierto económico.</p>
</div>
</div>
</div>
</section>
<section id="investigación-de-ejercicios-anteriores" class="slide level1">
<h1>Investigación de ejercicios anteriores</h1>
<h2 id="artículo-295-lgs">Artículo 295 LGS</h2>
<p>El síndico puede:</p>
<ul>
<li>solicitar información;</li>
<li>investigar la administración;</li>
<li>revisar documentación</li>
</ul>
<p><strong>aunque corresponda a ejercicios anteriores a su designación.</strong></p>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La finalidad es impedir que el cambio de síndicos impida descubrir irregularidades cometidas en ejercicios anteriores.</p>
</div>
</div>
</div>
</section>
<section id="designación-de-los-síndicos" class="slide level1">
<h1>Designación de los síndicos</h1>
<p>La designación corresponde a la <strong>asamblea ordinaria</strong>.</p>
<p>En la constitución por acto único:</p>
<ul>
<li>los síndicos deben designarse en el acto constitutivo.</li>
</ul>
<p>El estatuto determina:</p>
<ul>
<li>el número de síndicos;</li>
<li>si la sindicatura será unipersonal o colegiada.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Debe designarse igual número de síndicos suplentes que titulares.</p>
</div>
</div>
</div>
</section>
<section id="sindicatura-colegiada" class="slide level1">
<h1>Sindicatura colegiada</h1>
<p>La regla general es que la sindicatura puede ser:</p>
<ul>
<li>unipersonal; o</li>
<li>colegiada.</li>
</ul>
<p>Sin embargo, debe ser <strong>colegiada e integrada por un número impar</strong> cuando la sociedad se encuentre comprendida en los supuestos del art. 299 LGS, salvo las excepciones previstas por la propia ley.</p>
<p>Ejemplos:</p>
<ul>
<li>oferta pública;</li>
<li>sociedades de economía mixta;</li>
<li>concesionarias de servicios públicos;</li>
<li>sociedades controlantes o controladas;</li>
<li>sociedad anónima unipersonal.</li>
</ul>
</section>
<section id="puede-prescindirse-de-la-sindicatura" class="slide level1">
<h1>¿Puede prescindirse de la sindicatura?</h1>
<h2 id="sí-pero-sólo-en-determinados-casos.">Sí, pero sólo en determinados casos.</h2>
<p>Las sociedades que <strong>no</strong> se encuentren comprendidas en el art. 299 LGS pueden prescindir de la sindicatura si así lo prevé el estatuto.</p>
<p>En ese supuesto:</p>
<ul>
<li>los socios conservan el derecho individual de información y control (art. 55 LGS).</li>
</ul>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Si posteriormente la sociedad queda comprendida en un supuesto que exige sindicatura, deberá designarse aunque el estatuto no sea reformado.</p>
</div>
</div>
</div>
</section>
<section id="quiénes-pueden-ser-síndicos" class="slide level1">
<h1>¿Quiénes pueden ser síndicos?</h1>
<p>Pueden ser designados:</p>
<ul>
<li>abogados con título habilitante;</li>
<li>contadores públicos con título habilitante;</li>
<li>sociedades integradas exclusivamente por abogados y/o contadores, con responsabilidad solidaria.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La sindicatura es un órgano de <strong>fiscalización técnica</strong>.</p>
<p>Por ello la ley exige una calificación profesional específica.</p>
</div>
</div>
</div>
</section>
<section id="ideas-principales" class="slide level1">
<h1>Ideas principales</h1>
<table class="caption-top">
<thead>
<tr class="header">
<th>Tema</th>
<th>Regla</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Designación</td>
<td>Asamblea ordinaria</td>
</tr>
<tr class="even">
<td>Suplentes</td>
<td>Igual número que titulares</td>
</tr>
<tr class="odd">
<td>Sindicatura colegiada</td>
<td>Casos previstos por el art. 299 LGS</td>
</tr>
<tr class="even">
<td>Prescindencia</td>
<td>Sólo cuando la ley lo permite</td>
</tr>
<tr class="odd">
<td>Requisitos</td>
<td>Abogado, contador o sociedad profesional</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>No confundir:</p>
<ul>
<li><strong>Consejo de Vigilancia:</strong> integrado por accionistas.</li>
<li><strong>Sindicatura:</strong> integrada por profesionales.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="inhabilidades-e-incompatibilidades" class="slide level1">
<h1>Inhabilidades e incompatibilidades</h1>
<p>No pueden desempeñarse como síndicos:</p>
<ul>
<li>quienes no estén habilitados para ser directores;</li>
<li>los directores, gerentes y empleados de la sociedad;</li>
<li>los directores, gerentes y empleados de sociedades controlantes o controladas;</li>
<li>determinados familiares de directores y gerentes.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Las incompatibilidades buscan asegurar la <strong>independencia</strong> del órgano de fiscalización.</p>
</div>
</div>
</div>
</section>
<section id="parentesco-e-incompatibilidad" class="slide level1">
<h1>Parentesco e incompatibilidad</h1>
<p>Tampoco pueden ser síndicos:</p>
<ul>
<li>el cónyuge de directores o gerentes;</li>
<li>los parientes por consanguinidad en línea recta;</li>
<li>los colaterales hasta el cuarto grado;</li>
<li>los afines hasta el segundo grado.</li>
</ul>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La fiscalización exige independencia respecto de quienes administran la sociedad.</p>
</div>
</div>
</div>
</section>
<section id="síndico-y-auditor-externo" class="slide level1">
<h1>Síndico y auditor externo</h1>
<p>Existe discusión sobre si una misma persona puede actuar como:</p>
<ul>
<li>síndico societario; y</li>
<li>auditor externo de la sociedad.</li>
</ul>
<p>La posición admitida por las normas profesionales considera ambas funciones compatibles, siempre que:</p>
<ul>
<li>se mantenga la independencia profesional;</li>
<li>no exista relación de dependencia;</li>
<li>los informes se emitan separadamente.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>En las sociedades sujetas a oferta pública, la independencia debe ser objeto de especial evaluación.</p>
</div>
</div>
</div>
</section>
<section id="duración-revocación-y-renuncia" class="slide level1">
<h1>Duración, revocación y renuncia</h1>
<h2 id="duración">Duración</h2>
<ul>
<li>El estatuto fija el plazo.</li>
<li>No puede exceder de <strong>tres ejercicios</strong>.</li>
<li>El síndico permanece hasta ser reemplazado.</li>
<li>Puede ser reelegido indefinidamente.</li>
</ul>
<h2 id="revocación">Revocación</h2>
<ul>
<li>Corresponde a la asamblea ordinaria.</li>
<li>Puede decidirse sin causa.</li>
<li>No procede si se opone el <strong>5 % del capital social</strong>.</li>
</ul>
<h2 id="renuncia">Renuncia</h2>
<ul>
<li>Puede presentarse en cualquier momento.</li>
<li>Debe ser aceptada por la asamblea ordinaria.</li>
<li>El síndico continúa en funciones hasta su aceptación.</li>
</ul>
</section>
<section id="vacancia-y-reemplazo" class="slide level1">
<h1>Vacancia y reemplazo</h1>
<p>Debe elegirse igual número de:</p>
<ul>
<li>síndicos titulares;</li>
<li>síndicos suplentes.</li>
</ul>
<p>Si el titular no puede continuar en funciones, debe ser reemplazado por el suplente correspondiente.</p>
<h2 id="quién-realiza-la-convocatoria">¿Quién realiza la convocatoria?</h2>
<ul>
<li>En la sindicatura unipersonal: el directorio.</li>
<li>En la comisión fiscalizadora: el propio órgano de fiscalización.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>El reemplazo debe producirse con rapidez para asegurar la continuidad del control societario.</p>
</div>
</div>
</div>
</section>
<section id="falta-de-suplente-e-impedimento-sobreviniente" class="slide level1">
<h1>Falta de suplente e impedimento sobreviniente</h1>
<h2 id="si-el-suplente-no-puede-asumir">Si el suplente no puede asumir</h2>
<p>El directorio debe convocar inmediatamente a:</p>
<ul>
<li>asamblea ordinaria; o</li>
<li>asamblea de clase, si el síndico había sido elegido por una clase de acciones.</li>
</ul>
<p>La asamblea designará un nuevo síndico hasta completar el período.</p>
<h2 id="si-aparece-una-incompatibilidad-sobreviniente">Si aparece una incompatibilidad sobreviniente</h2>
<p>El síndico debe:</p>
<ul>
<li>cesar inmediatamente en sus funciones;</li>
<li>comunicarlo al directorio dentro de los diez días.</li>
</ul>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La omisión de informar puede generar responsabilidad conforme al art. 296 LGS.</p>
</div>
</div>
</div>
</section>
<section id="remuneración-de-los-síndicos" class="slide level1">
<h1>Remuneración de los síndicos</h1>
<p>La función sindical es <strong>remunerada</strong>.</p>
<p>La remuneración:</p>
<ul>
<li>debe guardar relación con la tarea profesional;</li>
<li>debe considerar la responsabilidad asumida;</li>
<li>no depende de las ganancias sociales;</li>
<li>no está sujeta a los límites del art. 261 LGS.</li>
</ul>
<p>Si el estatuto no fija el monto, corresponde determinarlo a la asamblea.</p>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>El síndico cumple una función técnica de fiscalización, no una función de gestión.</p>
</div>
</div>
</div>
</section>
<section id="carácter-personal-e-indelegable" class="slide level1">
<h1>Carácter personal e indelegable</h1>
<p>La función sindical es:</p>
<ul>
<li>individual;</li>
<li>personal;</li>
<li>indelegable.</li>
</ul>
<p>El síndico puede valerse de colaboradores para:</p>
<ul>
<li>recopilar antecedentes;</li>
<li>analizar documentación;</li>
<li>realizar tareas auxiliares.</li>
</ul>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La fiscalización sólo puede ser ejercida personalmente por el síndico.</p>
<p>No puede actuar mediante mandatarios, delegados o gestores.</p>
</div>
</div>
</div>
</section>
<section id="responsabilidad-del-síndico" class="slide level1">
<h1>Responsabilidad del síndico</h1>
<h2 id="artículo-296-lgs">Artículo 296 LGS</h2>
<p>Los síndicos responden en forma:</p>
<ul>
<li><strong>ilimitada</strong>;</li>
<li><strong>solidaria</strong>;</li>
</ul>
<p>por el incumplimiento de las obligaciones impuestas por:</p>
<ul>
<li>la ley;</li>
<li>el estatuto;</li>
<li>el reglamento.</li>
</ul>
<p>La responsabilidad comprende el período que se extiende desde la aceptación del cargo hasta el cese efectivo.</p>
</section>
<section id="supuestos-de-responsabilidad" class="slide level1">
<h1>Supuestos de responsabilidad</h1>
<p>Además del incumplimiento de los deberes del art. 294, el síndico puede responder por:</p>
<ul>
<li>nulidad de determinadas decisiones asamblearias;</li>
<li>distribución indebida de dividendos;</li>
<li>inexactitudes vinculadas con emisiones de valores;</li>
<li>otros actos expresamente previstos por la ley.</li>
</ul>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La decisión asamblearia que declara la responsabilidad produce la remoción automática del síndico.</p>
</div>
</div>
</div>
</section>
<section id="responsabilidad-junto-con-los-directores" class="slide level1 scrollable">
<h1>Responsabilidad junto con los directores</h1>
<h2 id="artículo-297-lgs">Artículo 297 LGS</h2>
<p>El síndico responde solidariamente con los directores cuando:</p>
<ol type="1">
<li>los directores causaron un daño mediante una conducta irregular;</li>
<li>el síndico podía controlar esa actuación;</li>
<li>una intervención oportuna habría evitado o reducido el daño.</li>
</ol>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>No responde simplemente porque los directores hayan causado un daño.</p>
<p>Debe existir una omisión relevante en el ejercicio de su función de fiscalización.</p>
</div>
</div>
</div>
</section>
<section id="extinción-de-la-responsabilidad" class="slide level1">
<h1>Extinción de la responsabilidad</h1>
<p>La responsabilidad puede extinguirse por:</p>
<ul>
<li>aprobación de la gestión;</li>
<li>renuncia a promover la acción;</li>
<li>transacción aprobada por la asamblea.</li>
</ul>
<p>Estas decisiones no producen efecto cuando:</p>
<ul>
<li>existe violación de la ley, el estatuto o el reglamento;</li>
<li>se opone al menos el 5 % del capital;</li>
<li>existe liquidación coactiva o concursal.</li>
</ul>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La aprobación de la gestión no funciona como una liberación general frente a incumplimientos legales.</p>
</div>
</div>
</div>
</section>
<section id="fiscalización-estatal" class="slide level1">
<h1>Fiscalización estatal</h1>
<p>La Ley General de Sociedades prevé dos sistemas:</p>
<ul>
<li><strong>Fiscalización estatal permanente</strong> (art. 299 LGS).</li>
<li><strong>Fiscalización estatal limitada</strong> (arts. 300 y 301 LGS).</li>
</ul>
<p>La autoridad de contralor ejerce estas funciones durante la vida de la sociedad, según el grado de control que la ley establezca.</p>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>El fundamento de la fiscalización estatal es la protección del interés público y de los terceros.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>ARTICULO 299. — Las sociedades anónimas, además del control de constitución, quedan sujetas a la fiscalización de la autoridad de contralor de su domicilio, durante su funcionamiento, disolución y liquidación, en cualquiera de los siguientes casos:</p>
<p>1º) Hagan oferta pública de sus acciones o debentures;</p>
<p>2º) Tengan capital social superior a pesos argentinos quinientos (<span class="math inline">\(a 500), monto éste que podrá ser actualizado por el Poder Ejecutivo, cada vez que lo estime necesario; (Nota Infoleg: por art. 1° de la Resolución N° 10/2024 del Ministerio de Justicia, B.O. 8/2/2024, se fija en PESOS DOS MIL MILLONES (\)</span> 2.000.000.000) el monto del capital social a partir del cual las sociedades anónimas quedan sujetas a fiscalización estatal permanente, conforme la previsión del presente inciso.)</p>
<p>3º) Sean de participación estatal, ya sea por la participación del Estado nacional, los estados provinciales, la Ciudad Autónoma de Buenos Aires, los municipios y/o los organismos estatales legalmente autorizados al efecto. (Inciso sustituido por art. 49 del Decreto N° 70/2023 B.O. 21/12/2023.)</p>
<p>4º) Realicen operaciones de capitalización, ahorro o en cualquier forma requieran dinero o valores al público con promesas de prestaciones o beneficios futuros;</p>
<p>5º) Exploten concesiones o servicios públicos;</p>
<p>6º) Se trate de sociedad controlante de o controlada por otra sujeta a fiscalización, conforme a uno de los incisos anteriores.</p>
<p>7°) Se trate de Sociedades Anónimas Unipersonales. (Inciso incorporado por punto 2.26 del Anexo II de la Ley N° 26.994 B.O. 08/10/2014 Suplemento. Vigencia: 1° de agosto de 2015, texto según art. 1° de la Ley N° 27.077 B.O. 19/12/2014)</p>
<p>Fiscalización estatal limitada.</p>
<p>ARTICULO 300. — La fiscalización por la autoridad de contralor de las sociedades anónimas no incluidas en el artículo 299, se limitará al contrato constitutivo, sus reformas y variaciones del capital, a los efectos de los artículos 53 y 167.</p>
<p>Fiscalización estatal limitada: extensión.</p>
<p>ARTICULO 301. — La autoridad de contralor podrá ejercer funciones de vigilancia en las sociedades anónimas no incluidas en el artículo 299, en cualquiera de los siguientes casos:</p>
<p>1º) Cuando lo soliciten accionistas que representen el diez por ciento (10 %) del capital suscripto o lo requiera cualquier síndico. En este caso se limitará a los hechos que funden la presentación;</p>
<p>2º) Cuando lo considere necesario, según resolución fundada, en resguardo del interés público.</p>
</div>
</div>
</div>
</section>
<section id="fiscalización-estatal-permanente" class="slide level1">
<h1>Fiscalización estatal permanente</h1>
<p>Quedan sujetas, entre otras, las sociedades que:</p>
<ul>
<li>hacen oferta pública de acciones o debentures;</li>
<li>superan el capital previsto por el art. 299 inc. 2;</li>
<li>son sociedades de economía mixta;</li>
<li>explotan concesiones o servicios públicos;</li>
<li>realizan operaciones de capitalización o ahorro;</li>
<li>son controlantes o controladas de otras sociedades fiscalizadas;</li>
<li>son sociedades anónimas unipersonales.</li>
</ul>
<p>La autoridad de contralor puede:</p>
<ul>
<li>examinar libros y documentación;</li>
<li>requerir informes;</li>
<li>realizar inspecciones;</li>
<li>recibir denuncias.</li>
</ul>
</section>
<section id="fiscalización-estatal-limitada" class="slide level1">
<h1>Fiscalización estatal limitada</h1>
<p>Las sociedades no comprendidas en el art. 299 están sujetas, en principio, al control de:</p>
<ul>
<li>constitución;</li>
<li>reformas del estatuto;</li>
<li>variaciones de capital;</li>
<li>valuación de aportes en especie.</li>
</ul>
<h2 id="excepciones">Excepciones</h2>
<p>La autoridad de contralor puede ampliar su intervención cuando:</p>
<ul>
<li>lo solicitan accionistas que representen al menos el 10 % del capital o un síndico;</li>
<li>exista un interés público comprometido.</li>
</ul>
</section>
<section id="sanciones-administrativas" class="slide level1">
<h1>Sanciones administrativas</h1>
<p>La autoridad de contralor puede aplicar:</p>
<ul>
<li>apercibimiento;</li>
<li>apercibimiento con publicación;</li>
<li>multas.</li>
</ul>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Las multas impuestas a directores o síndicos deben ser abonadas por ellos personalmente.</p>
<p>La sociedad no puede asumir ese pago.</p>
</div>
</div>
</div>
</section>
<section id="facultades-judiciales" class="slide level1">
<h1>Facultades judiciales</h1>
<p>La autoridad de contralor puede solicitar judicialmente:</p>
<ul>
<li>suspensión de resoluciones sociales;</li>
<li>intervención de la administración;</li>
<li>disolución y liquidación de la sociedad.</li>
</ul>
<p>Estas medidas proceden en los supuestos previstos por los arts. 301 y 303 LGS.</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Importante</strong></p>
</div>
<div class="callout-content">
<p>ARTICULO 301. — La autoridad de contralor podrá ejercer funciones de vigilancia en las sociedades anónimas no incluidas en el artículo 299, en cualquiera de los siguientes casos:</p>
<p>1º) Cuando lo soliciten accionistas que representen el diez por ciento (10 %) del capital suscripto o lo requiera cualquier síndico. En este caso se limitará a los hechos que funden la presentación;</p>
<p>2º) Cuando lo considere necesario, según resolución fundada, en resguardo del interés público.</p>
<p>ARTICULO 303. — La autoridad de contralor está facultada para solicitar al juez del domicilio de la sociedad competente en materia comercial:</p>
<p>1º) La suspensión de las resoluciones de sus órganos si las mismas fueren contrarias a la ley, el estatuto o el reglamento;</p>
<p>2º) La intervención de su administración en los casos del inciso anterior cuando ella haga oferta pública de sus acciones o debentures, o realice operaciones de capitalización, ahorro o en cualquier forma requiera dinero o valores al público con promesa de prestaciones o beneficios futuros y en el supuesto del artículo 301, inciso 2.</p>
<p>La intervención tendrá por objeto remediar las causas que la motivaron y si no fuere ello posible, disolución y liquidación;</p>
<p>3º) La disolución y liquidación en los casos a que se refieren los incisos 3, 4, 5, 8 y 9 del artículo 94 y la liquidación en el caso del inciso 2 de dicho artículo.</p>
</div>
</div>
</div>
</section>
<section id="ideas-principales-1" class="slide level1">
<h1>Ideas principales</h1>
<table class="caption-top">
<colgroup>
<col style="width: 62%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Fiscalización</th>
<th>Alcance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Permanente</td>
<td>Control integral durante la vida de la sociedad</td>
</tr>
<tr class="even">
<td>Limitada</td>
<td>Constitución, reformas y capital, con excepciones</td>
</tr>
<tr class="odd">
<td>Sanciones</td>
<td>Apercibimiento y multas</td>
</tr>
<tr class="even">
<td>Medidas judiciales</td>
<td>Suspensión, intervención, disolución y liquidación</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La intensidad del control estatal depende del interés público comprometido por la actividad o características de la sociedad.</p>
</div>
</div>
</div>
</section>
<section id="responsabilidad-por-ocultación" class="slide level1">
<h1>Responsabilidad por ocultación</h1>
<h2 id="artículo-305-lgs">Artículo 305 LGS</h2>
<p>Los directores y síndicos responden <strong>ilimitada y solidariamente</strong> cuando:</p>
<ul>
<li>conocen que la sociedad se encuentra comprendida en alguno de los supuestos del art. 299 LGS; y</li>
<li>omiten comunicar esa circunstancia a la autoridad de contralor.</li>
</ul>
<p>También pueden ser sancionados cuando:</p>
<ul>
<li>eluden; o</li>
<li>intentan eludir</li>
</ul>
<p>la fiscalización estatal.</p>
<div class="callout callout-warning callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>La finalidad de la norma es impedir que una sociedad evite indebidamente el régimen de fiscalización estatal permanente.</p>
</div>
</div>
</div>
</section>
<section class="slide level1">



</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 4.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiado");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiado");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>