<!DOCTYPE html>
<html lang="es"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Prof.&nbsp;Maximiliano Lucas Romei">
  <title>Sociedades Civiles y Comerciales – Clase 11 — SA - Constitucion y Capital</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-0427d8d92a431aa6a6430e53ec02a470.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Clase 11 — SA - Constitucion y Capital</h1>
  <p class="subtitle">Sociedades Civiles y Comerciales · UBA · Curso intensivo 2026</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Maximiliano Lucas Romei 
</div>
</div>
</div>

</section>
<section id="sociedad-anónima" class="slide level1">
<h1>Sociedad Anónima</h1>
<h2 id="constitución-y-capital-social">Constitución y Capital Social</h2>
<p><strong>Ley General de Sociedades</strong></p>
<p>Arts. 163 a 206</p>
</section>
<section id="la-sociedad-anónima" class="slide level1">
<h1>La sociedad anónima</h1>
<p>La sociedad anónima constituye el tipo societario diseñado para organizar emprendimientos que requieren importantes concentraciones de capital.</p>
<p>A diferencia de las sociedades personalistas, la identidad de los accionistas resulta, en principio, secundaria.</p>
<p>Lo verdaderamente relevante es el capital aportado.</p>
<p>Ello explica las dos notas características que surgen del art. 163 LGS:</p>
<ul>
<li>el capital se encuentra dividido en acciones;</li>
<li>los accionistas limitan su responsabilidad a la integración de las acciones suscriptas.</li>
</ul>
<p>Esta estructura facilita la incorporación de nuevos inversores, la circulación de las acciones y la continuidad de la empresa con independencia de las personas que integran el capital social.</p>
</section>
<section id="la-función-económica-de-la-sociedad-anónima" class="slide level1">
<h1>La función económica de la sociedad anónima</h1>
<p>Históricamente, la sociedad anónima nació como un instrumento destinado a financiar empresas que excedían ampliamente la capacidad económica de un solo comerciante.</p>
<p>Grandes expediciones marítimas, compañías coloniales, bancos, ferrocarriles y posteriormente industrias requirieron la posibilidad de reunir aportes provenientes de numerosos inversores.</p>
<p>Por ello, la sociedad anónima representa el modelo típico de las sociedades de capital.</p>
<p>Como destaca Nissen, constituye el principal instrumento de concentración de capitales para el desarrollo de empresas de gran envergadura. :contentReference<span data-index="0">oaicite:0</span></p>
</section>
<section id="sociedad-de-personas-vs.-sociedad-de-capital" class="slide level1">
<h1>Sociedad de personas vs.&nbsp;sociedad de capital</h1>
<p>En las sociedades de personas predomina la figura del socio.</p>
<p>En la sociedad anónima predomina el capital.</p>
<p>Consecuencias:</p>
<ul>
<li>la participación se representa mediante acciones;</li>
<li>la transmisión de la calidad de accionista es, como principio, libre;</li>
<li>la muerte de un accionista no afecta la continuidad de la sociedad;</li>
<li>la responsabilidad personal del accionista queda limitada al aporte comprometido.</li>
</ul>
<p>Esta desvinculación entre empresa y persona explica el enorme desarrollo económico de este tipo societario.</p>
</section>
<section id="qué-es-el-capital-social" class="slide level1">
<h1>¿Qué es el capital social?</h1>
<p>El capital social es una <strong>cifra jurídica</strong>.</p>
<p>No es una cuenta bancaria.</p>
<p>No es el dinero existente en caja.</p>
<p>No es el patrimonio de la sociedad.</p>
<p>Representa el valor nominal de los aportes comprometidos por los accionistas al constituirse la sociedad o como consecuencia de posteriores aumentos de capital.</p>
<p>Constituye una referencia permanente para determinar:</p>
<ul>
<li>la participación de cada accionista;</li>
<li>sus derechos políticos;</li>
<li>sus derechos económicos;</li>
<li>diversos límites previstos por la Ley General de Sociedades.</li>
</ul>
</section>
<section id="capital-social-y-patrimonio" class="slide level1">
<h1>Capital social y patrimonio</h1>
<p>Uno de los errores más frecuentes consiste en identificar capital con patrimonio.</p>
<p>Son conceptos completamente diferentes.</p>
<p><strong>Capital</strong></p>
<ul>
<li>Es una cifra jurídica.</li>
<li>Permanece invariable hasta que exista una decisión formal de modificarlo.</li>
</ul>
<p><strong>Patrimonio</strong></p>
<ul>
<li>Es una realidad económica.</li>
<li>Cambia todos los días según los resultados de la empresa.</li>
</ul>
<p>El patrimonio puede ser mayor, igual o menor que el capital social.</p>
</section>
<section id="ejemplo" class="slide level1">
<h1>Ejemplo</h1>
<p>Supongamos la siguiente sociedad.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Concepto</th>
<th style="text-align: right;">Importe</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Capital social</td>
<td style="text-align: right;">$100.000.000</td>
</tr>
<tr class="even">
<td style="text-align: right;">Activo</td>
<td style="text-align: right;">$420.000.000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Pasivo</td>
<td style="text-align: right;">$170.000.000</td>
</tr>
</tbody>
</table>
<p>Entonces:</p>
<p><strong>Patrimonio Neto</strong></p>
<p>Activo − Pasivo</p>
<p>= $250.000.000</p>
<p>La sociedad mantiene un capital de <strong>$100.000.000</strong>.</p>
<p>Sin embargo, su patrimonio asciende a <strong>$250.000.000</strong>.</p>
<p>El capital no cambia porque la empresa haya ganado dinero.</p>
<p>Para modificar el capital es necesaria una decisión societaria adoptada conforme a la ley.</p>
</section>
<section id="segundo-ejemplo" class="slide level1">
<h1>Segundo ejemplo</h1>
<p>Ahora imaginemos una crisis.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Concepto</th>
<th style="text-align: right;">Importe</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Capital social</td>
<td style="text-align: right;">$100.000.000</td>
</tr>
<tr class="even">
<td style="text-align: right;">Activo</td>
<td style="text-align: right;">$110.000.000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Pasivo</td>
<td style="text-align: right;">$90.000.000</td>
</tr>
</tbody>
</table>
<p>Patrimonio Neto:</p>
<p>$20.000.000</p>
<p>El capital continúa siendo <strong>$100.000.000</strong>.</p>
<p>Pero el patrimonio cayó a <strong>$20.000.000</strong>.</p>
<p>La pérdida patrimonial no modifica automáticamente el capital social.</p>
<p>Podrá originar posteriormente una reducción de capital o incluso otras consecuencias previstas por la ley, pero el capital permanece inalterado mientras no exista una decisión formal que lo modifique.</p>
</section>
<section id="funciones-del-capital-social" class="slide level1">
<h1>Funciones del capital social</h1>
<p>El capital cumple múltiples funciones.</p>
<h2 id="función-organizativa">Función organizativa</h2>
<p>Determina la participación de cada accionista.</p>
<h2 id="función-política">Función política</h2>
<p>Sirve de base para calcular derechos de voto y de preferencia.</p>
<h2 id="función-financiera">Función financiera</h2>
<p>Proporciona los recursos iniciales para desarrollar el objeto social.</p>
<h2 id="función-de-garantía">Función de garantía</h2>
<p>Constituye una referencia patrimonial destinada a brindar protección a los acreedores sociales, aunque la doctrina moderna relativiza esta función.</p>
</section>
<section id="ejemplo-de-participación-accionaria" class="slide level1">
<h1>Ejemplo de participación accionaria</h1>
<p>Capital social:</p>
<p><strong>$120.000.000</strong></p>
<p>Tres accionistas realizan los siguientes aportes.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Accionista</th>
<th style="text-align: right;">Aporte</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ana</td>
<td style="text-align: right;">$60.000.000</td>
</tr>
<tr class="even">
<td>Bruno</td>
<td style="text-align: right;">$36.000.000</td>
</tr>
<tr class="odd">
<td>Carla</td>
<td style="text-align: right;">$24.000.000</td>
</tr>
</tbody>
</table>
<p>Participación accionaria:</p>
<ul>
<li>Ana → 50 %</li>
<li>Bruno → 30 %</li>
<li>Carla → 20 %</li>
</ul>
<p>Si el estatuto establece una acción = un voto,</p>
<p>la participación política coincidirá exactamente con la participación en el capital.</p>
</section>
<section id="formación-del-capital-social" class="slide level1 scrollable">
<h1>Formación del capital social</h1>
<p>La constitución del capital social no se produce en un único momento.</p>
<p>La Ley General de Sociedades distingue claramente tres etapas:</p>
<ol type="1">
<li><p><strong>Determinación del capital</strong> en el acto constitutivo.</p></li>
<li><p><strong>Suscripción</strong> de las acciones por los accionistas.</p></li>
<li><p><strong>Integración</strong> de los aportes comprometidos.</p></li>
</ol>
<p>Estas tres etapas pueden coincidir en el tiempo o desarrollarse parcialmente de manera sucesiva, según la forma y naturaleza de los aportes.</p>
</section>
<section id="suscripción-e-integración" class="slide level1">
<h1>Suscripción e integración</h1>
<p>La ley diferencia dos conceptos que suelen confundirse.</p>
<h2 id="suscripción">Suscripción</h2>
<p>Es el compromiso jurídico asumido por el accionista.</p>
<p>El socio se obliga a aportar una determinada suma o un determinado bien.</p>
<h2 id="integración">Integración</h2>
<p>Consiste en el cumplimiento efectivo de esa obligación.</p>
<p>Es decir,</p>
<p>el momento en que el aporte ingresa efectivamente al patrimonio de la sociedad.</p>
<p>En consecuencia,</p>
<p>toda acción integrada fue previamente suscripta,</p>
<p>pero no toda acción suscripta se encuentra necesariamente integrada.</p>
</section>
<section id="ejemplo-1" class="slide level1">
<h1>Ejemplo</h1>
<p>La sociedad se constituye con un capital de</p>
<p><strong>$200.000.000</strong></p>
<p>Cuatro accionistas suscriben:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Accionista</th>
<th style="text-align: right;">Capital suscripto</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ana</td>
<td style="text-align: right;">$80.000.000</td>
</tr>
<tr class="even">
<td>Bruno</td>
<td style="text-align: right;">$60.000.000</td>
</tr>
<tr class="odd">
<td>Carla</td>
<td style="text-align: right;">$40.000.000</td>
</tr>
<tr class="even">
<td>Diego</td>
<td style="text-align: right;">$20.000.000</td>
</tr>
</tbody>
</table>
<p>El capital quedó totalmente <strong>suscripto</strong>.</p>
<p>Sin embargo, todavía resta analizar cuánto fue efectivamente integrado.</p>
</section>
<section id="ejemplo-de-integración" class="slide level1">
<h1>Ejemplo de integración</h1>
<p>Supongamos ahora que todos los aportes son en dinero.</p>
<p>La ley exige integrar, como mínimo, el <strong>25 %</strong> al momento de la constitución.</p>
<p>Entonces:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Accionista</th>
<th style="text-align: right;">Suscribió</th>
<th style="text-align: right;">Integró</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ana</td>
<td style="text-align: right;">$80.000.000</td>
<td style="text-align: right;">$20.000.000</td>
</tr>
<tr class="even">
<td>Bruno</td>
<td style="text-align: right;">$60.000.000</td>
<td style="text-align: right;">$15.000.000</td>
</tr>
<tr class="odd">
<td>Carla</td>
<td style="text-align: right;">$40.000.000</td>
<td style="text-align: right;">$10.000.000</td>
</tr>
<tr class="even">
<td>Diego</td>
<td style="text-align: right;">$20.000.000</td>
<td style="text-align: right;">$5.000.000</td>
</tr>
</tbody>
</table>
<p>Capital suscripto:</p>
<p><strong>$200.000.000</strong></p>
<p>Capital efectivamente integrado:</p>
<p><strong>$50.000.000</strong></p>
<p>Saldo pendiente de integración:</p>
<p><strong>$150.000.000</strong></p>
</section>
<section id="qué-ocurre-con-el-saldo-pendiente" class="slide level1">
<h1>¿Qué ocurre con el saldo pendiente?</h1>
<p>La obligación asumida por el accionista continúa vigente.</p>
<p>El saldo deberá integrarse dentro del plazo previsto por la ley y por el estatuto.</p>
<p>Mientras ello no ocurra,</p>
<p>la sociedad conserva un crédito contra ese accionista.</p>
<p>Desde el punto de vista patrimonial:</p>
<ul>
<li><p>el dinero efectivamente aportado integra el activo;</p></li>
<li><p>el saldo pendiente constituye también un derecho de crédito de la sociedad frente al accionista.</p></li>
</ul>
</section>
<section id="ejemplo-contable-simplificado" class="slide level1">
<h1>Ejemplo contable simplificado</h1>
<p>Capital suscripto:</p>
<p><strong>$200.000.000</strong></p>
<p>Integración inicial:</p>
<p><strong>$50.000.000</strong></p>
<p>En el activo encontramos:</p>
<ul>
<li>Caja: $50.000.000</li>
<li>Crédito contra accionistas: $150.000.000</li>
</ul>
<p>En el patrimonio neto:</p>
<p>Capital social:</p>
<p><strong>$200.000.000</strong></p>
<p>Por ello se afirma que el capital quedó íntegramente suscripto, aunque sólo se encuentre parcialmente integrado.</p>
</section>
<section id="los-aportes" class="slide level1">
<h1>Los aportes</h1>
<p>Los accionistas pueden efectuar aportes:</p>
<ul>
<li>en dinero;</li>
<li>en especie.</li>
</ul>
<p>La diferencia tiene importantes consecuencias jurídicas.</p>
<p>Los aportes dinerarios pueden integrarse parcialmente al constituirse la sociedad.</p>
<p>Los aportes en especie, por el contrario, deben encontrarse totalmente integrados desde el inicio.</p>
<p>Ello procura evitar que la sociedad aparezca dotada de bienes cuya efectiva incorporación resulte incierta.</p>
</section>
<section id="ejemplo-de-aporte-dinerario" class="slide level1">
<h1>Ejemplo de aporte dinerario</h1>
<p>Capital social:</p>
<p><strong>$100.000.000</strong></p>
<p>Todos los aportes son en efectivo.</p>
<p>Los accionistas integran únicamente el mínimo legal.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Capital</th>
<th style="text-align: right;">$100.000.000</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Integrado</td>
<td style="text-align: right;">$25.000.000</td>
</tr>
<tr class="even">
<td style="text-align: right;">Pendiente</td>
<td style="text-align: right;">$75.000.000</td>
</tr>
</tbody>
</table>
<p>La sociedad nace válidamente.</p>
<p>Los accionistas continúan obligados a integrar el saldo restante dentro del plazo legal.</p>
</section>
<section id="ejemplo-de-aporte-en-especie" class="slide level1">
<h1>Ejemplo de aporte en especie</h1>
<p>Ana aporta un inmueble valuado en</p>
<p><strong>$80.000.000</strong></p>
<p>Bruno aporta maquinaria valuada en</p>
<p><strong>$20.000.000</strong></p>
<p>Capital social:</p>
<p><strong>$100.000.000</strong></p>
<p>En este supuesto ambos bienes deben encontrarse totalmente incorporados al patrimonio social desde el momento de la constitución.</p>
<p>No sería admisible que Ana entregara solamente una cuarta parte del inmueble y prometiera integrar el resto más adelante.</p>
</section>
<section id="por-qué-la-ley-exige-esa-diferencia" class="slide level1">
<h1>¿Por qué la ley exige esa diferencia?</h1>
<p>La razón es sencilla.</p>
<p>El dinero pendiente puede reclamarse fácilmente al accionista.</p>
<p>En cambio,</p>
<p>los bienes aportados en especie requieren:</p>
<ul>
<li>individualización;</li>
<li>valuación;</li>
<li>tradición o inscripción cuando corresponda.</li>
</ul>
<p>La integración inmediata evita incertidumbres respecto del verdadero patrimonio inicial de la sociedad y protege tanto a los acreedores como a los restantes accionistas.</p>
</section>
<section id="principios-que-gobiernan-el-capital-social" class="slide level1">
<h1>Principios que gobiernan el capital social</h1>
<p>Todo el régimen legal del capital descansa sobre algunos principios fundamentales.</p>
<ul>
<li><p><strong>Determinación</strong>: el capital debe expresarse mediante una cifra precisa.</p></li>
<li><p><strong>Suscripción íntegra</strong>: todo el capital debe encontrarse totalmente suscripto al momento de la constitución.</p></li>
<li><p><strong>Integración mínima</strong>: los aportes dinerarios admiten integración parcial dentro de los límites legales.</p></li>
<li><p><strong>Integración total de los aportes en especie</strong>: deben incorporarse completamente desde el inicio.</p></li>
</ul>
<p>Estos principios permiten comprender todo el régimen posterior relativo a aumentos, reducciones y tutela del capital social.</p>
</section>
<section id="valuación-de-los-aportes" class="slide level1">
<h1>Valuación de los aportes</h1>
<p>Cuando el aporte consiste en dinero, no existe dificultad.</p>
<p>El problema aparece cuando el accionista aporta bienes.</p>
<p>Por ejemplo:</p>
<ul>
<li>un inmueble;</li>
<li>una maquinaria;</li>
<li>un automóvil;</li>
<li>una patente;</li>
<li>una marca;</li>
<li>un establecimiento comercial.</li>
</ul>
<p>En todos estos casos resulta indispensable determinar cuál es el verdadero valor del aporte.</p>
<p>De ello dependerá:</p>
<ul>
<li>el monto del capital social;</li>
<li>la participación del accionista;</li>
<li>la protección de los acreedores.</li>
</ul>
</section>
<section id="por-qué-es-tan-importante-la-valuación" class="slide level1">
<h1>¿Por qué es tan importante la valuación?</h1>
<p>Supongamos que un inmueble vale realmente</p>
<p><strong>$150.000.000</strong></p>
<p>pero los socios acuerdan asignarle un valor de</p>
<p><strong>$300.000.000</strong>.</p>
<p>Formalmente la sociedad parecería tener un capital muy superior al patrimonio efectivamente incorporado.</p>
<p>Los terceros creerán contratar con una sociedad mucho más solvente de lo que realmente es.</p>
<p>Por ello la ley exige mecanismos de valuación que eviten la sobrevaloración de los aportes.</p>
</section>
<section id="ejemplo-2" class="slide level1">
<h1>Ejemplo</h1>
<p>Tres accionistas constituyen una sociedad.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Accionista</th>
<th>Bien aportado</th>
<th style="text-align: right;">Valor real</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ana</td>
<td>Dinero</td>
<td style="text-align: right;">$80.000.000</td>
</tr>
<tr class="even">
<td>Bruno</td>
<td>Inmueble</td>
<td style="text-align: right;">$120.000.000</td>
</tr>
<tr class="odd">
<td>Carla</td>
<td>Maquinaria</td>
<td style="text-align: right;">$100.000.000</td>
</tr>
</tbody>
</table>
<p>Capital social:</p>
<p><strong>$300.000.000</strong></p>
<p>Participación:</p>
<ul>
<li>Ana → 26,67 %</li>
<li>Bruno → 40 %</li>
<li>Carla → 33,33 %</li>
</ul>
<p>La correcta valuación determina tanto la participación societaria como la verdadera garantía patrimonial frente a terceros.</p>
</section>
<section id="qué-sucede-si-el-bien-fue-sobrevaluado" class="slide level1">
<h1>¿Qué sucede si el bien fue sobrevaluado?</h1>
<p>Supongamos ahora que la maquinaria de Carla vale realmente</p>
<p><strong>$40.000.000</strong></p>
<p>pero fue incorporada al capital por</p>
<p><strong>$100.000.000</strong>.</p>
<p>La sociedad aparenta poseer:</p>
<p>Capital:</p>
<p><strong>$300.000.000</strong></p>
<p>Sin embargo, el patrimonio real asciende solamente a</p>
<p><strong>$240.000.000</strong></p>
<p>Existe una diferencia ficticia de</p>
<p><strong>$60.000.000</strong></p>
<p>Esa diferencia perjudica tanto a los restantes accionistas como a los acreedores sociales.</p>
</section>
<section id="ejemplo-comparativo" class="slide level1">
<h1>Ejemplo comparativo</h1>
<h2 id="valuación-correcta">Valuación correcta</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Bien</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dinero</td>
<td style="text-align: right;">$80.000.000</td>
</tr>
<tr class="even">
<td>Inmueble</td>
<td style="text-align: right;">$120.000.000</td>
</tr>
<tr class="odd">
<td>Maquinaria</td>
<td style="text-align: right;">$100.000.000</td>
</tr>
</tbody>
</table>
<p>Capital:</p>
<p><strong>$300.000.000</strong></p>
</section>
<section class="slide level1">

<h2 id="valuación-incorrecta">Valuación incorrecta</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Bien</th>
<th style="text-align: right;">Valor real</th>
<th style="text-align: right;">Valor asignado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dinero</td>
<td style="text-align: right;">$80.000.000</td>
<td style="text-align: right;">$80.000.000</td>
</tr>
<tr class="even">
<td>Inmueble</td>
<td style="text-align: right;">$120.000.000</td>
<td style="text-align: right;">$120.000.000</td>
</tr>
<tr class="odd">
<td>Maquinaria</td>
<td style="text-align: right;">$40.000.000</td>
<td style="text-align: right;">$100.000.000</td>
</tr>
</tbody>
</table>
<p>Capital aparente:</p>
<p><strong>$300.000.000</strong></p>
<p>Capital económico real:</p>
<p><strong>$240.000.000</strong></p>
</section>
<section id="el-principio-de-realidad-del-capital" class="slide level1">
<h1>El principio de realidad del capital</h1>
<p>El capital social debe reflejar aportes efectivamente existentes.</p>
<p>No puede integrarse mediante bienes inexistentes.</p>
<p>Tampoco mediante bienes deliberadamente sobrevaluados.</p>
<p>El objetivo consiste en impedir que la cifra del capital se transforme en una mera apariencia destinada a generar una falsa imagen de solvencia.</p>
<p>Como sostiene Nissen, el beneficio de la responsabilidad limitada presupone necesariamente la existencia de un capital adecuado para el cumplimiento del objeto social. :contentReference<span data-index="0">oaicite:0</span></p>
</section>
<section id="capital-nominal-y-patrimonio-real" class="slide level1">
<h1>Capital nominal y patrimonio real</h1>
<p>Supongamos la siguiente situación.</p>
<p>Capital social:</p>
<p><strong>$500.000.000</strong></p>
<p>Los bienes efectivamente aportados valen:</p>
<p><strong>$320.000.000</strong></p>
<p>La sociedad comienza su actividad con un déficit patrimonial de</p>
<p><strong>$180.000.000</strong></p>
<p>Desde el punto de vista jurídico el capital figura como $500.000.000.</p>
<p>Desde el punto de vista económico, sin embargo, nunca existió ese capital.</p>
<p>Por ello la correcta valuación constituye uno de los mecanismos fundamentales de tutela del capital social.</p>
</section>
<section id="infracapitalización" class="slide level1">
<h1>Infracapitalización</h1>
<p>También puede ocurrir el fenómeno inverso.</p>
<p>Los bienes están correctamente valuados.</p>
<p>Sin embargo,</p>
<p>el capital resulta manifiestamente insuficiente para desarrollar el objeto social.</p>
<h2 id="ejemplo-3">Ejemplo</h2>
<p>Una sociedad pretende construir un edificio de veinte pisos.</p>
<p>Capital social:</p>
<p><strong>$5.000.000</strong></p>
<p>Activo necesario para iniciar la obra:</p>
<p><strong>$2.500.000.000</strong></p>
<p>Aunque el capital haya sido correctamente integrado,</p>
<p>resulta evidente que la sociedad nace insuficientemente capitalizada.</p>
<p>Esta situación ha sido especialmente criticada por Nissen al analizar el régimen del capital mínimo legal. :contentReference<span data-index="1">oaicite:1</span></p>
</section>
<section id="capital-mínimo-y-capital-adecuado" class="slide level1">
<h1>Capital mínimo y capital adecuado</h1>
<p>No debe confundirse el capital mínimo previsto por la ley con el capital realmente necesario para desarrollar el objeto social.</p>
<p>El capital mínimo constituye únicamente un requisito legal para la constitución.</p>
<p>El capital adecuado depende del emprendimiento concreto.</p>
<p>No requiere el mismo capital una sociedad destinada a:</p>
<ul>
<li>prestar servicios de consultoría;</li>
</ul>
<p>que otra destinada a:</p>
<ul>
<li>construir rutas;</li>
<li>explotar una aerolínea;</li>
<li>fabricar automóviles;</li>
<li>operar un banco.</li>
</ul>
<p>La suficiencia del capital debe apreciarse siempre en función del objeto social.</p>
</section>
<section id="ideas-principales" class="slide level1">
<h1>Ideas principales</h1>
<p>La regulación de los aportes persigue un objetivo muy claro.</p>
<p>Garantizar que el capital social refleje una verdadera realidad patrimonial.</p>
<p>Por ello:</p>
<ul>
<li>los aportes deben ser susceptibles de valoración económica;</li>
<li>los aportes en especie requieren una adecuada valuación;</li>
<li>la sobrevaluación perjudica a socios y acreedores;</li>
<li>el capital debe guardar razonable relación con el objeto social.</li>
</ul>
<p>Sobre estos principios se construyen posteriormente las normas relativas a aumentos, reducciones y protección del capital social.</p>
</section>
<section id="variaciones-del-capital-social" class="slide level1">
<h1>Variaciones del capital social</h1>
<p>El capital social no permanece necesariamente inalterado durante toda la vida de la sociedad.</p>
<p>Las necesidades económicas de la empresa pueden exigir:</p>
<ul>
<li>incorporar nuevos recursos;</li>
<li>absorber pérdidas;</li>
<li>reorganizar la estructura patrimonial.</li>
</ul>
<p>Por ello, la Ley General de Sociedades regula dos grandes mecanismos:</p>
<ul>
<li><strong>aumento de capital</strong>;</li>
<li><strong>reducción de capital</strong>.</li>
</ul>
<p>En ambos casos no basta una modificación contable.</p>
<p>La variación requiere una decisión adoptada por el órgano competente y el cumplimiento de las formalidades previstas por la ley.</p>
</section>
<section id="por-qué-aumentar-el-capital" class="slide level1">
<h1>¿Por qué aumentar el capital?</h1>
<p>El aumento del capital puede responder a múltiples finalidades.</p>
<p>Entre las más frecuentes se encuentran:</p>
<ul>
<li>financiar nuevos proyectos;</li>
<li>ampliar la capacidad productiva;</li>
<li>incorporar nuevos accionistas;</li>
<li>fortalecer el patrimonio de la sociedad;</li>
<li>cumplir exigencias regulatorias;</li>
<li>adecuar el capital al crecimiento de la empresa.</li>
</ul>
<p>No todo aumento responde a una situación de crisis.</p>
<p>Muchas veces constituye simplemente una herramienta de expansión empresarial.</p>
</section>
<section id="primer-ejemplo" class="slide level1">
<h1>Primer ejemplo</h1>
<p>Capital actual:</p>
<p><strong>$100.000.000</strong></p>
<p>Dividido en</p>
<p><strong>100.000 acciones</strong></p>
<p>Valor nominal:</p>
<p><strong>$1.000</strong> cada una.</p>
<p>Los accionistas son:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Accionista</th>
<th style="text-align: right;">Acciones</th>
<th style="text-align: right;">Participación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ana</td>
<td style="text-align: right;">60.000</td>
<td style="text-align: right;">60 %</td>
</tr>
<tr class="even">
<td>Bruno</td>
<td style="text-align: right;">25.000</td>
<td style="text-align: right;">25 %</td>
</tr>
<tr class="odd">
<td>Carla</td>
<td style="text-align: right;">15.000</td>
<td style="text-align: right;">15 %</td>
</tr>
</tbody>
</table>
<p>La sociedad necesita construir una nueva planta industrial cuyo costo asciende a</p>
<p><strong>$50.000.000</strong></p>
<p>Por ello decide aumentar el capital.</p>
</section>
<section id="el-aumento-de-capital" class="slide level1">
<h1>El aumento de capital</h1>
<p>La asamblea aprueba emitir</p>
<p><strong>50.000 acciones nuevas</strong></p>
<p>de valor nominal</p>
<p><strong>$1.000</strong></p>
<p>Capital anterior:</p>
<p>$100.000.000</p>
<p>Capital nuevo:</p>
<p>$150.000.000</p>
<p>La pregunta inmediata es:</p>
<p><strong>¿Quién tiene derecho a suscribir esas nuevas acciones?</strong></p>
</section>
<section id="derecho-de-preferencia" class="slide level1">
<h1>Derecho de preferencia</h1>
<p>La ley protege a los accionistas existentes.</p>
<p>Como principio,</p>
<p>cada accionista tiene derecho a suscribir una cantidad de acciones suficiente para mantener su porcentaje de participación.</p>
<p>Este derecho recibe el nombre de</p>
<h2 id="derecho-de-preferencia-1">Derecho de preferencia</h2>
<p>Su finalidad consiste en evitar la dilución involuntaria del accionista.</p>
</section>
<section id="ejemplo-4" class="slide level1">
<h1>Ejemplo</h1>
<p>Se emiten</p>
<p><strong>50.000 acciones nuevas</strong></p>
<p>Ana posee el</p>
<p><strong>60 %</strong></p>
<p>Entonces tiene derecho a suscribir</p>
<p>60 % × 50.000</p>
<p>=</p>
<p><strong>30.000 acciones</strong></p>
<p>Bruno podrá suscribir</p>
<p>12.500 acciones.</p>
<p>Carla</p>
<p>7.500 acciones.</p>
<p>Si todos ejercen el derecho,</p>
<p>sus porcentajes permanecerán exactamente iguales.</p>
</section>
<section id="qué-ocurre-si-un-accionista-no-ejerce-su-derecho" class="slide level1">
<h1>¿Qué ocurre si un accionista no ejerce su derecho?</h1>
<p>Supongamos que Carla decide no suscribir ninguna acción.</p>
<p>Ana suscribe sus 30.000 acciones.</p>
<p>Bruno suscribe sus 12.500.</p>
<p>Quedan vacantes</p>
<p>7.500 acciones.</p>
<p>Esas acciones podrán ser suscriptas conforme al régimen legal y estatutario.</p>
<p>Aquí aparece otro instituto.</p>
</section>
<section id="derecho-de-acrecer" class="slide level1">
<h1>Derecho de acrecer</h1>
<p>El derecho de acrecer permite que quienes ejercieron íntegramente su derecho de preferencia puedan suscribir también las acciones que otros accionistas no adquirieron.</p>
<p>Su finalidad es doble.</p>
<ul>
<li><p>facilitar la colocación total de las acciones emitidas;</p></li>
<li><p>evitar el ingreso innecesario de terceros cuando los propios accionistas desean realizar el aporte.</p></li>
</ul>
</section>
<section id="ejemplo-5" class="slide level1">
<h1>Ejemplo</h1>
<p>Carla renuncia a sus</p>
<p>7.500 acciones.</p>
<p>Ana y Bruno manifiestan interés en adquirirlas.</p>
<p>Si ambas ejercen el derecho de acrecer,</p>
<p>esas acciones se distribuirán entre ellos según el régimen previsto por la ley y el estatuto.</p>
<p>Como consecuencia,</p>
<p>Carla disminuirá su porcentaje de participación.</p>
<p>Ana y Bruno lo incrementarán.</p>
</section>
<section id="dilución-del-accionista" class="slide level1">
<h1>Dilución del accionista</h1>
<p>Supongamos que Carla no suscribe ninguna acción.</p>
<p>El capital pasa a estar representado por</p>
<p>150.000 acciones.</p>
<p>Carla continúa teniendo</p>
<p>15.000 acciones.</p>
<p>Ahora su participación será</p>
<p>15.000 / 150.000</p>
<p>=</p>
<p><strong>10 %</strong></p>
<p>No perdió acciones.</p>
<p>Lo que disminuyó fue el porcentaje que representan dentro del nuevo capital.</p>
<p>Este fenómeno recibe el nombre de</p>
<h2 id="dilución.">Dilución.</h2>
</section>
<section id="comparación" class="slide level1">
<h1>Comparación</h1>
<h2 id="antes-del-aumento">Antes del aumento</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Accionista</th>
<th style="text-align: right;">Participación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ana</td>
<td style="text-align: right;">60 %</td>
</tr>
<tr class="even">
<td>Bruno</td>
<td style="text-align: right;">25 %</td>
</tr>
<tr class="odd">
<td>Carla</td>
<td style="text-align: right;">15 %</td>
</tr>
</tbody>
</table>
</section>
<section class="slide level1">

<h2 id="después-del-aumento-carla-no-suscribe">Después del aumento (Carla no suscribe)</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Accionista</th>
<th style="text-align: right;">Participación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ana</td>
<td style="text-align: right;">60 % (mantiene)</td>
</tr>
<tr class="even">
<td>Bruno</td>
<td style="text-align: right;">30 % (aumenta por acrecer)</td>
</tr>
<tr class="odd">
<td>Carla</td>
<td style="text-align: right;">10 % (se diluye)</td>
</tr>
</tbody>
</table>
<p>La finalidad del derecho de preferencia consiste precisamente en evitar esta pérdida de participación cuando el accionista desea mantenerla.</p>
</section>
<section id="la-prima-de-emisión" class="slide level1">
<h1>La prima de emisión</h1>
<p>Las nuevas acciones no necesariamente deben emitirse por su valor nominal.</p>
<p>Muchas veces la sociedad ha incrementado considerablemente su patrimonio.</p>
<p>Si las nuevas acciones se emitieran únicamente por su valor nominal,</p>
<p>los nuevos accionistas ingresarían beneficiándose del patrimonio acumulado por los antiguos.</p>
<p>Para evitar esa situación,</p>
<p>la ley admite la emisión con</p>
<h2 id="prima-de-emisión.">Prima de emisión.</h2>
</section>
<section id="ejemplo-6" class="slide level1">
<h1>Ejemplo</h1>
<p>Capital social:</p>
<p>$100.000.000</p>
<p>Patrimonio neto:</p>
<p>$400.000.000</p>
<p>Cada acción tiene un valor nominal de</p>
<p>$1.000</p>
<p>Pero su valor económico es mucho mayor.</p>
<p>La sociedad decide emitir nuevas acciones por</p>
<p><strong>$4.000</strong></p>
<p>de los cuales:</p>
<ul>
<li><p>Valor nominal → $1.000</p></li>
<li><p>Prima de emisión → $3.000</p></li>
</ul>
<p>De esta manera,</p>
<p>el nuevo accionista paga el verdadero valor económico de su ingreso a la sociedad.</p>
</section>
<section class="slide level1">

<h2 id="caso-práctico-prima-de-emisión">Caso práctico — Prima de emisión</h2>
<h3 id="caso">Caso</h3>
<p><strong>Innovación Farmacéutica S.A.</strong> fue constituida hace diez años con un capital social de <strong>$100.000.000</strong>, representado por <strong>100.000 acciones ordinarias</strong> de valor nominal <strong>$1.000</strong> cada una.</p>
<p>Gracias a los buenos resultados obtenidos, la sociedad incrementó considerablemente su patrimonio. Al cierre del último ejercicio presenta el siguiente patrimonio neto:</p>
<ul>
<li>Capital social: <strong>$100.000.000</strong></li>
<li>Reserva legal: <strong>$20.000.000</strong></li>
<li>Reservas facultativas: <strong>$180.000.000</strong></li>
<li>Resultados no asignados: <strong>$150.000.000</strong></li>
</ul>
<p><strong>Patrimonio neto total: $450.000.000</strong></p>
<p>La sociedad decide aumentar el capital mediante la emisión de <strong>20.000 nuevas acciones</strong> para incorporar a un inversor estratégico.</p>
<p>El valor nominal de cada acción continúa siendo de <strong>$1.000</strong>.</p>
<p>La asamblea resuelve que el nuevo accionista deberá pagar:</p>
<ul>
<li>Valor nominal: <strong>$1.000</strong> por acción.</li>
<li>Prima de emisión: <strong>$2.500</strong> por acción.</li>
</ul>
<p>En consecuencia, el nuevo inversor desembolsa <strong>$3.500</strong> por cada acción suscripta.</p>
</section>
<section class="slide level1">

<h2 id="solución">Solución</h2>
<p>La decisión de emitir acciones con <strong>prima de emisión</strong> resulta razonable y compatible con el principio de igualdad entre los accionistas.</p>
<p>Si las acciones nuevas se emitieran únicamente a su valor nominal ($1.000), el nuevo inversor ingresaría a una sociedad cuyo patrimonio neto es muy superior al capital social pagando un importe significativamente inferior al valor económico real de su participación.</p>
<p>En efecto, aunque el capital asciende a <strong>$100.000.000</strong>, el patrimonio neto es de <strong>$450.000.000</strong>. Existe, por lo tanto, un importante valor acumulado generado por la actividad de la sociedad y financiado por los accionistas originales.</p>
<p>La <strong>prima de emisión</strong> evita que ese valor preexistente sea transferido gratuitamente al nuevo accionista y preserva la igualdad patrimonial entre los socios antiguos y el nuevo inversor.</p>
<p>En este caso:</p>
<ul>
<li>el <strong>valor nominal</strong> integra el capital social;</li>
<li>la <strong>prima de emisión no integra el capital</strong>, sino que se incorpora al patrimonio neto como una cuenta separada (generalmente dentro de las reservas o del aporte irrevocable según el tratamiento contable aplicable).</li>
</ul>
<p>De esta manera, el nuevo accionista paga un precio más cercano al verdadero valor económico de la sociedad, evitando una dilución injustificada de la participación patrimonial de los accionistas preexistentes.</p>
</section>
<section id="ideas-principales-1" class="slide level1">
<h1>Ideas principales</h1>
<p>El aumento del capital constituye una herramienta esencial para financiar el crecimiento de la empresa.</p>
<p>Durante ese procedimiento la ley procura equilibrar distintos intereses.</p>
<ul>
<li><p>facilitar el ingreso de nuevos recursos;</p></li>
<li><p>proteger la posición de los accionistas existentes;</p></li>
<li><p>evitar diluciones indebidas;</p></li>
<li><p>preservar la igualdad entre accionistas;</p></li>
<li><p>impedir el enriquecimiento injustificado de quienes ingresan posteriormente al capital social.</p></li>
</ul>
<p>En la próxima sección analizaremos el fenómeno inverso:</p>
<p><strong>la reducción del capital social</strong>, sus clases y la tutela de los acreedores.</p>
</section>
<section id="la-reducción-del-capital-social" class="slide level1">
<h1>La reducción del capital social</h1>
<p>Así como la sociedad puede necesitar aumentar su capital,</p>
<p>también puede resultar conveniente o necesario reducirlo.</p>
<p>La reducción no implica necesariamente una crisis.</p>
<p>Puede obedecer a distintas finalidades.</p>
<p>Entre ellas:</p>
<ul>
<li>absorber pérdidas acumuladas;</li>
<li>devolver aportes a los accionistas;</li>
<li>adecuar el capital a las necesidades reales de la empresa;</li>
<li>reorganizar la estructura patrimonial.</li>
</ul>
<p>No toda reducción significa que la sociedad esté en dificultades económicas.</p>
</section>
<section id="clases-de-reducción" class="slide level1">
<h1>Clases de reducción</h1>
<p>La doctrina distingue dos grandes categorías.</p>
<h2 id="reducción-voluntaria">Reducción voluntaria</h2>
<p>La sociedad decide disminuir su capital por razones de conveniencia empresarial.</p>
<p>Generalmente implica devolución de aportes o liberación de integraciones pendientes.</p>
</section>
<section class="slide level1">

<h2 id="reducción-obligatoria">Reducción obligatoria</h2>
<p>La ley impone la necesidad de adecuar el capital cuando las pérdidas han disminuido significativamente el patrimonio social.</p>
<p>En este supuesto la reducción procura sincerar la verdadera situación patrimonial de la sociedad.</p>
</section>
<section id="ejemplo-de-reducción-por-pérdidas" class="slide level1">
<h1>Ejemplo de reducción por pérdidas</h1>
<p>Supongamos la siguiente situación.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Concepto</th>
<th style="text-align: right;">Importe</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Capital social</td>
<td style="text-align: right;">$300.000.000</td>
</tr>
<tr class="even">
<td>Activo</td>
<td style="text-align: right;">$180.000.000</td>
</tr>
<tr class="odd">
<td>Pasivo</td>
<td style="text-align: right;">$140.000.000</td>
</tr>
</tbody>
</table>
<p>Patrimonio Neto:</p>
<p><strong>$40.000.000</strong></p>
<p>Sin embargo,</p>
<p>el capital continúa siendo</p>
<p><strong>$300.000.000</strong></p>
<p>Existe una enorme diferencia entre la realidad económica y la cifra jurídica del capital.</p>
</section>
<section id="qué-busca-la-reducción" class="slide level1">
<h1>¿Qué busca la reducción?</h1>
<p>La sociedad decide reducir el capital.</p>
<p>Capital anterior:</p>
<p><strong>$300.000.000</strong></p>
<p>Nuevo capital:</p>
<p><strong>$40.000.000</strong></p>
<p>Obsérvese que no ingresó ni salió dinero.</p>
<p>Tampoco cambiaron los bienes de la empresa.</p>
<p>Lo único que cambió fue la cifra jurídica del capital,</p>
<p>que ahora refleja adecuadamente el patrimonio existente.</p>
</section>
<section id="antes-y-después" class="slide level1">
<h1>Antes y después</h1>
<h2 id="antes">Antes</h2>
<p>Activo</p>
<p>$180.000.000</p>
<p>Pasivo</p>
<p>$140.000.000</p>
<p>Patrimonio Neto</p>
<p>$40.000.000</p>
<p>Capital</p>
<p>$300.000.000</p>
</section>
<section class="slide level1">

<h2 id="después">Después</h2>
<p>Activo</p>
<p>$180.000.000</p>
<p>Pasivo</p>
<p>$140.000.000</p>
<p>Patrimonio Neto</p>
<p>$40.000.000</p>
<p>Capital</p>
<p>$40.000.000</p>
<p>La reducción no produjo ninguna modificación económica.</p>
<p>Simplemente eliminó un capital ficticio.</p>
</section>
<section id="reducción-con-devolución-de-aportes" class="slide level1">
<h1>Reducción con devolución de aportes</h1>
<p>Existe otro supuesto.</p>
<p>La sociedad posee un patrimonio ampliamente superior al capital y considera excesivos los recursos aportados.</p>
<p>Ejemplo.</p>
<p>Capital:</p>
<p>$200.000.000</p>
<p>Patrimonio Neto:</p>
<p>$700.000.000</p>
<p>La empresa no necesita mantener un capital tan elevado.</p>
<p>La asamblea decide reducirlo a</p>
<p>$150.000.000</p>
<p>y devolver</p>
<p>$50.000.000</p>
<p>a los accionistas.</p>
<p>Aquí sí existe una efectiva salida de bienes del patrimonio social.</p>
</section>
<section id="ejemplo-7" class="slide level1">
<h1>Ejemplo</h1>
<p>Ana posee el 60 % del capital.</p>
<p>Bruno el 40 %.</p>
<p>La sociedad devuelve</p>
<p>$50.000.000</p>
<p>Entonces:</p>
<p>Ana recibe</p>
<p>$30.000.000</p>
<p>Bruno recibe</p>
<p>$20.000.000</p>
<p>Ambos conservan exactamente el mismo porcentaje de participación.</p>
<p>Lo único que disminuye es el monto del capital.</p>
</section>
<section id="por-qué-la-ley-protege-a-los-acreedores" class="slide level1">
<h1>¿Por qué la ley protege a los acreedores?</h1>
<p>Cuando la reducción implica devolución de aportes,</p>
<p>el patrimonio de la sociedad disminuye.</p>
<p>En consecuencia,</p>
<p>los acreedores contarán con menos bienes para cobrar sus créditos.</p>
<p>Por ello la ley establece un procedimiento especial destinado a permitir que los acreedores formulen oposición cuando la reducción pueda afectar sus derechos.</p>
<p>La tutela deja de centrarse en los accionistas y pasa a proteger principalmente a los terceros.</p>
</section>
<section id="ejemplo-8" class="slide level1">
<h1>Ejemplo</h1>
<p>Antes de la reducción.</p>
<p>Activo:</p>
<p>$500.000.000</p>
<p>Pasivo:</p>
<p>$150.000.000</p>
<p>Capital:</p>
<p>$250.000.000</p>
<p>La sociedad pretende devolver</p>
<p>$180.000.000</p>
<p>a los accionistas.</p>
<p>Después de esa devolución,</p>
<p>el patrimonio disponible para responder frente a los acreedores disminuiría considerablemente.</p>
<p>Precisamente por ello la ley les concede mecanismos de protección.</p>
</section>
<section id="aumento-y-reducción-comparados" class="slide level1">
<h1>Aumento y reducción comparados</h1>
<table class="caption-top">
<colgroup>
<col style="width: 45%">
<col style="width: 55%">
</colgroup>
<thead>
<tr class="header">
<th>Aumento</th>
<th>Reducción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ingresan recursos</td>
<td>Pueden salir recursos</td>
</tr>
<tr class="even">
<td>Crece el capital</td>
<td>Disminuye el capital</td>
</tr>
<tr class="odd">
<td>Puede incorporarse nuevos accionistas</td>
<td>No necesariamente cambia la composición accionaria</td>
</tr>
<tr class="even">
<td>Puede generar dilución</td>
<td>Generalmente mantiene los porcentajes</td>
</tr>
<tr class="odd">
<td>Protege principalmente a los accionistas mediante el derecho de preferencia</td>
<td>Protege principalmente a los acreedores mediante el derecho de oposición</td>
</tr>
</tbody>
</table>
</section>
<section id="caso-integrador" class="slide level1">
<h1>Caso integrador</h1>
<p>La sociedad “Construcciones del Sur S.A.” presenta la siguiente situación.</p>
<p>Capital social:</p>
<p><strong>$100.000.000</strong></p>
<p>Patrimonio Neto:</p>
<p><strong>$450.000.000</strong></p>
<p>Cinco años después decide ampliar su actividad.</p>
<p>La asamblea aumenta el capital a</p>
<p><strong>$180.000.000</strong></p>
<p>Dos años más tarde vende una unidad de negocios y considera excesivo el capital comprometido.</p>
<p>Decide reducirlo a</p>
<p><strong>$140.000.000</strong></p>
<p>Preguntas para analizar.</p>
<ul>
<li><p>¿Por qué fue conveniente aumentar el capital inicialmente?</p></li>
<li><p>¿Por qué la posterior reducción no implica necesariamente una crisis?</p></li>
<li><p>¿Qué intereses tutela la ley en cada uno de esos procedimientos?</p></li>
</ul>
</section>
<section id="ideas-principales-2" class="slide level1">
<h1>Ideas principales</h1>
<p>Las variaciones del capital social responden a necesidades cambiantes de la empresa.</p>
<p>El aumento procura incorporar nuevos recursos o fortalecer el patrimonio.</p>
<p>La reducción busca adecuar la cifra jurídica del capital a la realidad económica o devolver recursos que ya no resultan necesarios.</p>
<p>En ambos casos la Ley General de Sociedades procura equilibrar tres intereses fundamentales:</p>
<ul>
<li>el interés de la sociedad;</li>
<li>los derechos de los accionistas;</li>
<li>la protección de los acreedores sociales.</li>
</ul>
<p>Con estos institutos queda completo el régimen básico del capital social en la sociedad anónima.</p>
</section>
<section id="capital-patrimonio-y-valor-de-las-acciones" class="slide level1">
<h1>Capital, patrimonio y valor de las acciones</h1>
<p>Hasta ahora vimos que el capital y el patrimonio son conceptos distintos.</p>
<p>Sin embargo, esa diferencia tiene una consecuencia práctica inmediata.</p>
<p>El valor de una acción no necesariamente coincide con su valor nominal.</p>
<p>Para comprender esta cuestión es necesario distinguir distintos conceptos de valor.</p>
</section>
<section id="un-mismo-ejemplo" class="slide level1">
<h1>Un mismo ejemplo</h1>
<p>Supongamos la siguiente sociedad.</p>
<p>Capital social:</p>
<p><strong>$100.000.000</strong></p>
<p>Representado por</p>
<p><strong>100.000 acciones</strong></p>
<p>Valor nominal:</p>
<p><strong>$1.000</strong></p>
<p>Al cierre del ejercicio presenta el siguiente balance.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Concepto</th>
<th style="text-align: right;">Importe</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Activo</td>
<td style="text-align: right;">$600.000.000</td>
</tr>
<tr class="even">
<td>Pasivo</td>
<td style="text-align: right;">$250.000.000</td>
</tr>
</tbody>
</table>
<p>Patrimonio Neto:</p>
<p><strong>$350.000.000</strong></p>
</section>
<section id="primer-dato" class="slide level1">
<h1>Primer dato</h1>
<p>Cada acción tiene un</p>
<h2 id="valor-nominal">Valor nominal</h2>
<p>de</p>
<p><strong>$1.000</strong></p>
<p>Ese importe surge exclusivamente del capital social.</p>
<p>No depende del patrimonio.</p>
<p>No depende de las ganancias.</p>
<p>No depende del mercado.</p>
<p>Simplemente resulta de dividir el capital por la cantidad de acciones emitidas.</p>
</section>
<section id="segundo-dato" class="slide level1">
<h1>Segundo dato</h1>
<p>Ahora calculemos el</p>
<h2 id="valor-patrimonial-proporcional-vpp">Valor patrimonial proporcional (VPP)</h2>
<p>Patrimonio Neto</p>
<p>$350.000.000</p>
<p>Cantidad de acciones</p>
<p>100.000</p>
<p>Entonces:</p>
<p>VPP</p>
<p>=</p>
<p>$350.000.000 ÷ 100.000</p>
<p>=</p>
<p><strong>$3.500 por acción</strong></p>
</section>
<section id="comparación-1" class="slide level1">
<h1>Comparación</h1>
<p>Cada acción presenta ahora dos valores diferentes.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Concepto</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Valor nominal</td>
<td style="text-align: right;">$1.000</td>
</tr>
<tr class="even">
<td>Valor patrimonial proporcional</td>
<td style="text-align: right;">$3.500</td>
</tr>
</tbody>
</table>
<p>Las acciones siguen teniendo un valor nominal de $1.000.</p>
<p>Pero cada una representa una porción del patrimonio cuyo valor asciende a $3.500.</p>
</section>
<section id="por-qué-ocurre-esta-diferencia" class="slide level1">
<h1>¿Por qué ocurre esta diferencia?</h1>
<p>Porque durante la vida de la sociedad pueden acumularse:</p>
<ul>
<li>utilidades;</li>
<li>reservas;</li>
<li>revalorización de activos;</li>
<li>resultados no distribuidos.</li>
</ul>
<p>Todo ello incrementa el patrimonio.</p>
<p>Sin modificar el capital social.</p>
<p>Por eso el valor económico de la acción suele separarse de su valor nominal.</p>
</section>
<section id="tercer-dato" class="slide level1">
<h1>Tercer dato</h1>
<p>Supongamos ahora que la sociedad cotiza en Bolsa.</p>
<p>Las acciones se negocian a</p>
<p><strong>$4.800</strong></p>
<p>Ese importe constituye el</p>
<h2 id="valor-de-mercado">Valor de mercado</h2>
<p>Depende de factores completamente distintos.</p>
<ul>
<li>expectativas futuras;</li>
<li>rentabilidad;</li>
<li>riesgo;</li>
<li>oferta y demanda.</li>
</ul>
<p>Puede ser superior o inferior al valor patrimonial.</p>
</section>
<section id="cuatro-valores-distintos" class="slide level1">
<h1>Cuatro valores distintos</h1>
<p>La misma acción puede presentar simultáneamente.</p>
<table class="caption-top">
<colgroup>
<col style="width: 60%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Tipo de valor</th>
<th style="text-align: right;">Importe</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Valor nominal</td>
<td style="text-align: right;">$1.000</td>
</tr>
<tr class="even">
<td>Valor patrimonial proporcional</td>
<td style="text-align: right;">$3.500</td>
</tr>
<tr class="odd">
<td>Valor de mercado</td>
<td style="text-align: right;">$4.800</td>
</tr>
<tr class="even">
<td>Valor de liquidación</td>
<td style="text-align: right;">Dependerá del resultado final de la liquidación</td>
</tr>
</tbody>
</table>
<p>No existe contradicción.</p>
<p>Cada uno responde a finalidades completamente distintas.</p>
</section>
<section id="ejemplo-de-liquidación" class="slide level1">
<h1>Ejemplo de liquidación</h1>
<p>La sociedad decide disolverse.</p>
<p>Durante la liquidación logra vender todos sus bienes.</p>
<p>Activo realizado:</p>
<p>$620.000.000</p>
<p>Pasivo cancelado:</p>
<p>$240.000.000</p>
<p>Saldo final para distribuir:</p>
<p><strong>$380.000.000</strong></p>
<p>Cada acción recibirá</p>
<p>$380.000.000 ÷ 100.000</p>
<p>=</p>
<p><strong>$3.800</strong></p>
<p>Ese importe constituye el valor efectivo obtenido en la liquidación.</p>
</section>
<section id="cuál-de-estos-valores-utiliza-la-ley" class="slide level1">
<h1>¿Cuál de estos valores utiliza la ley?</h1>
<p>Depende del instituto.</p>
<p>Por ejemplo:</p>
<ul>
<li><p>el capital social utiliza el valor nominal;</p></li>
<li><p>la valuación de participaciones para determinados supuestos puede apoyarse en el patrimonio;</p></li>
<li><p>la cotización bursátil responde al mercado;</p></li>
<li><p>la liquidación dependerá del producido final de realización de los bienes.</p></li>
</ul>
<p>No existe un único valor correcto.</p>
<p>Cada instituto jurídico utiliza el que mejor responde a su finalidad.</p>
</section>
<section id="caso-integrador-1" class="slide level1">
<h1>Caso integrador</h1>
<p>Ana posee</p>
<p>10.000 acciones.</p>
<p>Capital:</p>
<p>$100.000.000</p>
<p>Patrimonio Neto:</p>
<p>$350.000.000</p>
<p>Cotización bursátil:</p>
<p>$4.800</p>
<p>Entonces:</p>
<p>Participación política:</p>
<p><strong>10 %</strong></p>
<p>Valor nominal de su participación:</p>
<p>$10.000.000</p>
<p>Valor patrimonial proporcional:</p>
<p>$35.000.000</p>
<p>Valor bursátil aproximado:</p>
<p>$48.000.000</p>
<p>La misma participación societaria admite distintas valuaciones según el criterio utilizado.</p>
</section>
<section id="ideas-principales-3" class="slide level1">
<h1>Ideas principales</h1>
<p>Al estudiar las acciones es indispensable distinguir cuatro conceptos.</p>
<ul>
<li>Capital social.</li>
<li>Valor nominal.</li>
<li>Patrimonio neto.</li>
<li>Valor económico de la participación.</li>
</ul>
<p>Confundir estos conceptos suele conducir a errores en temas tan diversos como:</p>
<ul>
<li>derecho de receso;</li>
<li>prima de emisión;</li>
<li>valuación de acciones;</li>
<li>exclusión de socios;</li>
<li>reorganizaciones societarias;</li>
<li>liquidación de la sociedad.</li>
</ul>
<p>Comprender estas diferencias permite interpretar correctamente todo el régimen patrimonial de la sociedad anónima.</p>
</section>
<section id="constitución-de-la-sociedad-anónima" class="slide level1">
<h1>Constitución de la sociedad anónima</h1>
<p>La sociedad anónima es una sociedad <strong>formal</strong>.</p>
<p>No basta el acuerdo entre los futuros accionistas.</p>
<p>Su constitución requiere el cumplimiento de una serie de requisitos legales destinados a proteger:</p>
<ul>
<li>a los propios accionistas;</li>
<li>a los futuros acreedores;</li>
<li>al tráfico comercial.</li>
</ul>
<p>La omisión de alguno de estos requisitos puede impedir la inscripción de la sociedad o generar responsabilidad para quienes actúan durante el período de formación.</p>
</section>
<section id="forma-instrumental" class="slide level1">
<h1>Forma instrumental</h1>
<p>La constitución debe instrumentarse mediante escritura pública.</p>
<p>En ella deben constar, entre otras cuestiones:</p>
<ul>
<li>identidad de los accionistas;</li>
<li>denominación social;</li>
<li>domicilio;</li>
<li>objeto;</li>
<li>duración;</li>
<li>capital social;</li>
<li>clases de acciones;</li>
<li>integración de los aportes;</li>
<li>designación de las autoridades.</li>
</ul>
<p>La escritura constituye el instrumento básico de organización de la sociedad.</p>
</section>
<section id="el-estatuto" class="slide level1">
<h1>El estatuto</h1>
<p>El estatuto funciona como la “constitución” de la sociedad.</p>
<p>Regula las principales reglas de funcionamiento.</p>
<p>Entre otras materias establece:</p>
<ul>
<li>el objeto social;</li>
<li>el capital;</li>
<li>las clases de acciones;</li>
<li>el funcionamiento de los órganos;</li>
<li>las mayorías;</li>
<li>la distribución de utilidades;</li>
<li>las restricciones estatutarias permitidas por la ley.</li>
</ul>
<p>Una vez inscripto, resulta obligatorio para la sociedad, los accionistas y los órganos sociales.</p>
</section>
<section id="ejemplo-9" class="slide level1">
<h1>Ejemplo</h1>
<p>Tres emprendedores constituyen</p>
<p><strong>Tecnología Aplicada S.A.</strong></p>
<p>El estatuto establece:</p>
<ul>
<li><p>Capital: $120.000.000</p></li>
<li><p>120.000 acciones ordinarias de $1.000</p></li>
<li><p>Directorio integrado por tres miembros</p></li>
<li><p>Duración: 99 años</p></li>
<li><p>Objeto: desarrollo de software para entidades financieras</p></li>
</ul>
<p>A partir de ese estatuto se organizará toda la vida societaria.</p>
</section>
<section id="constitución-por-acto-único" class="slide level1">
<h1>Constitución por acto único</h1>
<p>Es el sistema utilizado prácticamente en la totalidad de las sociedades anónimas.</p>
<p>Todos los accionistas:</p>
<ul>
<li>celebran simultáneamente el acto constitutivo;</li>
<li>suscriben la totalidad del capital;</li>
<li>designan las autoridades;</li>
<li>aprueban el estatuto.</li>
</ul>
<p>Luego se solicita la inscripción registral.</p>
<p>La sociedad comienza su existencia regular una vez producida esa inscripción.</p>
</section>
<section id="constitución-sucesiva" class="slide level1">
<h1>Constitución sucesiva</h1>
<p>La Ley General de Sociedades también contempla la constitución mediante suscripción pública.</p>
<p>En este sistema:</p>
<ul>
<li>primero se promueve la constitución;</li>
<li>luego se invita al público a suscribir acciones;</li>
<li>finalmente se celebra la asamblea constitutiva.</li>
</ul>
<p>Su utilización práctica es actualmente excepcional.</p>
<p>La enorme mayoría de las sociedades anónimas argentinas se constituyen por acto único.</p>
</section>
<section id="la-sociedad-en-formación" class="slide level1">
<h1>La sociedad en formación</h1>
<p>Entre la firma del acto constitutivo y la inscripción registral existe un período intermedio.</p>
<p>Durante ese lapso la sociedad aún no se encuentra regularmente constituida.</p>
<p>Sin embargo, muchas veces resulta necesario comenzar ciertas actividades.</p>
<p>Por ejemplo:</p>
<ul>
<li>alquilar un inmueble;</li>
<li>contratar empleados;</li>
<li>adquirir equipamiento;</li>
<li>abrir cuentas bancarias.</li>
</ul>
<p>La ley regula específicamente este período para proteger tanto a terceros como a los futuros accionistas.</p>
</section>
<section id="ejemplo-10" class="slide level1">
<h1>Ejemplo</h1>
<p>Los socios firman la escritura el</p>
<p><strong>1 de marzo.</strong></p>
<p>La inscripción se obtiene el</p>
<p><strong>15 de abril.</strong></p>
<p>El día</p>
<p><strong>10 de marzo</strong></p>
<p>celebran un contrato de locación por cinco años.</p>
<p>Pregunta.</p>
<p>¿Quién responde frente al locador si finalmente la sociedad nunca llega a inscribirse?</p>
<p>Precisamente este tipo de situaciones explica la regulación de la sociedad en formación.</p>
</section>
<section id="sociedad-en-formación" class="slide level1">
<h1>Sociedad en formación</h1>
<p>Durante este período debe distinguirse:</p>
<ul>
<li><p>actos indispensables para obtener la inscripción;</p></li>
<li><p>actos necesarios para iniciar normalmente la actividad prevista;</p></li>
<li><p>actos extraordinarios o ajenos al objeto social.</p></li>
</ul>
<p>La imputación de responsabilidad dependerá de la naturaleza del acto y del régimen previsto por la Ley General de Sociedades.</p>
</section>
<section id="la-inscripción-registral" class="slide level1">
<h1>La inscripción registral</h1>
<p>La inscripción posee una enorme trascendencia jurídica.</p>
<p>Con ella la sociedad adquiere su condición de sociedad regularmente constituida.</p>
<p>Desde ese momento:</p>
<ul>
<li>actúa plenamente bajo el tipo elegido;</li>
<li>consolida la separación patrimonial respecto de los accionistas;</li>
<li>comienza a regir plenamente el sistema de responsabilidad propio de la sociedad anónima.</li>
</ul>
<p>Por ello suele afirmarse que la inscripción cumple una función constitutiva respecto de la regularidad de la sociedad.</p>
</section>
<section id="sociedad-anónima-unipersonal-sau" class="slide level1">
<h1>Sociedad Anónima Unipersonal (SAU)</h1>
<p>La reforma introducida por la Ley 26.994 incorporó la posibilidad de constituir sociedades anónimas con un único accionista.</p>
<p>La SAU constituye una excepción al principio histórico de pluralidad.</p>
<p>Sin embargo, la ley establece un régimen especialmente estricto destinado a proteger a los terceros.</p>
</section>
<section id="particularidades-de-la-sau" class="slide level1">
<h1>Particularidades de la SAU</h1>
<p>Entre otras exigencias especiales:</p>
<ul>
<li>un único accionista desde el origen;</li>
<li>debe constituirse exclusivamente como sociedad anónima;</li>
<li>integración total del capital al momento de la constitución;</li>
<li>fiscalización estatal permanente;</li>
<li>sindicatura obligatoria.</li>
</ul>
<p>El legislador buscó compensar los riesgos derivados de la unipersonalidad mediante mayores controles.</p>
</section>
<section id="modificaciones-posteriores-del-estatuto" class="slide level1">
<h1>Modificaciones posteriores del estatuto</h1>
<p>La vida de la sociedad no termina con la inscripción.</p>
<p>Con frecuencia será necesario modificar el estatuto.</p>
<p>Por ejemplo:</p>
<ul>
<li>aumentar o reducir el capital;</li>
<li>modificar el objeto;</li>
<li>cambiar la denominación;</li>
<li>trasladar el domicilio;</li>
<li>crear nuevas clases de acciones;</li>
<li>modificar el régimen de administración.</li>
</ul>
<p>Estas reformas requieren nuevamente el cumplimiento de los procedimientos previstos por la ley.</p>
</section>
<section id="caso-integrador-2" class="slide level1">
<h1>Caso integrador</h1>
<p>Cuatro profesionales constituyen una sociedad anónima destinada al desarrollo de software.</p>
<p>Durante la escritura fijan:</p>
<ul>
<li><p>Capital: $200.000.000.</p></li>
<li><p>200.000 acciones ordinarias.</p></li>
<li><p>Directorio de tres miembros.</p></li>
</ul>
<p>Una semana después alquilan oficinas y compran equipamiento.</p>
<p>La inscripción registral se obtiene cuarenta días más tarde.</p>
<p>Preguntas para analizar.</p>
<ul>
<li><p>¿Qué actos pueden realizar durante la etapa de formación?</p></li>
<li><p>¿Qué finalidad cumple la inscripción?</p></li>
<li><p>¿Cuándo comienza a funcionar plenamente el régimen de responsabilidad propio de la sociedad anónima?</p></li>
</ul>
</section>
<section id="conclusiones" class="slide level1">
<h1>Conclusiones</h1>
<p>La sociedad anónima constituye el principal instrumento jurídico de organización de empresas de capital.</p>
<p>Su régimen gira alrededor de tres grandes ejes.</p>
<ul>
<li><p>Constitución formal mediante escritura e inscripción.</p></li>
<li><p>Capital social como instrumento de organización y garantía.</p></li>
<li><p>Protección equilibrada de accionistas, acreedores y terceros.</p></li>
</ul>
<p>Comprender estos principios permite interpretar correctamente el régimen de las acciones, los órganos sociales, las modificaciones estatutarias y las operaciones de reorganización que serán desarrolladas en las clases siguientes.</p>
</section>
<section id="qué-representa-una-acción" class="slide level1">
<h1>¿Qué representa una acción?</h1>
<p>Hasta ahora analizamos el capital social como una cifra jurídica.</p>
<p>Sin embargo, ese capital se encuentra dividido en partes iguales.</p>
<p>Cada una de esas partes recibe el nombre de</p>
<h2 id="acción">Acción</h2>
<p>La acción representa la unidad mínima en que se divide el capital de una sociedad anónima.</p>
</section>
<section id="la-acción-como-medida-de-participación" class="slide level1">
<h1>La acción como medida de participación</h1>
<p>Supongamos:</p>
<p>Capital social</p>
<p><strong>$100.000.000</strong></p>
<p>Dividido en</p>
<p><strong>100.000 acciones</strong></p>
<p>Valor nominal</p>
<p><strong>$1.000</strong></p>
<p>Quien adquiere:</p>
<ul>
<li><p>1 acción participa en el 0,001 % del capital.</p></li>
<li><p>10.000 acciones participa en el 10 %.</p></li>
<li><p>60.000 acciones participa en el 60 %.</p></li>
</ul>
<p>La acción mide la participación del accionista dentro de la sociedad.</p>
</section>
<section id="qué-derechos-otorga-una-acción" class="slide level1">
<h1>¿Qué derechos otorga una acción?</h1>
<p>Cada acción incorpora un conjunto de derechos.</p>
<p>Entre ellos:</p>
<ul>
<li><p>participar en las asambleas;</p></li>
<li><p>votar;</p></li>
<li><p>percibir dividendos;</p></li>
<li><p>ejercer el derecho de preferencia;</p></li>
<li><p>participar en la liquidación.</p></li>
</ul>
<p>En consecuencia,</p>
<p>la acción no representa solamente dinero.</p>
<p>Representa una posición jurídica dentro de la sociedad.</p>
</section>
<section id="ejemplo-11" class="slide level1">
<h1>Ejemplo</h1>
<p>Capital:</p>
<p>$120.000.000</p>
<p>120.000 acciones.</p>
<p>Ana posee</p>
<p>24.000 acciones.</p>
<p>Entonces:</p>
<p>Participación:</p>
<p>20 %</p>
<p>Si la asamblea distribuye dividendos por</p>
<p>$36.000.000</p>
<p>Ana tendrá derecho a percibir</p>
<p>20 %</p>
<p>=</p>
<p>$7.200.000</p>
<p>La acción determina tanto derechos políticos como económicos.</p>
</section>
<section id="las-acciones-no-son-todas-iguales" class="slide level1">
<h1>Las acciones no son todas iguales</h1>
<p>La Ley General de Sociedades admite distintas clases de acciones.</p>
<p>Por ejemplo:</p>
<ul>
<li><p>acciones ordinarias;</p></li>
<li><p>acciones preferidas;</p></li>
<li><p>distintas categorías con derechos especiales.</p></li>
</ul>
<p>Todas representan una participación en el capital,</p>
<p>pero no necesariamente confieren exactamente los mismos derechos.</p>
<p>Su estudio será desarrollado al analizar el régimen jurídico de las acciones.</p>
</section>
<section id="integrando-los-conceptos" class="slide level1">
<h1>Integrando los conceptos</h1>
<p>Una sociedad presenta la siguiente situación.</p>
<p>Capital:</p>
<p>$200.000.000</p>
<p>200.000 acciones</p>
<p>Valor nominal:</p>
<p>$1.000</p>
<p>Patrimonio Neto:</p>
<p>$500.000.000</p>
<p>Ana posee</p>
<p>50.000 acciones.</p>
<p>Entonces:</p>
<ul>
<li><p>Participación política: <strong>25 %</strong></p></li>
<li><p>Valor nominal de su participación: <strong>$50.000.000</strong></p></li>
<li><p>Valor patrimonial proporcional: <strong>$125.000.000</strong></p></li>
</ul>
<p>La acción constituye el nexo entre el capital social y los derechos del accionista.</p>
</section>
<section id="síntesis-general-de-la-clase" class="slide level1">
<h1>Síntesis general de la clase</h1>
<p>Durante esta clase analizamos cuatro grandes cuestiones.</p>
<h2 id="constitución">Constitución</h2>
<ul>
<li>escritura pública;</li>
<li>estatuto;</li>
<li>inscripción;</li>
<li>sociedad en formación;</li>
<li>SAU.</li>
</ul>
<h2 id="capital-social">Capital social</h2>
<ul>
<li>concepto;</li>
<li>funciones;</li>
<li>principios.</li>
</ul>
<h2 id="variaciones">Variaciones</h2>
<ul>
<li>aumento;</li>
<li>reducción;</li>
<li>tutela de accionistas y acreedores.</li>
</ul>
<h2 id="acción-1">Acción</h2>
<ul>
<li>unidad de participación en el capital;</li>
<li>fuente de derechos políticos y económicos.</li>
</ul>
<p>En la próxima clase estudiaremos el régimen jurídico de las acciones y los órganos de la sociedad anónima.</p>
</section>
<section id="principios-del-capital-social" class="slide level1">
<h1>Principios del capital social</h1>
<p>El régimen del capital social se encuentra construido sobre una serie de principios destinados a proteger tanto a los accionistas como a los acreedores.</p>
<p>Entre los principales pueden mencionarse:</p>
<ul>
<li>determinación;</li>
<li>unidad;</li>
<li>estabilidad;</li>
<li>efectividad;</li>
<li>intangibilidad.</li>
</ul>
<p>Estos principios permiten interpretar la mayor parte de las normas relativas al capital social.</p>
</section>
<section id="determinación" class="slide level1">
<h1>Determinación</h1>
<p>El capital debe encontrarse determinado desde la constitución de la sociedad.</p>
<p>No puede existir un capital indeterminado o librado a decisiones futuras.</p>
<p>La cifra debe surgir claramente del estatuto.</p>
<h2 id="ejemplo-12">Ejemplo</h2>
<p>No sería válido establecer:</p>
<blockquote>
<p>“El capital será el que oportunamente decidan los accionistas.”</p>
</blockquote>
<p>En cambio, sí resulta válido:</p>
<p>Capital social:</p>
<p><strong>$200.000.000</strong></p>
<p>dividido en</p>
<p>200.000 acciones de valor nominal $1.000.</p>
</section>
<section id="unidad" class="slide level1">
<h1>Unidad</h1>
<p>El capital social constituye una única cifra jurídica.</p>
<p>No existen “capitales distintos” para cada accionista.</p>
<p>Todos los aportes se incorporan al patrimonio de la sociedad.</p>
<h2 id="ejemplo-13">Ejemplo</h2>
<p>Ana aporta</p>
<p>$80.000.000</p>
<p>Bruno aporta</p>
<p>$120.000.000</p>
<p>No existen dos capitales.</p>
<p>Existe un único capital social de</p>
<p><strong>$200.000.000</strong>.</p>
</section>
<section id="estabilidad" class="slide level1">
<h1>Estabilidad</h1>
<p>El capital permanece invariable hasta que sea modificado mediante los procedimientos previstos por la ley.</p>
<p>Las ganancias no aumentan automáticamente el capital.</p>
<p>Las pérdidas tampoco lo reducen automáticamente.</p>
<h2 id="ejemplo-14">Ejemplo</h2>
<p>Capital:</p>
<p>$150.000.000</p>
<p>La sociedad obtiene ganancias por</p>
<p>$90.000.000</p>
<p>El patrimonio aumenta.</p>
<p>El capital continúa siendo</p>
<p>$150.000.000</p>
</section>
<section id="efectividad" class="slide level1">
<h1>Efectividad</h1>
<p>El capital debe corresponder a aportes reales.</p>
<p>No puede integrarse mediante bienes inexistentes.</p>
<p>Tampoco mediante créditos ilusorios o bienes deliberadamente sobrevaluados.</p>
<h2 id="ejemplo-15">Ejemplo</h2>
<p>Una maquinaria vale realmente</p>
<p>$30.000.000</p>
<p>No puede aportarse diciendo que vale</p>
<p>$90.000.000</p>
<p>porque el capital dejaría de reflejar la realidad patrimonial.</p>
</section>
<section id="intangibilidad" class="slide level1">
<h1>Intangibilidad</h1>
<p>La sociedad no puede devolver libremente el capital a los accionistas.</p>
<p>Mientras existan acreedores,</p>
<p>el capital constituye una referencia patrimonial cuya disminución exige el cumplimiento de requisitos legales.</p>
<p>Por ello la reducción de capital se encuentra especialmente regulada por la Ley General de Sociedades.</p>
</section>
<section id="caso-integrador-3" class="slide level1">
<h1>Caso integrador</h1>
<p>La sociedad posee:</p>
<p>Capital:</p>
<p>$500.000.000</p>
<p>Patrimonio:</p>
<p>$900.000.000</p>
<p>La asamblea decide distribuir</p>
<p>$350.000.000</p>
<p>a los accionistas.</p>
<p>Pregunta.</p>
<p>¿Puede hacerlo libremente?</p>
<p>La respuesta dependerá de distinguir:</p>
<ul>
<li>distribución de utilidades;</li>
<li>devolución de aportes;</li>
<li>reducción de capital;</li>
<li>tutela de los acreedores.</li>
</ul>
<p>Los principios del capital social permiten resolver correctamente este tipo de situaciones.</p>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 4.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiado");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiado");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>