<!DOCTYPE html>
<html lang="es"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Prof.&nbsp;Maximiliano Lucas Romei">
  <title>Sociedades Civiles y Comerciales – Fallos fundamentales sobre personalidad jurídica</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-0427d8d92a431aa6a6430e53ec02a470.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
  <script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
  <link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Fallos fundamentales sobre personalidad jurídica</h1>
  <p class="subtitle">Parke Davis · Swift-Deltec · Palomeque</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Maximiliano Lucas Romei 
</div>
</div>
</div>

</section>
<section id="objetivos" class="slide level1">
<h1>Objetivos</h1>
<p>Al finalizar esta presentación el estudiante deberá poder:</p>
<ul>
<li>comprender el origen jurisprudencial de la teoría de la inoponibilidad;</li>
<li>distinguir personalidad jurídica y realidad económica;</li>
<li>explicar la evolución entre Parke Davis, Swift y Palomeque;</li>
<li>interpretar el art. 54 LGS;</li>
<li>interpretar el art. 144 CCyC;</li>
<li>comprender cuándo corresponde correr el velo societario.</li>
</ul>
</section>
<section id="los-tres-grandes-precedentes" class="slide level1 scrollable">
<h1>Los tres grandes precedentes</h1>
<p>La evolución jurisprudencial argentina puede resumirse en tres grandes decisiones.</p>
<ol type="1">
<li><strong>Parke Davis (1973).</strong></li>
<li><strong>Swift-Deltec (1974).</strong></li>
<li><strong>Palomeque (2003).</strong></li>
</ol>
<p>Cada una responde a una pregunta distinta.</p>
</section>
<section id="la-evolución-jurisprudencial" class="slide level1">
<h1>La evolución jurisprudencial</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
A["Parke Davis&lt;br/&gt;1973"] --&gt; B["Swift-Deltec&lt;br/&gt;1974"]
B --&gt; C["Art. 54 LGS&lt;br/&gt;1983"]
C --&gt; D["Palomeque&lt;br/&gt;2003"]
D --&gt; E["Art. 144 CCyC&lt;br/&gt;2015"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="el-problema-común" class="slide level1">
<h1>El problema común</h1>
<p>Los tres fallos parten de una misma pregunta.</p>
<h2 id="puede-invocarse-siempre-la-personalidad-jurídica">¿Puede invocarse siempre la personalidad jurídica?</h2>
<p>o</p>
<h2 id="existen-situaciones-excepcionales-en-las-cuales-corresponde-prescindir-de-ella">¿Existen situaciones excepcionales en las cuales corresponde prescindir de ella?</h2>
</section>
<section id="la-personalidad-jurídica" class="slide level1">
<h1>La personalidad jurídica</h1>
<p>Como regla:</p>
<p>la sociedad constituye un sujeto distinto de sus socios.</p>
<p>Consecuencias:</p>
<ul>
<li>patrimonio propio;</li>
<li>nombre propio;</li>
<li>domicilio;</li>
<li>responsabilidad propia;</li>
<li>capacidad.</li>
</ul>
</section>
<section id="la-regla" class="slide level1">
<h1>La regla</h1>
<p>La personalidad jurídica constituye uno de los pilares del Derecho Societario.</p>
<p>Sin personalidad diferenciada:</p>
<ul>
<li>desaparecería la autonomía patrimonial;</li>
<li>desaparecería la limitación de responsabilidad;</li>
<li>desaparecería la organización societaria moderna.</li>
</ul>
</section>
<section id="entonces" class="slide level1">
<h1>Entonces…</h1>
<p>¿Por qué aparecen estos tres fallos?</p>
<p>Porque la personalidad jurídica puede ser utilizada correctamente…</p>
<p>o abusivamente.</p>
</section>
<section id="el-abuso" class="slide level1">
<h1>El abuso</h1>
<p>La personalidad jurídica deja de cumplir su función cuando se transforma en:</p>
<ul>
<li>un instrumento de fraude;</li>
<li>una pantalla;</li>
<li>un mecanismo para violar la ley;</li>
<li>un medio para perjudicar terceros.</li>
</ul>
</section>
<section id="la-gran-discusión" class="slide level1">
<h1>La gran discusión</h1>
<p>Dos principios aparecen en tensión.</p>
<h2 id="seguridad-jurídica">Seguridad jurídica</h2>
<p>vs.</p>
<h2 id="justicia-material">Justicia material</h2>
<p>Toda la evolución jurisprudencial gira alrededor de ese conflicto.</p>
</section>
<section id="influencia-norteamericana" class="slide level1">
<h1>Influencia norteamericana</h1>
<p>La doctrina argentina no nació aislada.</p>
<p>Recibió una fuerte influencia del Derecho estadounidense.</p>
<p>Especialmente de la teoría denominada:</p>
<h2 id="disregard-of-legal-entity">Disregard of Legal Entity</h2>
</section>
<section id="disregard-of-legal-entity-1" class="slide level1">
<h1>Disregard of Legal Entity</h1>
<p>Literalmente:</p>
<blockquote>
<p>“Desconocimiento de la personalidad jurídica.”</p>
</blockquote>
<p>Más correctamente:</p>
<blockquote>
<p>Prescindencia del velo societario.</p>
</blockquote>
<p>No implica negar la existencia de la sociedad.</p>
<p>Implica impedir que la personalidad sea utilizada abusivamente.</p>
</section>
<section id="primer-antecedente" class="slide level1">
<h1>Primer antecedente</h1>
<h2 id="bank-of-the-united-states-v.-deveaux">Bank of the United States v. Deveaux</h2>
<p>1809</p>
<p>La Corte norteamericana sostuvo que, en determinados casos, debía observarse quiénes eran realmente las personas que actuaban detrás de la corporación. :contentReference<span data-index="0">oaicite:0</span></p>
</section>
<section id="segundo-antecedente" class="slide level1">
<h1>Segundo antecedente</h1>
<h2 id="harris-v.-youngstown-bridge-co.">Harris v. Youngstown Bridge Co.</h2>
<p>1898</p>
<p>Surge la denominada</p>
<h2 id="alter-ego-doctrine">alter ego doctrine</h2>
<p>La sociedad controlada aparece como el “alter ego” de la controlante. :contentReference<span data-index="1">oaicite:1</span></p>
</section>
<section id="recepción-en-argentina" class="slide level1">
<h1>Recepción en Argentina</h1>
<p>La jurisprudencia argentina no copia literalmente la doctrina norteamericana.</p>
<p>La adapta.</p>
<p>Y el primer gran precedente es:</p>
</section>
<section id="parke-davis." class="slide level1">
<h1>Parke Davis.</h1>
</section>
<section id="parke-davis" class="slide level1">
<h1>Parke Davis</h1>
<h2 id="corte-suprema-de-justicia-de-la-nación">Corte Suprema de Justicia de la Nación</h2>
<p>31 de julio de 1973</p>
<p>Uno de los fallos más influyentes de toda la historia del Derecho Societario argentino. :contentReference<span data-index="2">oaicite:2</span></p>
</section>
<section id="por-qué-estudiar-parke-davis" class="slide level1">
<h1>¿Por qué estudiar Parke Davis?</h1>
<p>Porque inaugura una manera distinta de observar la personalidad jurídica.</p>
<p>La Corte deja de mirar únicamente las formas jurídicas.</p>
<p>Comienza a analizar la realidad económica.</p>
</section>
<section id="contexto-histórico" class="slide level1">
<h1>Contexto histórico</h1>
<p>Década del 70.</p>
<p>Expansión de las empresas multinacionales.</p>
<p>Crecimiento de grupos societarios internacionales.</p>
<p>Mayor utilización de subsidiarias nacionales.</p>
</section>
<section id="la-empresa" class="slide level1">
<h1>La empresa</h1>
<p>Parke Davis desarrollaba actividad farmacéutica.</p>
<p>Su estructura societaria respondía a un típico grupo multinacional.</p>
</section>
<section id="la-estructura-del-grupo" class="slide level1">
<h1>La estructura del grupo</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Parke Davis &amp; Company&lt;br&gt;Estados Unidos"]

B["99,95 % del capital"]

C["Parke Davis Argentina"]

A --&gt; B
B --&gt; C
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La sociedad estadounidense controlaba prácticamente la totalidad del capital social argentino.</p>
</section>
<section id="el-conflicto" class="slide level1">
<h1>El conflicto</h1>
<p>La sociedad argentina pagaba regalías a la casa matriz.</p>
<p>Las regalías se deducían del impuesto.</p>
<p>La DGI rechazó esa deducción.</p>
</section>
<section id="la-operatoria" class="slide level1">
<h1>La operatoria</h1>
<p>Entre ambas sociedades existían contratos de licencia.</p>
<p>La sociedad argentina abonaba regalías por:</p>
<ul>
<li>utilización de patentes;</li>
<li>utilización de marcas;</li>
<li>transferencia de tecnología;</li>
<li>asistencia técnica.</li>
</ul>
<p>Estas regalías eran contabilizadas como gastos deducibles del impuesto a los réditos.</p>
</section>
<section id="cuál-era-el-beneficio-fiscal" class="slide level1">
<h1>¿Cuál era el beneficio fiscal?</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Ingresos"]
B["(-) Costos"]
C["(-) Regalías"]
D["Ganancia imponible"]
E["Menor Impuesto"]

A --&gt; B
B --&gt; C
C --&gt; D
D --&gt; E
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La discusión giró alrededor de la legitimidad de esa deducción.</p>
</section>
<section id="la-posición-de-la-dgi" class="slide level1">
<h1>La posición de la DGI</h1>
<p>La Dirección General Impositiva sostuvo que:</p>
<ul>
<li>las regalías no podían analizarse aisladamente;</li>
<li>debía observarse el funcionamiento del grupo empresario;</li>
<li>la personalidad jurídica no podía ocultar la verdadera realidad económica.</li>
</ul>
</section>
<section id="la-defensa-de-parke-davis" class="slide level1">
<h1>La defensa de Parke Davis</h1>
<p>La empresa sostuvo que:</p>
<ul>
<li>ambas sociedades tenían personalidad jurídica propia;</li>
<li>los contratos eran válidos;</li>
<li>las regalías respondían a prestaciones efectivamente realizadas;</li>
<li>las deducciones estaban autorizadas por la legislación tributaria.</li>
</ul>
</section>
<section id="la-verdadera-discusión" class="slide level1">
<h1>La verdadera discusión</h1>
<p>La Corte no debía decidir únicamente una cuestión tributaria.</p>
<p>Debía resolver una cuestión mucho más profunda.</p>
<h2 id="hasta-dónde-llega-la-autonomía-de-la-personalidad-jurídica">¿Hasta dónde llega la autonomía de la personalidad jurídica?</h2>
</section>
<section id="pregunta-central" class="slide level1">
<h1>Pregunta central</h1>
<p>¿Puede una sociedad pagar regalías a otra sociedad cuando esta última controla prácticamente la totalidad de su capital?</p>
<p>¿Existe verdadera independencia económica?</p>
</section>
<section id="el-principio-de-realidad-económica" class="slide level1">
<h1>El principio de realidad económica</h1>
<p>La Corte recuerda que el Derecho Tributario no puede quedar subordinado exclusivamente a las formas jurídicas.</p>
<p>Debe atenderse al contenido económico real de la operación. :contentReference<span data-index="1">oaicite:1</span></p>
</section>
<section id="texto-del-fallo" class="slide level1">
<h1>Texto del fallo</h1>
<blockquote>
<p>“…debe atenderse a la realidad económica de los actos, situaciones y relaciones, con prescindencia de las formas o estructuras jurídicas que puedan no corresponder a esa realidad.”</p>
</blockquote>
<p><strong>CSJN – Parke Davis.</strong></p>
</section>
<section id="comentario" class="slide level1">
<h1>Comentario</h1>
<p>Este párrafo constituye el verdadero eje del precedente.</p>
<p>La Corte no desconoce la existencia de la personalidad jurídica.</p>
<p>Lo que sostiene es que las formas jurídicas no pueden prevalecer cuando distorsionan la verdadera realidad económica.</p>
</section>
<section id="un-cambio-metodológico" class="slide level1">
<h1>Un cambio metodológico</h1>
<p>Hasta entonces predominaba una interpretación predominantemente formal.</p>
<p>Parke Davis inaugura una interpretación:</p>
<ul>
<li>funcional;</li>
<li>económica;</li>
<li>material.</li>
</ul>
</section>
<section id="el-razonamiento-de-la-corte" class="slide level1">
<h1>El razonamiento de la Corte</h1>
<p>La sentencia observa que:</p>
<ul>
<li>existe una sociedad controlante;</li>
<li>existe una sociedad controlada;</li>
<li>ambas integran un mismo proceso económico.</li>
</ul>
<p>Por ello la operación no puede analizarse como si involucrara sujetos completamente independientes.</p>
</section>
<section id="el-control-accionario" class="slide level1">
<h1>El control accionario</h1>
<p>El dato decisivo fue el porcentaje de participación.</p>
<h2 id="la-sociedad-estadounidense-poseía-aproximadamente-el-9995-del-capital-de-la-filial-argentina.">La sociedad estadounidense poseía aproximadamente el <strong>99,95 %</strong> del capital de la filial argentina.</h2>
</section>
<section id="por-qué-es-importante-ese-dato" class="slide level1">
<h1>¿Por qué es importante ese dato?</h1>
<p>Porque demuestra:</p>
<ul>
<li>dirección económica única;</li>
<li>ausencia de verdadera independencia;</li>
<li>subordinación de la filial.</li>
</ul>
</section>
<section id="personalidad-jurídica" class="slide level1">
<h1>Personalidad jurídica</h1>
<p>La Corte jamás afirma que la sociedad argentina carezca de personalidad jurídica.</p>
<p>Por el contrario,</p>
<p>reconoce su existencia.</p>
</section>
<section id="entonces-1" class="slide level1">
<h1>Entonces…</h1>
<p>¿Qué hace realmente la Corte?</p>
<p>No elimina la personalidad.</p>
<p>Analiza si esa personalidad alcanza para explicar adecuadamente la realidad económica.</p>
</section>
<section id="segunda-cita-fundamental" class="slide level1">
<h1>Segunda cita fundamental</h1>
<blockquote>
<p>“…las formas jurídicas adoptadas no pueden impedir el conocimiento de la verdadera naturaleza económica de las operaciones.”</p>
</blockquote>
<p><strong>CSJN – Parke Davis.</strong></p>
</section>
<section id="explicación" class="slide level1">
<h1>Explicación</h1>
<p>Las sociedades siguen existiendo.</p>
<p>Los contratos siguen existiendo.</p>
<p>Pero el juez puede preguntarse:</p>
<p>¿reflejan verdaderamente la realidad económica?</p>
</section>
<section id="la-unidad-económica" class="slide level1">
<h1>La unidad económica</h1>
<p>La Corte entiende que existe una unidad económica.</p>
<p>No observa dos centros independientes de decisión.</p>
<p>Observa un único interés económico organizado mediante distintas personas jurídicas.</p>
</section>
<section id="corre-el-velo-societario" class="slide level1">
<h1>¿Corre el velo societario?</h1>
<p>Esta pregunta genera una intensa discusión doctrinaria.</p>
</section>
<section id="primera-postura" class="slide level1">
<h1>Primera postura</h1>
<p>Parke Davis constituye el primer caso argentino de desestimación de la personalidad jurídica.</p>
</section>
<section id="segunda-postura" class="slide level1">
<h1>Segunda postura</h1>
<p>La Corte no corre el velo.</p>
<p>Simplemente aplica el principio tributario de realidad económica.</p>
</section>
<section class="slide level1">

<p><strong>Desde el punto de vista formal</strong>, la Corte aplica el principio tributario de la realidad económica previsto en la Ley 11.683.</p>
<p><strong>Desde el punto de vista material</strong>, el razonamiento utilizado anticipa claramente la doctrina que años más tarde inspirará la desestimación de la personalidad jurídica, desarrollada en <em>Swift-Deltec</em> y finalmente receptada en el art. 54 de la Ley General de Sociedades.</p>
<p>Por ello, <strong>Parke Davis no aplica todavía el art. 54 LGS (que aún no existía), pero sí constituye uno de sus antecedentes jurisprudenciales más relevantes.</strong></p>
</section>
<section id="importancia-histórica" class="slide level1">
<h1>Importancia histórica</h1>
<p>Por ello la doctrina considera a Parke Davis el gran antecedente de:</p>
<ul>
<li>Swift-Deltec;</li>
<li>art. 54 LGS;</li>
<li>art. 144 CCyC.</li>
</ul>
</section>
<section id="el-mensaje-del-fallo" class="slide level1">
<h1>El mensaje del fallo</h1>
<p>La personalidad jurídica merece tutela.</p>
<p>Pero no puede convertirse en una barrera infranqueable para alcanzar soluciones manifiestamente injustas.</p>
</section>
<section id="esquema-conceptual" class="slide level1">
<h1>Esquema conceptual</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Personalidad jurídica"]

B["Realidad económica"]

C["Control societario"]

D["Decisión de la Corte"]

A --&gt; D
B --&gt; D
C --&gt; D
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="primera-enseñanza" class="slide level1">
<h1>Primera enseñanza</h1>
<p>La personalidad jurídica es la regla.</p>
<p>La realidad económica constituye el criterio interpretativo que permite evitar el abuso de las formas jurídicas.</p>
</section>
<section id="qué-no-dijo-la-corte" class="slide level1">
<h1>¿Qué NO dijo la Corte?</h1>
<p>Es importante advertir aquello que el fallo no sostiene.</p>
<p>La Corte:</p>
<ul>
<li>no declara inexistente a la sociedad;</li>
<li>no desconoce su personalidad jurídica;</li>
<li>no anula los contratos celebrados;</li>
<li>no elimina la separación patrimonial.</li>
</ul>
</section>
<section id="lo-que-realmente-sostuvo" class="slide level1">
<h1>Lo que realmente sostuvo</h1>
<p>La Corte afirmó que:</p>
<blockquote>
<p>la personalidad jurídica no puede impedir que el juez examine la verdadera realidad económica de una operación.</p>
</blockquote>
<p>Ese examen puede conducir a soluciones distintas de las que surgirían de una interpretación puramente formal.</p>
</section>
<section id="realidad-económica" class="slide level1">
<h1>Realidad económica</h1>
<h2 id="qué-significa">¿Qué significa?</h2>
<p>No significa ignorar el Derecho.</p>
<p>Significa interpretar la norma teniendo en cuenta:</p>
<ul>
<li>quién obtiene realmente el beneficio;</li>
<li>quién soporta verdaderamente el riesgo;</li>
<li>quién adopta las decisiones económicas.</li>
</ul>
</section>
<section id="la-subordinación-económica" class="slide level1">
<h1>La subordinación económica</h1>
<p>La filial argentina desarrollaba actividad propia.</p>
<p>Sin embargo,</p>
<p>sus decisiones estratégicas se encontraban condicionadas por la sociedad controlante.</p>
<h2 id="la-corte-atribuye-especial-importancia-a-esa-circunstancia.">La Corte atribuye especial importancia a esa circunstancia.</h2>
</section>
<section id="control-y-dependencia" class="slide level1">
<h1>Control y dependencia</h1>
<p>No todo control societario elimina la autonomía jurídica.</p>
<p>Pero cuanto mayor sea el control,</p>
<p>más intensamente deberá analizarse la verdadera independencia económica.</p>
</section>
<section id="dos-planos-distintos" class="slide level1">
<h1>Dos planos distintos</h1>
<h2 id="plano-jurídico">Plano jurídico</h2>
<p>Existen dos personas jurídicas.</p>
<h2 id="plano-económico">Plano económico</h2>
<p>Existe una dirección económica común.</p>
<p>Parke Davis enseña que ambos planos no siempre coinciden.</p>
</section>
<section id="primer-aporte-del-fallo" class="slide level1">
<h1>Primer aporte del fallo</h1>
<p>La personalidad jurídica deja de ser considerada un dogma absoluto.</p>
<p>Pasa a concebirse como una técnica jurídica al servicio de determinados fines.</p>
</section>
<section id="segundo-aporte" class="slide level1">
<h1>Segundo aporte</h1>
<p>Las estructuras societarias pueden ser analizadas críticamente por los tribunales.</p>
<p>No basta invocar una forma legalmente válida.</p>
<p>Debe verificarse que esa forma responda a una finalidad legítima.</p>
</section>
<section id="tercer-aporte" class="slide level1">
<h1>Tercer aporte</h1>
<p>La Corte incorpora al análisis societario una dimensión económica.</p>
<p>El juez deja de observar únicamente:</p>
<ul>
<li>contratos;</li>
<li>estatutos;</li>
<li>personerías.</li>
</ul>
<p>También observa:</p>
<ul>
<li>funcionamiento;</li>
<li>control;</li>
<li>dependencia;</li>
<li>finalidad económica.</li>
</ul>
</section>
<section id="la-doctrina-posterior" class="slide level1">
<h1>La doctrina posterior</h1>
<p>Gran parte de la doctrina considera que Parke Davis inaugura el tránsito desde una visión estrictamente formal hacia una concepción funcional de la personalidad jurídica.</p>
</section>
<section id="influencia-doctrinaria" class="slide level1">
<h1>Influencia doctrinaria</h1>
<p>Después de Parke Davis comienza a utilizarse con mayor frecuencia la expresión:</p>
<h2 id="penetración-del-velo-societario">“penetración del velo societario”</h2>
<p>aunque esa expresión no aparece literalmente en el fallo.</p>
</section>
<section id="qué-es-el-velo-societario" class="slide level1">
<h1>¿Qué es el velo societario?</h1>
<p>Es una metáfora.</p>
<p>La personalidad jurídica funciona como un “velo” que separa:</p>
<ul>
<li>sociedad;</li>
<li>socios;</li>
<li>controlantes.</li>
</ul>
<p>En situaciones excepcionales,</p>
<p>el juez puede “correr” ese velo para conocer quién actúa realmente detrás de la persona jurídica.</p>
</section>
<section id="siempre-puede-correrse" class="slide level1">
<h1>¿Siempre puede correrse?</h1>
<p>No.</p>
<p>Precisamente la evolución posterior de la jurisprudencia demuestra que se trata de un remedio extraordinario.</p>
</section>
<section id="evolución-posterior" class="slide level1">
<h1>Evolución posterior</h1>
<pre><code>Parke Davis
        │
        ▼
Swift-Deltec
        │
        ▼
Art. 54 LGS
        │
        ▼
Palomeque
        │
        ▼
Art. 144 CCyC</code></pre>
</section>
<section id="del-precedente-a-la-ley" class="slide level1">
<h1>Del precedente a la ley</h1>
<p>Diez años después del fallo Parke Davis,</p>
<p>la Ley 22.903 incorporó el actual tercer párrafo del artículo 54 de la Ley de Sociedades.</p>
<p>No reprodujo literalmente el fallo,</p>
<p>pero recogió su filosofía.</p>
</section>
<section id="artículo-54-lgs" class="slide level1">
<h1>Artículo 54 LGS</h1>
<p>La actuación de la sociedad que:</p>
<ul>
<li>encubra fines extrasocietarios;</li>
<li>constituya un recurso para violar la ley;</li>
<li>viole el orden público;</li>
<li>viole la buena fe;</li>
<li>frustre derechos de terceros,</li>
</ul>
<p>permitirá imputar directamente las consecuencias a quienes hicieron posible ese accionar.</p>
</section>
<section id="diferencia-importante" class="slide level1">
<h1>Diferencia importante</h1>
<h2 id="parke-davis-1">Parke Davis</h2>
<p>Realidad económica.</p>
<h2 id="artículo-54">Artículo 54</h2>
<p>Fraude societario.</p>
<p>No son conceptos idénticos.</p>
</section>
<section id="por-qué-importa-esta-diferencia" class="slide level1">
<h1>¿Por qué importa esta diferencia?</h1>
<p>Porque toda actuación económicamente unitaria</p>
<p>NO constituye fraude.</p>
<p>La utilización de grupos empresarios es perfectamente lícita.</p>
<p>Lo ilícito aparece cuando la personalidad jurídica se utiliza abusivamente.</p>
</section>
<section id="pregunta-de-examen" class="slide level1">
<h1>Pregunta de examen</h1>
<p>¿Puede afirmarse que todo grupo económico autoriza la desestimación de la personalidad jurídica?</p>
<h2 id="respuesta">Respuesta</h2>
<p>No.</p>
<p>El grupo económico constituye un dato relevante,</p>
<p>pero resulta insuficiente por sí solo.</p>
<p>Será necesario acreditar los presupuestos exigidos por la ley.</p>
</section>
<section id="críticas-doctrinarias" class="slide level1">
<h1>Críticas doctrinarias</h1>
<p>Parte de la doctrina entendió que Parke Davis podía generar inseguridad jurídica.</p>
<p>El excesivo recurso a la realidad económica podría afectar:</p>
<ul>
<li>la autonomía patrimonial;</li>
<li>la previsibilidad;</li>
<li>la estabilidad de las sociedades.</li>
</ul>
</section>
<section id="defensa-del-precedente" class="slide level1">
<h1>Defensa del precedente</h1>
<p>Otra parte de la doctrina sostuvo exactamente lo contrario.</p>
<p>La personalidad jurídica no puede transformarse en un instrumento para obtener ventajas incompatibles con la finalidad de la ley.</p>
</section>
<section id="enseñanza-principal" class="slide level1">
<h1>Enseñanza principal</h1>
<p>Parke Davis no destruye la personalidad jurídica.</p>
<p>La fortalece.</p>
<p>Porque demuestra que el ordenamiento protege a las sociedades legítimas,</p>
<p>pero no tolera su utilización abusiva.</p>
</section>
<section id="síntesis" class="slide level1 scrollable">
<h1>Síntesis</h1>
<p>Parke Davis enseña cinco ideas fundamentales.</p>
<ol type="1">
<li>La personalidad jurídica constituye la regla.</li>
<li>Las formas jurídicas no son absolutas.</li>
<li>Debe atenderse a la realidad económica.</li>
<li>El control societario puede resultar jurídicamente relevante.</li>
<li>El precedente constituye el punto de partida de toda la evolución posterior sobre la inoponibilidad.</li>
</ol>
</section>
<section id="fin-de-la-primera-parte" class="slide level1">
<h1>Fin de la primera parte</h1>
<h2 id="a-continuación">A continuación:</h2>
</section>
<section id="swift-deltec" class="slide level1">
<h1>Swift-Deltec</h1>
<p>Del principio de realidad económica…</p>
<p>a la verdadera doctrina argentina sobre la inoponibilidad de la personalidad jurídica.</p>
</section>
<section id="segunda-parte" class="slide level1">
<h1>Segunda Parte</h1>
</section>
<section id="swift-deltec-1" class="slide level1">
<h1>Swift-Deltec</h1>
<h2 id="csjn-1974">CSJN — 1974</h2>
<p>El verdadero nacimiento de la doctrina argentina sobre la inoponibilidad de la personalidad jurídica.</p>
</section>
<section id="por-qué-estudiar-swift" class="slide level1">
<h1>¿Por qué estudiar Swift?</h1>
<p>Si Parke Davis introdujo el principio de realidad económica,</p>
<p>Swift transformó esa idea en un verdadero instrumento de tutela de los acreedores.</p>
<p>Es probablemente el precedente más importante del Derecho Societario argentino en materia de desestimación de la personalidad jurídica.</p>
</section>
<section id="el-contexto" class="slide level1">
<h1>El contexto</h1>
<p>A fines de la década de 1960 la empresa</p>
<h2 id="compañía-swift-de-la-plata-s.a.">Compañía Swift de La Plata S.A.</h2>
<p>atravesaba una profunda crisis económica.</p>
<p>Finalmente solicitó la apertura de su concurso preventivo.</p>
</section>
<section id="el-grupo-empresario" class="slide level1">
<h1>El grupo empresario</h1>
<p>Swift Argentina no actuaba aisladamente.</p>
<p>Integraba un grupo multinacional.</p>
<p>La sociedad controlante era</p>
<h2 id="deltec-international.">Deltec International.</h2>
</section>
<section id="la-estructura" class="slide level1">
<h1>La estructura</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Deltec International"]

B["Control accionario"]

C["Swift de La Plata"]

A --&gt; B
B --&gt; C
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="el-concurso" class="slide level1">
<h1>El concurso</h1>
<p>Durante el trámite concursal ocurrió un hecho llamativo.</p>
<p>La propia sociedad controlante</p>
<p>se presentó como acreedora de Swift.</p>
<h2 id="solicitó-verificar-un-crédito-de-importante-magnitud.">Solicitó verificar un crédito de importante magnitud.</h2>
</section>
<section id="qué-implicaba-esa-verificación" class="slide level1">
<h1>¿Qué implicaba esa verificación?</h1>
<p>No era solamente una cuestión de cobro.</p>
<p>En el concurso preventivo</p>
<p>quien verifica un crédito</p>
<p>puede participar en la formación de las mayorías.</p>
</section>
<section id="entonces-2" class="slide level1">
<h1>Entonces…</h1>
<p>Si Deltec verificaba su crédito,</p>
<p>podía votar.</p>
<p>Y si votaba,</p>
<p>podía influir decisivamente sobre la aprobación del acuerdo preventivo.</p>
</section>
<section id="el-problema" class="slide level1">
<h1>El problema</h1>
<p>¿Puede una sociedad controlar a otra…</p>
<p>y al mismo tiempo presentarse como acreedora para votar en su concurso?</p>
</section>
<section id="la-cuestión-jurídica" class="slide level1">
<h1>La cuestión jurídica</h1>
<p>La discusión dejó de ser exclusivamente concursal.</p>
<p>Pasó a ser una cuestión de Derecho Societario.</p>
<p>¿Existían realmente dos sujetos independientes?</p>
<p>¿O una única realidad económica?</p>
</section>
<section id="la-sospecha-del-tribunal" class="slide level1">
<h1>La sospecha del Tribunal</h1>
<p>Los jueces advirtieron que,</p>
<p>si se admitía la verificación,</p>
<p>el grupo empresario terminaría decidiendo el resultado del concurso.</p>
<p>Ello perjudicaba directamente a los acreedores externos.</p>
</section>
<section id="el-fraude" class="slide level1">
<h1>El fraude</h1>
<p>El verdadero fraude no consistía solamente en presentar un crédito.</p>
<p>Consistía en utilizar la estructura del grupo societario para controlar el procedimiento concursal.</p>
</section>
<section id="texto-del-trabajo-doctrinario" class="slide level1">
<h1>Texto del trabajo doctrinario</h1>
<blockquote>
<p>“…Swift era sólo una empresa subsidiaria de Deltec, quien era titular del paquete accionario mayoritario…”</p>
</blockquote>
</section>
<section id="comentario-1" class="slide level1">
<h1>Comentario</h1>
<p>No bastaba observar la personalidad jurídica.</p>
<p>Era necesario analizar</p>
<p>quién ejercía realmente el control económico.</p>
</section>
<section id="texto" class="slide level1">
<h1>Texto</h1>
<blockquote>
<p>“…Swift y Deltec eran la misma persona…”</p>
</blockquote>
</section>
<section id="qué-significa-esa-expresión" class="slide level1">
<h1>¿Qué significa esa expresión?</h1>
<p>Naturalmente,</p>
<p>la Corte no sostuvo que jurídicamente fueran idénticas.</p>
<p>Lo que afirmó es que,</p>
<p>desde el punto de vista económico,</p>
<p>actuaban como una sola organización.</p>
</section>
<section id="la-decisión" class="slide level1">
<h1>La decisión</h1>
<p>La Justicia rechazó la verificación del crédito.</p>
<p>Consecuentemente,</p>
<p>Deltec no pudo integrar las mayorías concursales.</p>
</section>
<section id="resultado" class="slide level1">
<h1>Resultado</h1>
<p>Tampoco fue homologado el acuerdo preventivo.</p>
<p>Finalmente,</p>
<p>se decretó la quiebra de Swift.</p>
</section>
<section id="la-doctrina-swift" class="slide level1">
<h1>La doctrina Swift</h1>
<p>Swift inaugura una idea fundamental.</p>
<p>Los grupos económicos</p>
<p>no pueden utilizar la personalidad jurídica</p>
<p>para manipular los procedimientos concursales.</p>
</section>
<section id="texto-doctrinario" class="slide level1">
<h1>Texto doctrinario</h1>
<blockquote>
<p>“…la totalidad del conjunto económico tiene que responder por las deudas de cada uno de sus segmentos…”</p>
</blockquote>
</section>
<section id="explicación-1" class="slide level1">
<h1>Explicación</h1>
<p>No significa que</p>
<p>todo grupo económico responda automáticamente.</p>
<p>Significa que,</p>
<p>cuando la personalidad jurídica es utilizada fraudulentamente,</p>
<p>la separación patrimonial deja de ser oponible.</p>
</section>
<section id="la-metáfora-utilizada-por-lozada" class="slide level1">
<h1>La metáfora utilizada por Lozada</h1>
<p>El juez Salvador María Lozada explicó la situación mediante un ejemplo.</p>
</section>
<section id="texto-1" class="slide level1">
<h1>Texto</h1>
<blockquote>
<p>“…es como si una persona dijera que no pagará sus deudas porque su brazo o su cabeza son acreedores de ella misma…”</p>
</blockquote>
</section>
<section id="comentario-2" class="slide level1">
<h1>Comentario</h1>
<p>Es probablemente la explicación más conocida del fallo.</p>
<p>Resume perfectamente la idea de unidad económica.</p>
</section>
<section id="diferencia-con-parke-davis" class="slide level1">
<h1>Diferencia con Parke Davis</h1>
<h2 id="parke-davis-2">Parke Davis</h2>
<p>Realidad económica.</p>
<h2 id="swift">Swift</h2>
<p>Fraude mediante utilización de la personalidad jurídica.</p>
</section>
<section id="un-paso-más" class="slide level1">
<h1>Un paso más</h1>
<p>Swift ya no se limita a interpretar económicamente.</p>
<p>Comienza a construir</p>
<p>la verdadera doctrina argentina del levantamiento del velo societario.</p>
</section>
<section id="influencia-legislativa" class="slide level1">
<h1>Influencia legislativa</h1>
<p>La enorme repercusión del caso motivó que,</p>
<p>años después,</p>
<p>el legislador incorporara expresamente</p>
<p>el tercer párrafo del artículo 54 de la Ley 19.550.</p>
</section>
<section id="artículo-54-lgs-1" class="slide level1">
<h1>Artículo 54 LGS</h1>
<p>La actuación de la sociedad que:</p>
<ul>
<li>encubra fines extrasocietarios;</li>
<li>constituya un recurso para violar la ley;</li>
<li>viole el orden público;</li>
<li>viole la buena fe;</li>
<li>frustre derechos de terceros,</li>
</ul>
<p>habilita la imputación directa a socios y controlantes.</p>
</section>
<section id="qué-tomó-el-legislador-de-swift" class="slide level1">
<h1>¿Qué tomó el legislador de Swift?</h1>
<p>Principalmente esta idea.</p>
<p>La personalidad jurídica</p>
<p>no puede convertirse</p>
<p>en un instrumento para defraudar acreedores.</p>
</section>
<section id="enseñanza-central" class="slide level1">
<h1>Enseñanza central</h1>
<p>Swift no elimina la personalidad jurídica.</p>
<p>Sanciona</p>
<p>el uso abusivo de esa personalidad.</p>
</section>
<section id="comparación" class="slide level1">
<h1>Comparación</h1>
<table class="caption-top">
<thead>
<tr class="header">
<th>Parke Davis</th>
<th>Swift</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Realidad económica</td>
<td>Fraude</td>
</tr>
<tr class="even">
<td>Tributario</td>
<td>Concursal</td>
</tr>
<tr class="odd">
<td>Interpretación</td>
<td>Inoponibilidad</td>
</tr>
<tr class="even">
<td>Antecedente</td>
<td>Desarrollo</td>
</tr>
</tbody>
</table>
</section>
<section id="transición" class="slide level1">
<h1>Transición</h1>
<p>Sin embargo,</p>
<p>la evolución jurisprudencial no terminó allí.</p>
<p>Décadas después,</p>
<p>la Corte Suprema fijó un límite muy importante.</p>
<p>Ese precedente fue</p>
</section>
<section id="palomeque." class="slide level1">
<h1>Palomeque.</h1>
</section>
<section id="tercera-parte" class="slide level1">
<h1>Tercera Parte</h1>
</section>
<section id="palomeque" class="slide level1">
<h1>Palomeque</h1>
<h2 id="csjn">CSJN</h2>
<p>El límite de la doctrina de la inoponibilidad.</p>
</section>
<section id="por-qué-es-tan-importante-palomeque" class="slide level1">
<h1>¿Por qué es tan importante Palomeque?</h1>
<p>Después de Parke Davis y Swift comenzó a extenderse una idea.</p>
<blockquote>
<p>Siempre que una sociedad incumple una obligación, corresponde correr el velo societario.</p>
</blockquote>
<p>La Corte Suprema respondió:</p>
<h2 id="no.">No.</h2>
</section>
<section id="el-contexto-1" class="slide level1">
<h1>El contexto</h1>
<p>La causa se originó en un conflicto laboral.</p>
<p>El trabajador pretendía que la condena no alcanzara únicamente a la sociedad empleadora.</p>
<p>Solicitó también la responsabilidad personal de quienes integraban la sociedad.</p>
</section>
<section id="la-pretensión" class="slide level1">
<h1>La pretensión</h1>
<p>El actor sostuvo que correspondía aplicar:</p>
<ul>
<li>el artículo 54 LGS;</li>
<li>la doctrina del levantamiento del velo.</li>
</ul>
<p>De ese modo buscaba ejecutar el patrimonio personal de los socios.</p>
</section>
<section id="la-pregunta-jurídica" class="slide level1">
<h1>La pregunta jurídica</h1>
<p>¿Todo incumplimiento laboral permite prescindir de la personalidad jurídica?</p>
</section>
<section id="la-respuesta-de-la-corte" class="slide level1">
<h1>La respuesta de la Corte</h1>
<h2 id="no.-1">No.</h2>
<p>La personalidad jurídica continúa siendo la regla.</p>
<p>La desestimación constituye una excepción.</p>
</section>
<section id="primer-fundamento" class="slide level1">
<h1>Primer fundamento</h1>
<p>La Corte recuerda que</p>
<p>la sociedad constituye un sujeto de derecho diferente de sus socios.</p>
<p>No pueden confundirse ambos patrimonios.</p>
</section>
<section id="texto-del-precedente" class="slide level1">
<h1>Texto del precedente</h1>
<blockquote>
<p>“…no debe confundirse la personalidad de los socios y administradores con la de la sociedad…”</p>
</blockquote>
</section>
<section id="comentario-3" class="slide level1">
<h1>Comentario</h1>
<p>Este párrafo recupera uno de los principios fundamentales del Derecho Societario.</p>
<p>La existencia de una deuda social</p>
<p>no transforma automáticamente esa deuda</p>
<p>en una obligación personal de los socios.</p>
</section>
<section id="segunda-idea" class="slide level1">
<h1>Segunda idea</h1>
<p>La responsabilidad personal</p>
<p>no nace por el simple hecho de integrar una sociedad.</p>
<p>Debe acreditarse algo más.</p>
</section>
<section id="qué-exige-la-corte" class="slide level1">
<h1>¿Qué exige la Corte?</h1>
<p>La utilización abusiva de la personalidad jurídica.</p>
<p>No basta:</p>
<ul>
<li>insolvencia;</li>
<li>incumplimiento;</li>
<li>falta de pago.</li>
</ul>
</section>
<section id="texto-2" class="slide level1">
<h1>Texto</h1>
<blockquote>
<p>“…la figura societaria ha sido utilizada como mero instrumento para la consecución de finalidades extrasocietarias…”</p>
</blockquote>
</section>
<section id="continúa-el-fallo" class="slide level1">
<h1>Continúa el fallo</h1>
<blockquote>
<p>“…o como mero recurso para violar la ley o el orden público o frustrar derechos de terceros.”</p>
</blockquote>
</section>
<section id="los-requisitos" class="slide level1">
<h1>Los requisitos</h1>
<p>La Corte exige acreditar:</p>
<ul>
<li>utilización instrumental de la sociedad;</li>
<li>finalidad extrasocietaria;</li>
<li>fraude;</li>
<li>violación de la ley;</li>
<li>frustración de derechos.</li>
</ul>
<p>No basta el simple incumplimiento contractual.</p>
</section>
<section id="el-verdadero-mensaje" class="slide level1">
<h1>El verdadero mensaje</h1>
<p>Palomeque no restringe el artículo 54.</p>
<p>Lo interpreta.</p>
<p>Recuerda que se trata de un remedio</p>
<p>absolutamente excepcional.</p>
</section>
<section id="error-frecuente" class="slide level1">
<h1>Error frecuente</h1>
<p>Muchos operadores jurídicos sostenían:</p>
<pre><code>Hay deuda
↓

Corre el velo</code></pre>
<p>Palomeque rechaza ese razonamiento.</p>
</section>
<section id="el-esquema-correcto" class="slide level1">
<h1>El esquema correcto</h1>
<pre><code>Hay deuda
↓

¿Existe fraude?

↓

SI
↓

Art. 54

↓

NO

↓

Se mantiene la personalidad jurídica.</code></pre>
</section>
<section id="el-fraude-1" class="slide level1">
<h1>El fraude</h1>
<p>La Corte exige algo cualitativamente distinto.</p>
<p>Debe demostrarse que la sociedad fue utilizada:</p>
<ul>
<li>como pantalla;</li>
<li>como instrumento;</li>
<li>como recurso fraudulento.</li>
</ul>
</section>
<section id="protección-del-tráfico" class="slide level1">
<h1>Protección del tráfico</h1>
<p>¿Por qué tanta prudencia?</p>
<p>Porque la personalidad jurídica protege:</p>
<ul>
<li>inversiones;</li>
<li>crédito;</li>
<li>seguridad jurídica;</li>
<li>previsibilidad.</li>
</ul>
</section>
<section id="el-riesgo-contrario" class="slide level1">
<h1>El riesgo contrario</h1>
<p>Si cualquier incumplimiento permitiera demandar a los socios,</p>
<p>desaparecería prácticamente la autonomía patrimonial.</p>
</section>
<section id="la-función-del-artículo-54" class="slide level1">
<h1>La función del artículo 54</h1>
<p>No fue pensado para sancionar todo incumplimiento.</p>
<p>Fue pensado para sancionar</p>
<p>el abuso de la personalidad jurídica.</p>
</section>
<section id="comparación-1" class="slide level1">
<h1>Comparación</h1>
<h2 id="swift-1">Swift</h2>
<p>Existe fraude.</p>
<p>↓</p>
<p>Se corre el velo.</p>
</section>
<section class="slide level1">

<h2 id="palomeque-1">Palomeque</h2>
<p>No se acredita fraude.</p>
<p>↓</p>
<p>La personalidad permanece incólume.</p>
</section>
<section id="el-equilibrio" class="slide level1">
<h1>El equilibrio</h1>
<p>Parke Davis enseña</p>
<p>que las formas jurídicas no son absolutas.</p>
<p>Swift enseña</p>
<p>que el fraude no merece protección.</p>
<p>Palomeque enseña</p>
<p>que tampoco puede destruirse la personalidad jurídica sin prueba suficiente.</p>
</section>
<section id="la-evolución-completa" class="slide level1">
<h1>La evolución completa</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Parke Davis&lt;br/&gt;Realidad económica"]

B["Swift&lt;br/&gt;Fraude"]

C["Art.54 LGS"]

D["Palomeque&lt;br/&gt;Aplicación restrictiva"]

E["Art.144 CCyC"]

A --&gt; B --&gt; C --&gt; D --&gt; E
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="artículo-144-ccyc" class="slide level1">
<h1>Artículo 144 CCyC</h1>
<p>El Código Civil y Comercial generalizó la solución.</p>
<p>Ya no se aplica únicamente a sociedades.</p>
<p>Comprende a todas las personas jurídicas privadas.</p>
</section>
<section id="requisitos-del-artículo-144" class="slide level1">
<h1>Requisitos del artículo 144</h1>
<p>La actuación debe:</p>
<ul>
<li>perseguir fines ajenos;</li>
<li>violar la ley;</li>
<li>violar el orden público;</li>
<li>violar la buena fe;</li>
<li>frustrar derechos.</li>
</ul>
<p>La consecuencia será la imputación directa a quienes hicieron posible ese accionar.</p>
</section>
<section id="qué-cambia-respecto-del-artículo-54" class="slide level1">
<h1>¿Qué cambia respecto del artículo 54?</h1>
<p>El fundamento permanece.</p>
<p>Lo que cambia</p>
<p>es el ámbito de aplicación.</p>
<p>El artículo 144 alcanza a todas las personas jurídicas privadas.</p>
</section>
<section id="cuadro-comparativo" class="slide level1">
<h1>Cuadro comparativo</h1>
<table class="caption-top">
<thead>
<tr class="header">
<th>Parke Davis</th>
<th>Swift</th>
<th>Palomeque</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tributario</td>
<td>Concursal</td>
<td>Laboral</td>
</tr>
<tr class="even">
<td>Realidad económica</td>
<td>Fraude societario</td>
<td>Excepcionalidad</td>
</tr>
<tr class="odd">
<td>Grupo empresario</td>
<td>Grupo empresario</td>
<td>Responsabilidad de socios</td>
</tr>
<tr class="even">
<td>Antecedente</td>
<td>Desarrollo</td>
<td>Límite</td>
</tr>
</tbody>
</table>
</section>
<section id="la-construcción-jurisprudencial" class="slide level1">
<h1>La construcción jurisprudencial</h1>
<p>No son fallos contradictorios.</p>
<p>Son etapas de una misma evolución.</p>
<p>Cada uno responde una pregunta distinta.</p>
</section>
<section id="cinco-ideas-para-recordar" class="slide level1 scrollable">
<h1>Cinco ideas para recordar</h1>
<ol type="1">
<li>La personalidad jurídica constituye la regla.</li>
<li>La realidad económica importa.</li>
<li>El fraude no merece tutela.</li>
<li>La inoponibilidad es excepcional.</li>
<li>El artículo 144 CCyC amplía el instituto a todas las personas jurídicas.</li>
</ol>
</section>
<section id="pregunta-de-examen-1" class="slide level1">
<h1>Pregunta de examen</h1>
<h2 id="qué-aporte-realiza-cada-fallo">¿Qué aporte realiza cada fallo?</h2>
<p><strong>Parke Davis</strong></p>
<p>Introduce el principio de realidad económica.</p>
<p><strong>Swift</strong></p>
<p>Construye la doctrina argentina de la inoponibilidad.</p>
<p><strong>Palomeque</strong></p>
<p>Fija los límites de aplicación del artículo 54.</p>
</section>
<section id="conclusión-final" class="slide level1">
<h1>Conclusión final</h1>
<p>La evolución jurisprudencial argentina demuestra que la personalidad jurídica constituye uno de los pilares del Derecho Privado.</p>
<p>Sin embargo,</p>
<p>cuando esa personalidad es utilizada como un instrumento para violar la ley, defraudar acreedores o frustrar derechos,</p>
<p>el ordenamiento permite prescindir excepcionalmente de ella.</p>
<p>Ese recorrido comienza con <strong>Parke Davis</strong>, se consolida con <strong>Swift</strong> y encuentra su límite en <strong>Palomeque</strong>.</p>
</section>
<section id="jurisprudencia" class="slide level1">
<h1>Jurisprudencia</h1>
</section>
<section id="boskoop-s.a.-s-quiebra-s-incidente-de-apelación" class="slide level1">
<h1>Boskoop S.A. s/ quiebra s/ incidente de apelación</h1>
<p><strong>CNCom., Sala A, 18 de abril de 2006</strong></p>
</section>
<section id="tema" class="slide level1">
<h1>Tema</h1>
<ul>
<li>Sociedades constituidas en el extranjero.</li>
<li>Artículos 118 y 124 de la Ley General de Sociedades.</li>
<li>Fraude a la ley.</li>
<li>Competencia concursal.</li>
</ul>
</section>
<section id="contexto" class="slide level1">
<h1>Contexto</h1>
<p>Boskoop S.A. era una sociedad constituida en la República Oriental del Uruguay.</p>
<p>Frente a un pedido de quiebra promovido en la República Argentina, la sociedad opuso excepción de incompetencia y sostuvo que, por haber sido constituida en Uruguay, debía intervenir la jurisdicción de ese país.</p>
</section>
<section id="planteo-de-la-sociedad" class="slide level1">
<h1>Planteo de la sociedad</h1>
<p>Boskoop sostuvo que:</p>
<ul>
<li>había sido válidamente constituida en Uruguay;</li>
<li>tenía domicilio en ese país;</li>
<li>no correspondía la competencia de los tribunales argentinos;</li>
<li>su actuación en Argentina no justificaba la aplicación del derecho societario argentino.</li>
</ul>
</section>
<section id="la-controversia" class="slide level1">
<h1>La controversia</h1>
<p>El tribunal debía determinar si Boskoop era:</p>
<ul>
<li>una verdadera sociedad constituida en el extranjero comprendida en el artículo 118 LGS;</li>
</ul>
<p>o bien,</p>
<ul>
<li>una sociedad alcanzada por el supuesto excepcional previsto en el artículo 124 LGS.</li>
</ul>
</section>
<section id="hechos-relevantes" class="slide level1">
<h1>Hechos relevantes</h1>
<p>La Cámara verificó que:</p>
<ul>
<li>Boskoop no acreditó desarrollar actividad económica efectiva en Uruguay;</li>
<li>su principal activo era un inmueble ubicado en la Ciudad Autónoma de Buenos Aires;</li>
<li>dicho inmueble era explotado comercialmente en Argentina como playa de estacionamiento y garaje.</li>
</ul>
</section>
<section id="la-cuestión-jurídica-1" class="slide level1">
<h1>La cuestión jurídica</h1>
<p>¿Basta el lugar de constitución para considerar extranjera a una sociedad?</p>
<p>La Cámara respondió que no.</p>
<p>Además del lugar de constitución debía analizarse la realidad de su funcionamiento.</p>
</section>
<section id="fundamentos" class="slide level1">
<h1>Fundamentos</h1>
<p>El tribunal sostuvo que debía atenderse especialmente a:</p>
<ul>
<li>la sede efectiva de la sociedad;</li>
<li>el lugar donde desarrollaba su actividad principal;</li>
<li>la finalidad perseguida por la constitución en el extranjero.</li>
</ul>
<p>La realidad económica prevalecía sobre el mero dato formal de la constitución.</p>
</section>
<section id="aplicación-del-artículo-124-lgs" class="slide level1">
<h1>Aplicación del artículo 124 LGS</h1>
<p>La Cámara entendió que Boskoop encuadraba en el supuesto previsto por el artículo 124 de la Ley General de Sociedades.</p>
<p>En consecuencia,</p>
<p>debía ser considerada <strong>sociedad local a los efectos del cumplimiento de las formalidades de constitución, de su reforma y del contralor de funcionamiento</strong>, conforme al régimen previsto por la Ley General de Sociedades.</p>
</section>
<section id="consecuencia" class="slide level1">
<h1>Consecuencia</h1>
<p>El tribunal concluyó que el caso no quedaba comprendido en el régimen general del artículo 118 LGS.</p>
<p>Al resultar aplicable el artículo 124, la sociedad debía someterse al régimen previsto para las sociedades locales.</p>
<p>En consecuencia,</p>
<p>la quiebra debía tramitar ante la jurisdicción argentina.</p>
</section>
<section id="doctrina-del-fallo" class="slide level1">
<h1>Doctrina del fallo</h1>
<p>La doctrina considera que el artículo 124 constituye un mecanismo destinado a evitar el fraude a la ley mediante la utilización instrumental de sociedades constituidas en el extranjero.</p>
<p>No basta la constitución formal fuera del país.</p>
<p>Debe analizarse dónde funciona realmente la sociedad.</p>
</section>
<section id="artículo-118-vs.-artículo-124" class="slide level1">
<h1>Artículo 118 vs.&nbsp;Artículo 124</h1>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Artículo 118 LGS</th>
<th>Artículo 124 LGS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sociedad verdaderamente constituida y organizada en el extranjero</td>
<td>Sociedad constituida en el extranjero cuya sede o principal objeto se encuentra en la República</td>
</tr>
<tr class="even">
<td>Reconoce su actuación en Argentina</td>
<td>Somete a la sociedad al régimen previsto para las sociedades locales</td>
</tr>
<tr class="odd">
<td>Regla general</td>
<td>Excepción</td>
</tr>
</tbody>
</table>
</section>
<section id="enseñanza-del-precedente" class="slide level1">
<h1>Enseñanza del precedente</h1>
<p>Boskoop demuestra que la constitución en el extranjero no resulta suficiente para excluir la aplicación del derecho societario argentino.</p>
<p>Cuando la sede efectiva o el principal objeto de la sociedad se encuentran en la República,</p>
<p>resulta aplicable el artículo 124 de la Ley General de Sociedades.</p>
</section>
<section id="importancia" class="slide level1">
<h1>Importancia</h1>
<p>Boskoop constituye uno de los principales precedentes sobre la aplicación práctica del artículo 124 LGS.</p>
<p>El fallo reafirma que la realidad económica prevalece sobre la mera apariencia formal cuando se pretende utilizar una sociedad extranjera para desarrollar exclusivamente actividad en Argentina.</p>
</section>
<section id="idea-central" class="slide level1">
<h1>Idea central</h1>
<blockquote>
<p><strong>El artículo 118 facilita la actuación en Argentina de las verdaderas sociedades extranjeras.</strong></p>
</blockquote>
<blockquote>
<p><strong>El artículo 124 impide que la constitución formal en el extranjero sea utilizada para eludir la aplicación del derecho societario argentino cuando la sociedad desarrolla en la República su sede efectiva o su principal objeto.</strong></p>
</blockquote>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 960,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 8.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiado");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiado");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>