<!DOCTYPE html>
<html lang="es"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Prof.&nbsp;Maximiliano Lucas Romei">
  <title>Sociedades Civiles y Comerciales – Clase 3 — Constitución, iter societatis y sociedades informales</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-0427d8d92a431aa6a6430e53ec02a470.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
  <script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
  <link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Clase 3 — Constitución, iter societatis y sociedades informales</h1>
  <p class="subtitle">Sociedades Civiles y Comerciales · UBA · Curso intensivo 2026</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Maximiliano Lucas Romei 
</div>
</div>
</div>

</section>
<section id="clase-3" class="slide level1">
<h1>Clase 3</h1>
<h2 id="constitución-de-la-sociedad">Constitución de la sociedad</h2>
<p><strong>Ley General de Sociedades</strong></p>
<p><strong>Bibliografía base</strong></p>
<ul>
<li>Daniel R. Vítolo, <em>Manual de Sociedades</em> (2023).</li>
<li>Ricardo A. Nissen, <em>Curso de Derecho Societario</em> (2019).</li>
</ul>
</section>
<section id="constitución-de-la-sociedad-1" class="slide level1">
<h1>Constitución de la sociedad</h1>
<h2 id="del-concepto-al-nacimiento-de-la-persona-jurídica">Del concepto al nacimiento de la persona jurídica</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Clase 2&lt;br/&gt;¿Qué es una sociedad?"]
--&gt; B["Clase 3&lt;br/&gt;¿Cómo nace una sociedad?"]

B --&gt; C["Acto constitutivo"]

C --&gt; D["Inscripción"]

D --&gt; E["Persona jurídica plenamente constituida"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>En la clase anterior estudiamos el <strong>concepto de sociedad</strong> y su naturaleza jurídica. A partir de esta clase nos ocuparemos del <strong>proceso de constitución</strong>, es decir, del conjunto de actos necesarios para que la sociedad nazca como sujeto de derecho.</p>
<p>El análisis seguirá el orden de la <strong>Ley General de Sociedades</strong>, comenzando por el acto constitutivo y concluyendo con el régimen de las sociedades comprendidas en la Sección IV.</p>
</section>
<section id="hoja-de-ruta-de-la-clase" class="slide level1">
<h1>Hoja de ruta de la clase</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Acto constitutivo"]
B["Elementos generales"]
C["Elementos específicos"]
D["Contenido del instrumento (art. 11)"]
E["Iter societatis"]
F["Inscripción registral"]
G["Sociedades de la Sección IV"]

A --&gt; B
B --&gt; C
C --&gt; D
D --&gt; E
E --&gt; F
F --&gt; G
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Todo el régimen gira alrededor de una pregunta:</p>
<blockquote>
<p><strong>¿Qué requisitos exige el ordenamiento para que una sociedad quede regularmente constituida?</strong></p>
</blockquote>
</section>
<section id="el-nacimiento-de-la-sociedad" class="slide level1">
<h1>El nacimiento de la sociedad</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Voluntad de los constituyentes"]

--&gt; B["Acto constitutivo"]

--&gt; C["Instrumento"]

--&gt; D["Inscripción"]

--&gt; E["Sociedad regularmente constituida"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El nacimiento de una sociedad no depende exclusivamente del acuerdo de voluntades.</p>
<p>La constitución exige una sucesión de actos jurídicos regulados por la Ley General de Sociedades, algunos de naturaleza privada y otros sometidos al control del Registro Público.</p>
</section>
<section id="punto-de-partida-normativo" class="slide level1">
<h1>Punto de partida normativo</h1>
<h2 id="artículos-1-a-11-lgs">Artículos 1 a 11 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Arts. 1-11))
    Acto constitutivo
    Capacidad
    Forma
    Instrumento
    Inscripción
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Los primeros artículos de la Ley General de Sociedades regulan el proceso constitutivo.</p>
<p>Su estudio resulta indispensable para comprender cómo nace la personalidad jurídica societaria.</p>
</section>
<section id="el-acto-constitutivo" class="slide level1">
<h1>El acto constitutivo</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Acto constitutivo"]

A --&gt; B["Contrato"]

A --&gt; C["Acto unilateral"]

B --&gt; D["Sociedades pluripersonales"]

C --&gt; E["Sociedad Anónima Unipersonal"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Luego de la reforma introducida por la Ley 26.994, el acto constitutivo puede revestir dos formas:</p>
<ul>
<li><strong>Contrato</strong>, cuando intervienen dos o más personas.</li>
<li><strong>Declaración unilateral de voluntad</strong>, exclusivamente en el supuesto de la Sociedad Anónima Unipersonal.</li>
</ul>
</section>
<section id="el-acto-constitutivo-y-sus-elementos" class="slide level1">
<h1>El acto constitutivo y sus elementos</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Acto constitutivo))
    Elementos generales
      Capacidad
      Consentimiento
      Objeto
      Causa
      Forma
    Elementos específicos
      Fondo común
      Aportes
      Utilidades y pérdidas
      Affectio societatis
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La doctrina distingue entre:</p>
<ul>
<li><strong>elementos generales</strong>, comunes a todo acto jurídico; y</li>
<li><strong>elementos específicos</strong>, propios del contrato de sociedad.</li>
</ul>
<p>Esta clasificación será el eje de la primera parte de la clase.</p>
</section>
<section id="vítolo" class="slide level1">
<h1>Vítolo</h1>
<p>Vítolo explica que el acto constitutivo debe reunir, por un lado, los requisitos generales exigidos para todo acto jurídico y, por otro, los elementos específicos que caracterizan al contrato de sociedad como negocio jurídico de organización. :contentReference<span data-index="0">oaicite:0</span></p>
<p>Asimismo, destaca que la incorporación de la Sociedad Anónima Unipersonal no alteró la regla general según la cual la sociedad nace, normalmente, de un contrato celebrado entre dos o más personas. :contentReference<span data-index="1">oaicite:1</span></p>
</section>
<section id="nissen" class="slide level1">
<h1>Nissen</h1>
<p>Nissen parte de la naturaleza contractual de la sociedad y señala que el contrato societario comparte los elementos esenciales de los demás contratos, aunque presenta características propias derivadas de su finalidad organizativa y de la creación de un sujeto de derecho distinto de los socios. :contentReference<span data-index="2">oaicite:2</span></p>
</section>
<section id="objetivos-de-esta-unidad" class="slide level1">
<h1>Objetivos de esta unidad</h1>
<p>Al finalizar esta clase deberíamos poder:</p>
<ul>
<li>identificar los requisitos del acto constitutivo;</li>
<li>distinguir los elementos generales de los específicos;</li>
<li>interpretar los artículos 1 a 11 de la LGS;</li>
<li>comprender el proceso de inscripción;</li>
<li>analizar las consecuencias de la falta de inscripción y el régimen de la Sección IV.</li>
</ul>
</section>
<section id="comenzamos" class="slide level1">
<h1>Comenzamos</h1>
<h2 id="primera-parte">Primera parte</h2>
</section>
<section id="los-elementos-generales-del-acto-constitutivo" class="slide level1">
<h1>Los elementos generales del acto constitutivo</h1>
</section>
<section id="elementos-generales" class="slide level1">
<h1>Elementos generales</h1>
<h2 id="capacidad">Capacidad</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Capacidad))
    Regla general
    Art. 27
      Cónyuges
    Art. 28
      Menores
      Incapaces
      Capacidad restringida
    Art. 30
      Sociedad socia
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La capacidad constituye uno de los presupuestos de validez del acto constitutivo.</p>
<p>Como regla, se rige por las disposiciones generales del Código Civil y Comercial. Sin embargo, la Ley General de Sociedades contiene normas especiales que responden a las particularidades del fenómeno societario.</p>
</section>
<section id="la-regla-general" class="slide level1">
<h1>La regla general</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Código Civil y Comercial"]

--&gt; B["Capacidad para contratar"]

--&gt; C["Contrato de sociedad"]

--&gt; D["Ley General de Sociedades"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La LGS no regula integralmente la capacidad.</p>
<p>Por ello resultan aplicables las normas generales del Código Civil y Comercial, sin perjuicio de las disposiciones especiales previstas por la legislación societaria.</p>
<p><strong>Vítolo</strong> parte de este principio y luego analiza las excepciones expresamente contempladas por la ley. :contentReference<span data-index="0">oaicite:0</span></p>
</section>
<section id="las-reglas-especiales" class="slide level1">
<h1>Las reglas especiales</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Capacidad"]

A --&gt; B["Art. 27"]
A --&gt; C["Art. 28"]
A --&gt; D["Art. 30"]

B --&gt; E["Sociedades entre cónyuges"]

C --&gt; F["Menores e incapaces"]

D --&gt; G["Sociedad socia"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Las principales reglas especiales de la LGS se concentran en tres artículos.</p>
<p>Cada uno responde a una finalidad distinta de política legislativa.</p>
</section>
<section id="artículo-27" class="slide level1">
<h1>Artículo 27</h1>
<h2 id="sociedades-entre-cónyuges">Sociedades entre cónyuges</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Ley 19.550"]

--&gt; B["Régimen restrictivo"]

--&gt; C["Ley 26.994"]

--&gt; D["Sociedades de cualquier tipo"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El texto vigente dispone que:</p>
<blockquote>
<p><strong>“Los cónyuges pueden integrar entre sí sociedades de cualquier tipo.”</strong></p>
</blockquote>
<p>La reforma armonizó la LGS con el nuevo régimen patrimonial del Código Civil y Comercial.</p>
</section>
<section id="por-qué-cambió-el-régimen" class="slide level1">
<h1>¿Por qué cambió el régimen?</h1>
<p>La prohibición histórica encontraba fundamento en la antigua regulación patrimonial del matrimonio.</p>
<p>El Código Civil y Comercial modificó sustancialmente ese sistema, reconociendo mayor autonomía patrimonial a los cónyuges.</p>
<p>Por ello la reforma eliminó la limitación existente y permitió la constitución de sociedades de cualquier tipo entre esposos.</p>
<p><strong>Vítolo</strong> destaca que la modificación responde a la necesaria adecuación de la LGS al nuevo derecho de familia. :contentReference<span data-index="1">oaicite:1</span></p>
</section>
<section id="artículo-28" class="slide level1">
<h1>Artículo 28</h1>
<h2 id="menores-incapaces-y-personas-con-capacidad-restringida">Menores, incapaces y personas con capacidad restringida</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Indivisión hereditaria"]

--&gt; B["Constitución de sociedad"]

--&gt; C["Intervienen menores o personas con capacidad restringida"]

--&gt; D["Sólo responsabilidad limitada"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El artículo 28 no regula la constitución ordinaria de sociedades.</p>
<p>Contempla un supuesto excepcional vinculado con la continuación de una explotación económica integrada por bienes sometidos a indivisión hereditaria.</p>
</section>
<section id="finalidad-del-artículo-28" class="slide level1">
<h1>Finalidad del artículo 28</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Art. 28))
    Protección patrimonial
    Control judicial
    Responsabilidad limitada
    Continuidad de la empresa
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La finalidad de la norma consiste en compatibilizar:</p>
<ul>
<li>la continuidad de la actividad económica;</li>
<li>con la tutela patrimonial de los menores y demás personas especialmente protegidas.</li>
</ul>
</section>
<section id="artículo-30" class="slide level1">
<h1>Artículo 30</h1>
<h2 id="sociedad-socia">Sociedad socia</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["SA"]

B["SCA"]

A --&gt; C["Sólo pueden integrar"]

B --&gt; C

C --&gt; D["Sociedades por acciones"]

C --&gt; E["SRL"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El artículo 30 limita la participación de las sociedades anónimas y de las sociedades en comandita por acciones en otras sociedades.</p>
<p>La restricción constituye una de las normas clásicas del derecho societario argentino.</p>
</section>
<section id="fundamento-del-artículo-30" class="slide level1">
<h1>Fundamento del artículo 30</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Art.30))
    Transparencia
    Control
    Protección de acreedores
    Evitar estructuras opacas
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Para <strong>Nissen</strong>, estas limitaciones procuran preservar la transparencia patrimonial y evitar estructuras societarias excesivamente complejas que dificulten el control y la protección de terceros. :contentReference<span data-index="2">oaicite:2</span></p>
<p>Vítolo analiza la evolución de la norma y su ámbito de aplicación luego de las reformas introducidas por la Ley 26.994. :contentReference<span data-index="3">oaicite:3</span></p>
</section>
<section id="síntesis" class="slide level1">
<h1>Síntesis</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Capacidad"]

--&gt; B["Regla general: CCyC"]

B --&gt; C["Excepciones LGS"]

C --&gt; D["Art. 27"]

C --&gt; E["Art. 28"]

C --&gt; F["Art. 30"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La capacidad constituye el primer presupuesto de validez del acto constitutivo.</p>
<p>Como regla se aplica el Código Civil y Comercial; las excepciones previstas por la LGS responden a razones específicas de protección, transparencia y política legislativa.</p>
</section>
<section id="jurisprudencia" class="slide level1">
<h1>Jurisprudencia</h1>
<h2 id="el-origen-del-artículo-30-lgs">El origen del artículo 30 LGS</h2>
<p><strong>CSJN, “Gobierno Nacional c.&nbsp;Cía. Ferrocarrilera de Petróleo” (30/7/1948)</strong></p>
<p>Este fallo constituye el antecedente histórico más importante del actual artículo 30 de la Ley General de Sociedades.</p>
<p>Tanto Halperín como Nissen destacan su influencia en la solución adoptada luego por la ley 19.550. :contentReference<span data-index="0">oaicite:0</span></p>
</section>
<section id="el-contexto-histórico" class="slide level1">
<h1>El contexto histórico</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">timeline
    title Evolución del régimen

    1948 : Fallo "Gobierno Nacional"
    1972 : Ley 19.550
    2015 : Reforma Ley 26.994
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El caso fue resuelto muchos años antes de la sanción de la Ley General de Sociedades.</p>
<p>Sin embargo, la solución adoptada por la Corte terminó siendo receptada por el legislador.</p>
</section>
<section id="el-problema-jurídico" class="slide level1">
<h1>El problema jurídico</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Sociedad Anónima"]

--&gt; B["Pretende integrar"]

--&gt; C["Sociedad Colectiva"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La cuestión consistía en determinar si una sociedad anónima podía integrar una sociedad colectiva.</p>
</section>
<section id="qué-resolvió-la-corte" class="slide level1">
<h1>¿Qué resolvió la Corte?</h1>
<p>La Corte Suprema sostuvo que:</p>
<ul>
<li>la sociedad anónima <strong>no podía integrar una sociedad colectiva</strong>;</li>
<li>la naturaleza de ambos tipos societarios era incompatible.</li>
</ul>
<p>Ese criterio fue luego incorporado por la legislación societaria. :contentReference<span data-index="1">oaicite:1</span></p>
</section>
<section id="fundamento-principal" class="slide level1">
<h1>Fundamento principal</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Sociedad colectiva"]

--&gt; B["Intuitu personae"]

--&gt; C["Responsabilidad personal"]

--&gt; D["Incompatibilidad con la SA"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La Corte entendió que la sociedad colectiva se estructura sobre la confianza personal existente entre los socios.</p>
<p>Ese elemento no resultaba compatible con la participación de una sociedad anónima.</p>
</section>
<section id="recepción-legislativa" class="slide level1">
<h1>Recepción legislativa</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Fallo 1948"]

--&gt; B["Halperín"]

--&gt; C["Ley 19.550"]

--&gt; D["Artículo 30"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Nissen explica que el criterio jurisprudencial fue asumido por los redactores de la Ley 19.550, especialmente por Isaac Halperín, quien defendía esta limitación como mecanismo de protección del sistema societario. :contentReference<span data-index="2">oaicite:2</span></p>
</section>
<section id="cuál-era-la-justificación" class="slide level1">
<h1>¿Cuál era la justificación?</h1>
<p>Según la explicación tradicional:</p>
<ul>
<li>evitar que la SA eludiera el control estatal;</li>
<li>impedir que asumiera responsabilidades ilimitadas propias de una sociedad de personas;</li>
<li>preservar la naturaleza intuitu personae de la sociedad colectiva. :contentReference<span data-index="3">oaicite:3</span></li>
</ul>
</section>
<section id="la-crítica-de-nissen" class="slide level1">
<h1>La crítica de Nissen</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Críticas))
    Riesgo exagerado
    Control estatal insuficiente
    Fundamentos históricos debilitados
    Necesidad de reforma
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Nissen afirma que esos fundamentos fueron ampliamente cuestionados por la doctrina y que existe un consenso importante favorable a la reforma o incluso a la derogación del artículo 30. :contentReference<span data-index="4">oaicite:4</span></p>
</section>
<section id="situación-actual" class="slide level1">
<h1>Situación actual</h1>
<p>Hoy el artículo 30 mantiene una restricción, aunque menos severa que la originaria.</p>
<p>La Ley 26.994 amplió la capacidad de las sociedades anónimas permitiendo su participación en sociedades de responsabilidad limitada, además de las sociedades por acciones. :contentReference<span data-index="5">oaicite:5</span></p>
</section>
<section id="por-qué-seguimos-estudiando-este-fallo" class="slide level1">
<h1>¿Por qué seguimos estudiando este fallo?</h1>
<p>Porque permite comprender que:</p>
<ul>
<li>muchas normas societarias tienen origen jurisprudencial;</li>
<li>el artículo 30 no surgió aisladamente, sino como recepción de una construcción previa;</li>
<li>conocer el fundamento histórico ayuda también a comprender las críticas contemporáneas.</li>
</ul>
<blockquote>
<p><strong>No estudiamos este fallo por su aplicación práctica actual, sino porque explica el origen y la evolución del régimen legal vigente.</strong></p>
</blockquote>
</section>
<section id="elementos-generales-del-acto-constitutivo" class="slide level1">
<h1>Elementos generales del acto constitutivo</h1>
<h2 id="consentimiento-objeto-causa-y-forma">Consentimiento, objeto, causa y forma</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Elementos generales))
    Consentimiento
    Objeto
    Causa
    Forma
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Una vez verificada la capacidad de los constituyentes, corresponde analizar los restantes elementos generales del acto constitutivo.</p>
<p>La Ley General de Sociedades no regula exhaustivamente estos requisitos, por lo que deben integrarse con las disposiciones del Código Civil y Comercial relativas a los actos jurídicos y a los contratos.</p>
<p>Vítolo y Nissen coinciden en que el contrato de sociedad participa de la teoría general del contrato, aunque presenta particularidades derivadas de su función organizativa. :contentReference<span data-index="0">oaicite:0</span> :contentReference<span data-index="1">oaicite:1</span></p>
</section>
<section id="el-consentimiento" class="slide level1">
<h1>El consentimiento</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Oferta"]

--&gt; B["Aceptación"]

--&gt; C["Consentimiento"]

--&gt; D["Acto constitutivo"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El consentimiento consiste en el acuerdo de voluntades dirigido a crear una organización societaria.</p>
<p>Como regla, se rige por las normas generales del Código Civil y Comercial sobre formación del consentimiento y vicios de la voluntad.</p>
<p>La principal particularidad aparece en la <strong>Sociedad Anónima Unipersonal</strong>, donde el acto constitutivo deja de ser un contrato para convertirse en una declaración unilateral de voluntad, cuestión ya estudiada en la clase anterior.</p>
</section>
<section id="objeto-y-causa" class="slide level1">
<h1>Objeto y causa</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Objeto"]

--&gt; B["¿Qué hará la sociedad?"]

C["Causa"]

--&gt; D["¿Para qué se constituye?"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Estos conceptos suelen confundirse, pero cumplen funciones diferentes.</p>
<p><strong>Objeto social:</strong> determina la actividad que desarrollará la sociedad y constituye uno de los requisitos esenciales del instrumento constitutivo (art. 11, inc. 3°, LGS).</p>
<p><strong>Causa:</strong> refiere a la finalidad económico-social perseguida por los constituyentes mediante la organización común.</p>
<p>La doctrina coincide en que la licitud debe verificarse tanto respecto del objeto como de la causa. :contentReference<span data-index="2">oaicite:2</span> :contentReference<span data-index="3">oaicite:3</span></p>
</section>
<section id="el-objeto-social" class="slide level1">
<h1>El objeto social</h1>
<h2 id="artículo-11-inciso-3-lgs">Artículo 11 inciso 3° LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Objeto social))
    Preciso
    Determinado
    Lícito
    Posible
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La ley exige que el objeto sea <strong>preciso y determinado</strong>.</p>
<p>Esta exigencia no responde a una cuestión meramente formal.</p>
<p>Un objeto correctamente delimitado:</p>
<ul>
<li>fija el ámbito de actuación de los administradores;</li>
<li>facilita el control registral;</li>
<li>brinda información adecuada a los terceros;</li>
<li>delimita la actividad para la cual fue creada la sociedad.</li>
</ul>
<p>Por ello, las cláusulas excesivamente genéricas suelen ser observadas por la autoridad registral.</p>
</section>
<section id="la-forma" class="slide level1">
<h1>La forma</h1>
<h2 id="artículo-4-lgs">Artículo 4 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Acto constitutivo"]

--&gt; B["Instrumento público"]

--&gt; C["Instrumento privado"]

B --&gt; D["Presentación para inscripción"]

C --&gt; D
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Como regla, el contrato constitutivo puede otorgarse por instrumento público o privado.</p>
<p>La escritura pública sólo será exigible cuando una disposición legal específica o la naturaleza de los bienes aportados así lo requieran.</p>
<p>La forma del acto constitutivo no debe confundirse con la forma exigida para determinados aportes, especialmente los bienes registrables.</p>
</section>
<section id="doctrina" class="slide level1">
<h1>Doctrina</h1>
<h3 id="vítolo-1">Vítolo</h3>
<ul>
<li>El contrato de sociedad reúne los elementos generales propios de todo acto jurídico.</li>
<li>La LGS debe interpretarse conjuntamente con el Código Civil y Comercial.</li>
<li>El objeto social constituye uno de los aspectos centrales del control de legalidad efectuado por el Registro Público. :contentReference<span data-index="4">oaicite:4</span></li>
</ul>
<h3 id="nissen-1">Nissen</h3>
<ul>
<li>El consentimiento, el objeto, la causa y la forma continúan rigiéndose por la teoría general del contrato.</li>
<li>Las particularidades del contrato de sociedad no eliminan la aplicación de los principios generales del derecho contractual. :contentReference<span data-index="5">oaicite:5</span></li>
</ul>
</section>
<section id="síntesis-de-los-elementos-generales" class="slide level1">
<h1>Síntesis de los elementos generales</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Elementos generales"]

A --&gt; B["Capacidad"]

A --&gt; C["Consentimiento"]

A --&gt; D["Objeto"]

A --&gt; E["Causa"]

A --&gt; F["Forma"]

F --&gt; G["Acto constitutivo válido"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Con esto concluye el análisis de los <strong>elementos generales</strong>.</p>
<p>A continuación estudiaremos los <strong>elementos específicos</strong>, es decir, aquellos que distinguen al contrato de sociedad de cualquier otro contrato previsto por el ordenamiento jurídico.</p>
</section>
<section id="elementos-generales-del-acto-constitutivo-1" class="slide level1">
<h1>Elementos generales del acto constitutivo</h1>
<h2 id="arts.-1-4-11-13-18-19-y-20-lgs">Arts. 1, 4, 11, 13, 18, 19 y 20 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Elementos generales))
    Consentimiento
      Art. 1
    Objeto
      Art. 11 inc. 3
      Arts. 18 a 20
    Causa
      Art. 1
      Art. 13
    Forma
      Art. 4
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El acto constitutivo societario debe leerse desde la Ley General de Sociedades.</p>
<p>La teoría general del contrato completa el régimen, pero el punto de partida debe ser la LGS.</p>
</section>
<section id="consentimiento" class="slide level1">
<h1>Consentimiento</h1>
<h2 id="art.-1-lgs">Art. 1 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Una o más personas"]

--&gt; B["Se obligan a realizar aportes"]

--&gt; C["Acto constitutivo"]

--&gt; D["Sociedad"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El consentimiento aparece en el art. 1 cuando la ley describe a quienes se obligan a realizar aportes para aplicarlos a una actividad común.</p>
<p>En las sociedades pluripersonales existe contrato.</p>
<p>En la SAU, el consentimiento plural es reemplazado por la declaración unilateral de voluntad.</p>
<p>Nissen señala que el consentimiento se rige por los principios generales de los actos jurídicos y contratos, aunque identifica supuestos especiales de incorporación societaria no plenamente voluntaria. :contentReference<span data-index="0">oaicite:0</span></p>
</section>
<section id="objeto-social" class="slide level1">
<h1>Objeto social</h1>
<h2 id="art.-11-inc.-3-lgs">Art. 11 inc. 3 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Objeto social))
    Preciso
    Determinado
    Lícito
    Posible
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El instrumento constitutivo debe contener la designación del objeto social.</p>
<p>La ley exige que sea <strong>preciso y determinado</strong>.</p>
<p>El objeto social delimita la actividad que la sociedad podrá desarrollar y cumple una función relevante frente a socios, administradores, terceros y Registro Público.</p>
</section>
<section id="objeto-ilícito-actividad-ilícita-y-objeto-prohibido" class="slide level1">
<h1>Objeto ilícito, actividad ilícita y objeto prohibido</h1>
<h2 id="arts.-18-19-y-20-lgs">Arts. 18, 19 y 20 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Objeto o actividad"]

A --&gt; B["Objeto ilícito&lt;br/&gt;Art. 18"]

A --&gt; C["Actividad ilícita&lt;br/&gt;Art. 19"]

A --&gt; D["Objeto prohibido&lt;br/&gt;Art. 20"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La licitud del objeto no es una cuestión meramente formal.</p>
<p>La LGS distingue entre:</p>
<ul>
<li>sociedad de objeto ilícito;</li>
<li>sociedad de objeto lícito con actividad ilícita;</li>
<li>sociedad de objeto prohibido en razón del tipo.</li>
</ul>
<p>Esta distinción será retomada al estudiar nulidades societarias.</p>
</section>
<section id="causa" class="slide level1">
<h1>Causa</h1>
<h2 id="art.-1-lgs-1">Art. 1 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Aportes"]

--&gt; B["Producción o intercambio de bienes o servicios"]

--&gt; C["Beneficios"]

--&gt; D["Pérdidas"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La causa del contrato de sociedad se vincula con la finalidad económica común.</p>
<p>El art. 1 muestra esa finalidad: los socios organizan aportes para una actividad común, participando en beneficios y soportando pérdidas.</p>
<p>Nissen vincula la causa con la obtención de beneficios mediante una actividad económica organizada. :contentReference<span data-index="1">oaicite:1</span></p>
</section>
<section id="cláusulas-leoninas" class="slide level1">
<h1>Cláusulas leoninas</h1>
<h2 id="art.-13-lgs">Art. 13 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Contrato de sociedad"]

--&gt; B["Participación en ganancias"]

--&gt; C["Participación en pérdidas"]

D["Exclusión absoluta"]

--&gt; E["Cláusula nula&lt;br/&gt;Art. 13 LGS"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La causa societaria se desnaturaliza si se excluye absolutamente a un socio de las ganancias o de las pérdidas.</p>
<p>Por eso el art. 13 declara nulas determinadas estipulaciones incompatibles con la esencia del contrato social.</p>
</section>
<section id="forma" class="slide level1">
<h1>Forma</h1>
<h2 id="art.-4-lgs">Art. 4 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Contrato constitutivo o modificatorio"]

A --&gt; B["Instrumento público"]

A --&gt; C["Instrumento privado"]

B --&gt; D["Inscripción"]

C --&gt; D
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El art. 4 establece que el contrato constitutivo o sus modificaciones deben otorgarse por instrumento público o privado.</p>
<p>La forma del contrato no debe confundirse con la forma exigida para ciertos aportes, especialmente cuando se aportan bienes registrables.</p>
</section>
<section id="vítolo-y-nissen" class="slide level1">
<h1>Vítolo y Nissen</h1>
<p>Vítolo trabaja estos elementos partiendo de la LGS y completando con el régimen general del Código Civil y Comercial, especialmente en materia de capacidad, consentimiento, objeto, causa y forma. :contentReference<span data-index="2">oaicite:2</span></p>
<p>Nissen sostiene que el contrato de sociedad debe reunir los elementos comunes a todo contrato —consentimiento, capacidad, objeto y causa—, sin perjuicio de sus notas específicas como contrato plurilateral de organización. :contentReference<span data-index="3">oaicite:3</span></p>
</section>
<section id="síntesis-normativa" class="slide level1">
<h1>Síntesis normativa</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Acto constitutivo"]

A --&gt; B["Art. 1&lt;br/&gt;Concepto y causa societaria"]

A --&gt; C["Art. 4&lt;br/&gt;Forma"]

A --&gt; D["Art. 11 inc. 3&lt;br/&gt;Objeto social"]

A --&gt; E["Art. 13&lt;br/&gt;Cláusulas prohibidas"]

A --&gt; F["Arts. 18 a 20&lt;br/&gt;Ilicitud y objeto prohibido"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Con esto cerramos los elementos generales.</p>
<p>Seguimos con los elementos específicos del contrato de sociedad.</p>
</section>
<section id="elementos-específicos-del-contrato-de-sociedad" class="slide level1">
<h1>Elementos específicos del contrato de sociedad</h1>
<h2 id="artículo-1-lgs">Artículo 1 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Art. 1 LGS))
    Aportes
    Fondo común
    Actividad organizada
    Beneficios
    Pérdidas
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>A diferencia de los elementos generales, los elementos específicos son aquellos que caracterizan exclusivamente al contrato de sociedad.</p>
<p>Surgen principalmente del artículo 1 de la Ley General de Sociedades y permiten distinguir este contrato de cualquier otro contrato plurilateral.</p>
<p>Vítolo y Nissen coinciden en que estos elementos son los que otorgan identidad propia al fenómeno societario. :contentReference<span data-index="0">oaicite:0</span> :contentReference<span data-index="1">oaicite:1</span></p>
</section>
<section id="el-fondo-común" class="slide level1">
<h1>El fondo común</h1>
<h2 id="art.-1-lgs-2">Art. 1 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Socios"]

--&gt; B["Aportes"]

--&gt; C["Fondo común"]

--&gt; D["Actividad económica"]

--&gt; E["Resultados"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El artículo 1 exige que los socios se obliguen a realizar aportes.</p>
<p>Esos aportes no permanecen aislados sino que confluyen en un patrimonio destinado al desarrollo de la actividad social.</p>
<p>La doctrina denomina a ese patrimonio inicial <strong>fondo común</strong>.</p>
</section>
<section id="fondo-común-capital-y-patrimonio" class="slide level1">
<h1>Fondo común, capital y patrimonio</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Aportes"]

--&gt; B["Fondo común"]

B --&gt; C["Capital social"]

B --&gt; D["Patrimonio social"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Estos conceptos no son equivalentes.</p>
<ul>
<li><strong>Fondo común:</strong> bienes aportados para iniciar la actividad.</li>
<li><strong>Capital social:</strong> cifra jurídica prevista en el contrato.</li>
<li><strong>Patrimonio:</strong> conjunto de bienes, derechos y obligaciones de la sociedad en cada momento de su existencia.</li>
</ul>
<p>Vítolo dedica especial atención a esta diferenciación, por las frecuentes confusiones que genera en la práctica. :contentReference<span data-index="2">oaicite:2</span></p>
</section>
<section id="los-aportes" class="slide level1">
<h1>Los aportes</h1>
<h2 id="art.-1-lgs-3">Art. 1 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Aportes))
    Dinero
    Bienes
    Derechos
    Créditos
    Industria
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El aporte constituye la obligación principal del socio.</p>
<p>No existe contrato de sociedad sin aportes.</p>
<p>La naturaleza del aporte dependerá del tipo societario y de las disposiciones específicas que regulan cada una de las formas sociales.</p>
</section>
<section id="funciones-del-aporte" class="slide level1">
<h1>Funciones del aporte</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Aporte"]

--&gt; B["Forma el fondo común"]

B --&gt; C["Integra el patrimonio"]

C --&gt; D["Permite desarrollar el objeto social"]

D --&gt; E["Genera beneficios o pérdidas"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El aporte cumple simultáneamente una función:</p>
<ul>
<li>económica;</li>
<li>organizativa;</li>
<li>patrimonial;</li>
<li>de garantía frente a terceros.</li>
</ul>
<p>Por ello constituye uno de los ejes estructurales del derecho societario.</p>
</section>
<section id="participación-en-utilidades-y-pérdidas" class="slide level1">
<h1>Participación en utilidades y pérdidas</h1>
<h2 id="art.-1-lgs-4">Art. 1 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Actividad social"]

--&gt; B["Resultado"]

B --&gt; C["Utilidades"]

B --&gt; D["Pérdidas"]

C --&gt; E["Participación de los socios"]

D --&gt; E
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El artículo 1 dispone expresamente que los socios participan de los beneficios y soportan las pérdidas.</p>
<p>No se trata de una cláusula accesoria.</p>
<p>Es una consecuencia necesaria de la organización societaria.</p>
</section>
<section id="utilidad-y-dividendo" class="slide level1">
<h1>Utilidad y dividendo</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Resultado positivo"]

--&gt; B["Utilidad"]

--&gt; C["Aprobación de estados contables"]

--&gt; D["Decisión de distribuir"]

--&gt; E["Dividendo"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La utilidad y el dividendo no son sinónimos.</p>
<p>La utilidad es un resultado económico.</p>
<p>El dividendo constituye el crédito que nace a favor del socio cuando el órgano competente aprueba su distribución.</p>
<p>Vítolo y Nissen desarrollan expresamente esta distinción. :contentReference<span data-index="3">oaicite:3</span> :contentReference<span data-index="4">oaicite:4</span></p>
</section>
<section id="y-la-affectio-societatis" class="slide level1">
<h1>¿Y la <em>affectio societatis</em>?</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Affectio societatis))
    Colaboración
    Organización común
    Interés compartido
    Fin común
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La doctrina clásica incorporó la <em>affectio societatis</em> como uno de los elementos característicos del contrato de sociedad.</p>
<p>Sin embargo, su verdadera naturaleza ha sido objeto de un intenso debate doctrinario.</p>
<p>¿Es un requisito esencial del contrato?</p>
<p>¿O simplemente una consecuencia de la celebración del contrato social?</p>
<p>Ese interrogante merece un tratamiento específico.</p>
</section>
<section id="transición" class="slide level1">
<h1>Transición</h1>
<p>Hasta aquí hemos analizado los elementos específicos previstos por el artículo 1 de la LGS.</p>
<p>El siguiente tema estará dedicado exclusivamente a la <strong>affectio societatis</strong>, uno de los conceptos más discutidos del Derecho Societario argentino y sobre el cual Vítolo y Nissen adoptan posiciones que vale la pena comparar.</p>
</section>
<section id="affectio-societatis" class="slide level1">
<h1>Affectio societatis</h1>
<h2 id="un-elemento-esencial-del-contrato-de-sociedad">¿Un elemento esencial del contrato de sociedad?</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Affectio societatis))
    Colaboración
    Organización común
    Interés compartido
    Fin social
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La <em>affectio societatis</em> es uno de los conceptos más tradicionales del Derecho Societario.</p>
<p>Sin embargo, no aparece mencionada expresamente en la Ley General de Sociedades.</p>
<p>Su reconocimiento es esencialmente doctrinario y jurisprudencial.</p>
</section>
<section id="qué-significa" class="slide level1">
<h1>¿Qué significa?</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Pluralidad de personas"]

--&gt; B["Voluntad de colaborar"]

--&gt; C["Organización común"]

--&gt; D["Obtención del fin social"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La expresión <em>affectio societatis</em> alude a la voluntad permanente de los socios de colaborar en pie de igualdad para alcanzar el objeto común de la sociedad.</p>
<p>No se identifica con la simple intención de contratar.</p>
<p>Supone una verdadera vocación asociativa.</p>
</section>
<section id="dónde-está-en-la-ley" class="slide level1">
<h1>¿Dónde está en la ley?</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Ley General de Sociedades"]

--&gt; B["No menciona la affectio societatis"]

A --&gt; C["Art. 1"]

C --&gt; D["Organización común"]

C --&gt; E["Aportes"]

C --&gt; F["Participación en beneficios y pérdidas"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La LGS no utiliza la expresión <em>affectio societatis</em>.</p>
<p>Quienes sostienen su vigencia entienden que surge implícitamente del artículo 1 y de la propia estructura del contrato societario.</p>
</section>
<section id="la-doctrina-clásica" class="slide level1">
<h1>La doctrina clásica</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Doctrina clásica))
    Halperín
    Nissen
    Vítolo
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Tradicionalmente se entendió que la <em>affectio societatis</em> diferenciaba al contrato de sociedad de otros contratos de colaboración o de cambio.</p>
<p>Su función era explicar la existencia de un interés común y de una organización compartida.</p>
</section>
<section id="la-posición-de-nissen" class="slide level1">
<h1>La posición de Nissen</h1>
<p>Nissen sostiene que la <em>affectio societatis</em> constituye uno de los elementos específicos del contrato de sociedad.</p>
<p>La define como la voluntad de los socios de colaborar activamente para la consecución del fin común, aceptando los riesgos propios de la empresa y subordinando el interés individual al interés social. :contentReference<span data-index="0">oaicite:0</span></p>
<p>Para Nissen, esta nota permite distinguir la sociedad de otras relaciones jurídicas que también persiguen un resultado económico.</p>
</section>
<section id="la-posición-de-vítolo" class="slide level1">
<h1>La posición de Vítolo</h1>
<p>Vítolo reconoce la importancia histórica del concepto, pero advierte que no constituye un requisito autónomo expresamente previsto por la ley.</p>
<p>Entiende que muchas de las funciones tradicionalmente atribuidas a la <em>affectio societatis</em> pueden explicarse mediante otros institutos, como la buena fe, el deber de lealtad y la organización prevista en el artículo 1 de la LGS. :contentReference<span data-index="1">oaicite:1</span></p>
</section>
<section id="es-un-elemento-esencial" class="slide level1">
<h1>¿Es un elemento esencial?</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Posición tradicional"]

--&gt; B["Sí"]

A --&gt; C["No"]

B --&gt; D["Elemento esencial"]

C --&gt; E["Concepto doctrinario útil, pero no autónomo"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Actualmente existen dos grandes posiciones doctrinarias:</p>
<ul>
<li>quienes consideran que integra la esencia del contrato de sociedad;</li>
<li>quienes entienden que se trata de una construcción doctrinaria sin autonomía normativa.</li>
</ul>
</section>
<section id="utilidad-práctica" class="slide level1">
<h1>Utilidad práctica</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Aplicaciones))
    Interpretación del contrato
    Conflictos entre socios
    Exclusión
    Abuso de mayoría
    Deber de lealtad
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Aun quienes relativizan su carácter esencial reconocen que la <em>affectio societatis</em> continúa siendo una herramienta útil para interpretar conflictos internos y valorar la conducta de los socios.</p>
</section>
<section id="jurisprudencia-1" class="slide level1">
<h1>Jurisprudencia</h1>
<p>La jurisprudencia argentina ha recurrido frecuentemente a la <em>affectio societatis</em> para resolver conflictos entre socios, especialmente en materia de exclusión, paralización de órganos sociales y abuso de mayoría.</p>
<p>Sin embargo, la tendencia más reciente consiste en fundamentar esas soluciones directamente en la Ley General de Sociedades y en el principio de buena fe, antes que en una noción abstracta de <em>affectio societatis</em>.</p>
</section>
<section id="conclusión" class="slide level1">
<h1>Conclusión</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Affectio societatis"]

--&gt; B["Concepto clásico"]

--&gt; C["Discusión doctrinaria"]

--&gt; D["Importancia interpretativa"]

--&gt; E["No aparece expresamente en la LGS"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La <em>affectio societatis</em> sigue ocupando un lugar relevante en la doctrina societaria.</p>
<p>No obstante, después de la reforma introducida por la Ley 26.994, el centro del sistema se desplaza hacia el texto del artículo 1 de la LGS, la organización societaria y los deberes derivados de la buena fe y del interés social.</p>
</section>
<section id="el-acto-constitutivo-1" class="slide level1">
<h1>El acto constitutivo</h1>
<h2 id="contenido-del-instrumento">Contenido del instrumento</h2>
<h3 id="artículo-11-lgs">Artículo 11 LGS</h3>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Art. 11))
    Identificación de socios
    Denominación
    Domicilio
    Objeto
    Capital
    Organización
    Administración
    Fiscalización
    Utilidades
    Disolución
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Una vez analizados los elementos generales y específicos del contrato de sociedad, corresponde estudiar <strong>cómo deben exteriorizarse</strong>.</p>
<p>El artículo 11 de la LGS establece el <strong>contenido mínimo</strong> que debe reunir el instrumento constitutivo.</p>
<p>No se trata de un modelo de contrato.</p>
<p>Es un conjunto de requisitos cuya omisión puede impedir la inscripción registral.</p>
</section>
<section id="artículo-11-lgs-1" class="slide level1">
<h1>Artículo 11 LGS</h1>
<h2 id="qué-finalidad-cumple">¿Qué finalidad cumple?</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Acto constitutivo"]

--&gt; B["Instrumento"]

--&gt; C["Control registral"]

--&gt; D["Publicidad"]

--&gt; E["Seguridad jurídica"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El artículo 11 persigue múltiples objetivos:</p>
<ul>
<li>individualizar a la sociedad;</li>
<li>proteger a los socios;</li>
<li>brindar información a terceros;</li>
<li>facilitar el control de legalidad del Registro Público.</li>
</ul>
</section>
<section id="estructura-del-artículo-11" class="slide level1 scrollable">
<h1>Estructura del artículo 11</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Art. 11"]

A --&gt; B["Quiénes constituyen"]

A --&gt; C["Qué sociedad constituyen"]

A --&gt; D["Cómo funcionará"]

A --&gt; E["Cómo finalizará"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Los distintos incisos pueden agruparse en cuatro grandes categorías:</p>
<ol type="1">
<li>Identificación de los constituyentes.</li>
<li>Individualización de la sociedad.</li>
<li>Organización y funcionamiento.</li>
<li>Disolución y liquidación.</li>
</ol>
</section>
<section id="inciso-1" class="slide level1">
<h1>Inciso 1°</h1>
<h2 id="identificación-de-los-socios">Identificación de los socios</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Inc.1))
    Nombre
    Edad
    Estado civil
    Nacionalidad
    Profesión
    Domicilio
    DNI
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El instrumento debe individualizar adecuadamente a los constituyentes.</p>
<p>La finalidad es eliminar toda incertidumbre acerca de quiénes asumen la calidad de socios.</p>
<p>Cuando el socio sea una persona jurídica deberán consignarse los datos correspondientes a su identificación.</p>
</section>
<section id="inciso-2" class="slide level1">
<h1>Inciso 2°</h1>
<h2 id="denominación-y-domicilio">Denominación y domicilio</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Sociedad"]

--&gt; B["Denominación"]

--&gt; C["Domicilio"]

--&gt; D["Sede social"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La denominación permite individualizar a la sociedad frente a terceros.</p>
<p>El domicilio determina el Registro Público competente, la competencia judicial y el régimen legal aplicable a numerosos actos societarios.</p>
<p>Debe distinguirse entre:</p>
<ul>
<li>domicilio social;</li>
<li>sede social.</li>
</ul>
</section>
<section id="inciso-3" class="slide level1">
<h1>Inciso 3°</h1>
<h2 id="objeto-social-1">Objeto social</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Objeto))
    Preciso
    Determinado
    Lícito
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El objeto constituye uno de los aspectos más controlados por la autoridad registral.</p>
<p>Debe describir con precisión la actividad que desarrollará la sociedad.</p>
<p>Las cláusulas excesivamente amplias suelen ser observadas por el Registro Público.</p>
<p>Vítolo dedica especial atención al objeto por su importancia para el control de legalidad y la actuación de los administradores. :contentReference<span data-index="0">oaicite:0</span></p>
</section>
<section id="incisos-4-y-5" class="slide level1">
<h1>Incisos 4° y 5°</h1>
<h2 id="capital-y-aportes">Capital y aportes</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Capital social"]

--&gt; B["Aportes"]

--&gt; C["Integración"]

--&gt; D["Participaciones"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El instrumento debe indicar:</p>
<ul>
<li>el capital social;</li>
<li>los aportes comprometidos;</li>
<li>la forma de integración;</li>
<li>la participación correspondiente a cada socio.</li>
</ul>
<p>Estos datos permiten conocer la estructura patrimonial inicial de la sociedad.</p>
</section>
<section id="incisos-6-a-9" class="slide level1">
<h1>Incisos 6° a 9°</h1>
<h2 id="organización-de-la-sociedad">Organización de la sociedad</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Organización))
    Administración
    Representación
    Fiscalización
    Reuniones
    Mayorías
    Ejercicio social
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Estos incisos regulan el funcionamiento interno de la sociedad.</p>
<p>Determinan:</p>
<ul>
<li>quién administra;</li>
<li>quién representa;</li>
<li>cómo se adoptan las decisiones;</li>
<li>cómo se controla la gestión;</li>
<li>cuándo se confeccionan los estados contables.</li>
</ul>
<p>Constituyen el verdadero “estatuto de funcionamiento” de la sociedad.</p>
</section>
<section id="incisos-finales" class="slide level1">
<h1>Incisos finales</h1>
<h2 id="utilidades-disolución-y-liquidación">Utilidades, disolución y liquidación</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Resultados"]

--&gt; B["Distribución"]

B --&gt; C["Disolución"]

C --&gt; D["Liquidación"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El instrumento debe prever:</p>
<ul>
<li>la forma de distribuir utilidades;</li>
<li>el tratamiento de las pérdidas;</li>
<li>las reglas para la disolución;</li>
<li>el procedimiento de liquidación.</li>
</ul>
<p>La ley procura evitar vacíos normativos que puedan generar conflictos futuros.</p>
</section>
<section id="vítolo-y-nissen-1" class="slide level1">
<h1>Vítolo y Nissen</h1>
<p><strong>Vítolo</strong> explica que el artículo 11 contiene el contenido mínimo obligatorio del instrumento constitutivo y constituye una guía para el control de legalidad efectuado por el Registro Público. :contentReference<span data-index="1">oaicite:1</span></p>
<p><strong>Nissen</strong> destaca que el artículo 11 no agota el contenido posible del contrato social, sino que establece las cláusulas indispensables para la válida constitución de la sociedad. Sobre esa base pueden incorporarse numerosas estipulaciones complementarias compatibles con la ley. :contentReference<span data-index="2">oaicite:2</span></p>
</section>
<section id="cláusulas-tipificantes-y-no-tipificantes" class="slide level1">
<h1>Cláusulas tipificantes y no tipificantes</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Cláusulas del contrato"]

A --&gt; B["Tipificantes"]

A --&gt; C["No tipificantes"]

B --&gt; D["Definen el tipo societario"]

C --&gt; E["Complementan el régimen legal"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>No todas las cláusulas cumplen la misma función.</p>
<p>Las <strong>cláusulas tipificantes</strong> son aquellas exigidas por la ley para configurar un determinado tipo societario.</p>
<p>Las <strong>cláusulas no tipificantes</strong> son pactos complementarios incorporados por la autonomía de la voluntad, siempre que no contradigan normas imperativas ni desnaturalicen el tipo elegido.</p>
<p>Este criterio será especialmente importante al estudiar la tipicidad societaria y las sociedades de la Sección IV.</p>
</section>
<section id="iter-societatis" class="slide level1">
<h1>Iter societatis</h1>
<h2 id="el-proceso-de-constitución-de-la-sociedad">El proceso de constitución de la sociedad</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Voluntad de los socios"]
--&gt; B["Acto constitutivo"]
--&gt; C["Sociedad en formación"]
--&gt; D["Inscripción registral"]
--&gt; E["Sociedad regularmente constituida"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La constitución de una sociedad no constituye un acto instantáneo.</p>
<p>Entre la celebración del contrato y la inscripción registral existe un período intermedio, conocido por la doctrina como <strong>iter societatis</strong> o <strong>período fundacional</strong>.</p>
<p>Durante esta etapa la sociedad ya existe como organización negocial, pero todavía no ha completado el procedimiento previsto por la ley para su regular constitución.</p>
</section>
<section id="el-período-fundacional" class="slide level1">
<h1>El período fundacional</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">timeline
    title Iter societatis

    Firma del contrato : Acto constitutivo
    Organización inicial : Sociedad en formación
    Presentación : Registro Público
    Inscripción : Sociedad regularmente constituida
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El período fundacional comprende todas las actuaciones necesarias para obtener la inscripción del contrato constitutivo.</p>
<p>En esta etapa suelen realizarse actos indispensables para poner en marcha la empresa, como la apertura de cuentas bancarias, la contratación de personal, la adquisición de bienes o la celebración de contratos preliminares.</p>
</section>
<section id="la-sociedad-en-formación" class="slide level1">
<h1>La sociedad en formación</h1>
<h2 id="arts.-183-y-184-lgs">Arts. 183 y 184 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Contrato firmado"]
--&gt; B["Sociedad en formación"]
--&gt; C["Inscripción"]
--&gt; D["Sociedad regularmente constituida"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La LGS regula expresamente la sociedad en formación para las sociedades anónimas.</p>
<p>Sin embargo, la doctrina utiliza esta expresión en un sentido más amplio para describir el período existente entre el otorgamiento del acto constitutivo y la inscripción registral.</p>
<p>Vítolo distingue claramente esta etapa del régimen de las sociedades de la Sección IV. :contentReference<span data-index="0">oaicite:0</span></p>
</section>
<section id="qué-ocurre-durante-este-período" class="slide level1">
<h1>¿Qué ocurre durante este período?</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Sociedad en formación))
    Organización inicial
    Actos preparatorios
    Contratos
    Aportes
    Trámite registral
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Durante el período fundacional los socios comienzan a ejecutar el proyecto empresario.</p>
<p>La necesidad de actuar antes de la inscripción explica por qué la ley regula la responsabilidad derivada de esos actos.</p>
</section>
<section id="responsabilidad" class="slide level1">
<h1>Responsabilidad</h1>
<h2 id="art.-183-lgs">Art. 183 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Actos celebrados durante la formación"]
--&gt; B["Responsabilidad de quienes los realizaron"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Como principio, quienes actúan en nombre de la sociedad antes de su inscripción responden por los actos celebrados.</p>
<p>La posterior inscripción podrá producir determinados efectos respecto de esos actos, conforme a las condiciones previstas por la ley.</p>
</section>
<section id="ratificación" class="slide level1">
<h1>Ratificación</h1>
<h2 id="art.-184-lgs">Art. 184 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Acto celebrado"]
--&gt; B["Inscripción"]
--&gt; C["Ratificación por la sociedad"]
--&gt; D["Asunción de efectos"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La ley contempla la posibilidad de que determinados actos celebrados durante el período fundacional sean asumidos por la sociedad una vez inscripta.</p>
<p>De este modo se procura compatibilizar las necesidades prácticas del tráfico comercial con la protección de terceros.</p>
</section>
<section id="vítolo-2" class="slide level1">
<h1>Vítolo</h1>
<p>Vítolo explica que el período fundacional constituye una etapa necesaria en la vida de toda sociedad y que los artículos 183 y 184 procuran resolver el problema de los actos celebrados antes de la inscripción definitiva. :contentReference<span data-index="1">oaicite:1</span></p>
<p>Destaca además que no debe confundirse la <strong>sociedad en formación</strong> con las <strong>sociedades comprendidas en la Sección IV</strong>, pues responden a supuestos jurídicos completamente diferentes. :contentReference<span data-index="2">oaicite:2</span></p>
</section>
<section id="nissen-2" class="slide level1">
<h1>Nissen</h1>
<p>Nissen señala que la sociedad en formación constituye una situación transitoria y normal dentro del proceso constitutivo.</p>
<p>Su finalidad consiste en permitir el desarrollo de los actos indispensables para la puesta en marcha de la empresa mientras se completa el trámite registral. :contentReference<span data-index="3">oaicite:3</span></p>
</section>
<section id="síntesis-1" class="slide level1">
<h1>Síntesis</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Acto constitutivo"]
--&gt; B["Período fundacional"]
--&gt; C["Sociedad en formación"]
--&gt; D["Inscripción"]
--&gt; E["Sociedad regularmente constituida"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El <strong>iter societatis</strong> constituye el puente entre el contrato y la personalidad jurídica plenamente oponible.</p>
<p>Comprender esta etapa resulta indispensable para distinguir entre:</p>
<ul>
<li>sociedad en formación;</li>
<li>sociedad regularmente constituida;</li>
<li>sociedades de la Sección IV.</li>
</ul>
</section>
<section id="inscripción-en-el-registro-público" class="slide level1">
<h1>Inscripción en el Registro Público</h1>
<h2 id="arts.-5-a-10-lgs">Arts. 5 a 10 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Acto constitutivo"]

--&gt; B["Presentación"]

--&gt; C["Control de legalidad"]

--&gt; D["Inscripción"]

--&gt; E["Publicidad"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La inscripción en el Registro Público constituye la última etapa del proceso constitutivo.</p>
<p>Los artículos 5 a 10 de la LGS regulan:</p>
<ul>
<li>el lugar de inscripción;</li>
<li>los plazos;</li>
<li>el control registral;</li>
<li>los efectos de la inscripción;</li>
<li>la publicidad del acto constitutivo.</li>
</ul>
</section>
<section id="dónde-se-inscribe" class="slide level1">
<h1>¿Dónde se inscribe?</h1>
<h2 id="artículo-5-lgs">Artículo 5 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Contrato constitutivo"]

--&gt; B["Registro Público"]

B --&gt; C["Domicilio social"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La inscripción debe solicitarse en el Registro Público correspondiente al domicilio social.</p>
<p>La competencia registral depende del domicilio fijado en el contrato constitutivo.</p>
<p>En la Ciudad Autónoma de Buenos Aires, estas funciones son ejercidas por la <strong>Inspección General de Justicia (IGJ)</strong>.</p>
</section>
<section id="cuándo-debe-solicitarse" class="slide level1">
<h1>¿Cuándo debe solicitarse?</h1>
<h2 id="artículo-6-lgs">Artículo 6 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">timeline
    title Artículo 6 LGS

    Firma del contrato : Día 0
    Presentación : Dentro de los 20 días
    Trámite registral : Hasta obtener la inscripción
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La solicitud de inscripción debe presentarse dentro de los <strong>veinte (20) días</strong> desde el otorgamiento del acto constitutivo.</p>
<p>Si la presentación es tempestiva, la inscripción produce efectos desde la fecha del acto constitutivo.</p>
</section>
<section id="qué-ocurre-si-la-presentación-es-tardía" class="slide level1">
<h1>¿Qué ocurre si la presentación es tardía?</h1>
<h2 id="artículo-6-lgs-1">Artículo 6 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Presentación fuera de término"]

--&gt; B["La inscripción sigue siendo posible"]

--&gt; C["Debe cumplirse el régimen del art. 6"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La reforma introducida por la Ley 26.994 eliminó el régimen excesivamente rígido existente con anterioridad.</p>
<p>La presentación tardía ya no impide necesariamente la inscripción, aunque puede producir consecuencias jurídicas específicas.</p>
<p>Vítolo analiza detalladamente esta modificación y destaca el criterio más flexible adoptado por la reforma. :contentReference<span data-index="0">oaicite:0</span></p>
</section>
<section id="el-control-registral" class="slide level1">
<h1>El control registral</h1>
<h2 id="artículo-6-lgs-2">Artículo 6 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Control))
    Legalidad
    Tipicidad
    Objeto
    Capital
    Cláusulas obligatorias
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El Registro Público no realiza un control de oportunidad o conveniencia.</p>
<p>Su función consiste en verificar la legalidad del acto constitutivo.</p>
<p>Por ello controla, entre otras cuestiones:</p>
<ul>
<li>el cumplimiento de la ley;</li>
<li>la adecuación al tipo elegido;</li>
<li>la presencia de las cláusulas exigidas por el artículo 11.</li>
</ul>
</section>
<section id="facultades-de-la-autoridad-registral" class="slide level1">
<h1>Facultades de la autoridad registral</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Registro Público"]

--&gt; B["Observa"]

--&gt; C["Requiere subsanaciones"]

--&gt; D["Inscribe"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Si el contrato presenta defectos subsanables, la autoridad registral puede formular observaciones y requerir su corrección antes de disponer la inscripción.</p>
<p>Este control preventivo procura evitar el ingreso al tráfico jurídico de sociedades constituidas en violación de la ley.</p>
</section>
<section id="publicidad" class="slide level1">
<h1>Publicidad</h1>
<h2 id="artículos-5-y-10-lgs">Artículos 5 y 10 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Inscripción"]

--&gt; B["Publicidad"]

--&gt; C["Conocimiento por terceros"]

--&gt; D["Seguridad jurídica"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La inscripción cumple una función de publicidad.</p>
<p>Permite que terceros conozcan la existencia de la sociedad, sus datos esenciales y las reglas básicas de su organización.</p>
<p>La publicidad registral constituye uno de los fundamentos de la oponibilidad del contrato social.</p>
</section>
<section id="modificaciones-posteriores" class="slide level1">
<h1>Modificaciones posteriores</h1>
<h2 id="artículo-12-lgs">Artículo 12 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Modificación del contrato"]

--&gt; B["Inscripción"]

--&gt; C["Publicidad"]

--&gt; D["Oponibilidad"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Las modificaciones del contrato social también deben inscribirse.</p>
<p>Mientras no sean registradas, su oponibilidad frente a terceros puede verse afectada.</p>
<p>La inscripción no constituye un requisito exclusivo del acto constitutivo, sino también de las principales modificaciones estatutarias.</p>
</section>
<section id="vítolo-y-nissen-2" class="slide level1">
<h1>Vítolo y Nissen</h1>
<p><strong>Vítolo</strong> explica que el Registro Público ejerce un verdadero control de legalidad y analiza especialmente el nuevo régimen del artículo 6 luego de la reforma de la Ley 26.994, particularmente en materia de presentación tardía. :contentReference<span data-index="1">oaicite:1</span></p>
<p><strong>Nissen</strong> destaca la importancia del control registral como mecanismo preventivo destinado a preservar la legalidad societaria y proteger a terceros mediante la publicidad de los actos inscriptos. :contentReference<span data-index="2">oaicite:2</span></p>
</section>
<section id="transición-1" class="slide level1">
<h1>Transición</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Contrato"]

--&gt; B["Inscripción"]

--&gt; C["Sociedad regularmente constituida"]

A --&gt; D["Sin inscripción"]

--&gt; E["Sección IV LGS"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La inscripción permite alcanzar el régimen ordinario de las sociedades regularmente constituidas.</p>
<p>La falta de inscripción, en cambio, conduce al régimen especial previsto por los <strong>artículos 21 a 26 de la Ley General de Sociedades</strong>, que estudiaremos a continuación.</p>
</section>
<section id="las-sociedades-de-la-sección-iv" class="slide level1">
<h1>Las sociedades de la Sección IV</h1>
<h2 id="arts.-21-a-26-lgs">Arts. 21 a 26 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Ley 19.550"]

--&gt; B["Sociedades de hecho e irregulares"]

--&gt; C["Ley 26.994"]

--&gt; D["Sociedades de la Sección IV"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La Ley 26.994 modificó profundamente el régimen de las sociedades no regularmente constituidas.</p>
<p>Desaparecieron las categorías de <strong>sociedad de hecho</strong> y <strong>sociedad irregular</strong>, reemplazadas por un régimen único contenido en los artículos 21 a 26 de la LGS.</p>
<p>La finalidad de la reforma fue abandonar un sistema predominantemente sancionatorio para adoptar un régimen más flexible, privilegiando la conservación de la empresa y la protección del tráfico jurídico. :contentReference<span data-index="0">oaicite:0</span> :contentReference<span data-index="1">oaicite:1</span></p>
</section>
<section id="qué-sociedades-comprende" class="slide level1">
<h1>¿Qué sociedades comprende?</h1>
<h2 id="artículo-21-lgs">Artículo 21 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Sección IV))
    Sin inscripción
    Con defectos de forma
    Con omisiones
    Atípicas
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El artículo 21 comprende un conjunto heterogéneo de supuestos.</p>
<p>No se trata únicamente de sociedades no inscriptas.</p>
<p>También quedan alcanzadas aquellas que presentan defectos constitutivos o cuya instrumentación no satisface las exigencias legales.</p>
<p>La Sección IV constituye un régimen residual destinado a evitar la nulidad automática de organizaciones empresarias que funcionan en la realidad económica.</p>
</section>
<section id="antes-y-después-de-la-reforma" class="slide level1">
<h1>Antes y después de la reforma</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Antes de 2015"]

--&gt; B["Sociedad irregular"]

A --&gt; C["Sociedad de hecho"]

D["Desde 2015"]

--&gt; E["Sección IV"]

E --&gt; F["Régimen unificado"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Uno de los principales objetivos de la reforma fue eliminar categorías cuya diferenciación práctica generaba importantes dificultades interpretativas.</p>
<p>En su reemplazo se estableció un régimen único, aplicable a todas las sociedades comprendidas en el artículo 21.</p>
</section>
<section id="fundamento-de-la-reforma" class="slide level1">
<h1>Fundamento de la reforma</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Ley 26.994))
    Conservación de la empresa
    Seguridad del tráfico
    Flexibilización
    Protección de terceros
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La reforma parte de una idea central.</p>
<p>La ausencia de inscripción no debe conducir automáticamente a la desaparición del fenómeno societario.</p>
<p>Cuando existe una organización económica que actúa en el tráfico jurídico, el derecho debe brindar respuestas adecuadas para proteger tanto a los socios como a los terceros.</p>
<p>Vítolo destaca que la reforma abandona la lógica sancionatoria que caracterizaba al régimen anterior. :contentReference<span data-index="2">oaicite:2</span></p>
</section>
<section id="la-posición-de-nissen-1" class="slide level1">
<h1>La posición de Nissen</h1>
<p>Nissen reconoce que la reforma implicó un cambio profundo respecto del sistema originario de la Ley 19.550.</p>
<p>No obstante, advierte que la amplitud del nuevo régimen puede generar incertidumbre y plantea diversos interrogantes interpretativos respecto de su alcance y de la protección de terceros. :contentReference<span data-index="3">oaicite:3</span></p>
</section>
<section id="primera-consecuencia" class="slide level1">
<h1>Primera consecuencia</h1>
<h2 id="la-sociedad-existe">La sociedad existe</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Contrato"]

--&gt; B["No inscripción"]

--&gt; C["Sección IV"]

--&gt; D["La organización subsiste"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La falta de inscripción ya no implica desconocer la existencia de la organización.</p>
<p>La sociedad continúa siendo relevante para el derecho.</p>
<p>Lo que cambia es el régimen jurídico aplicable.</p>
</section>
<section id="método-de-estudio" class="slide level1">
<h1>Método de estudio</h1>
<p>En los próximos artículos analizaremos:</p>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Art. 21"]

--&gt; B["Representación"]

--&gt; C["Responsabilidad"]

--&gt; D["Bienes registrables"]

--&gt; E["Subsanación"]

--&gt; F["Disolución"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Cada uno de estos aspectos fue profundamente modificado por la Ley 26.994.</p>
</section>
<section id="idea-central" class="slide level1">
<h1>Idea central</h1>
<p>La Sección IV ya no constituye un régimen de “sociedades defectuosas”.</p>
<p>Constituye un <strong>régimen especial</strong> para organizaciones que existen y actúan en el tráfico jurídico, pero que no reúnen los requisitos necesarios para quedar sometidas al régimen ordinario de las sociedades regularmente constituidas.</p>
</section>
<section id="artículo-22-lgs" class="slide level1">
<h1>Artículo 22 LGS</h1>
<h2 id="la-subsanación">La subsanación</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Sociedad Sección IV"]

--&gt; B["Defecto constitutivo"]

--&gt; C["Subsanación"]

--&gt; D["Sociedad regularmente constituida"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Una de las principales innovaciones de la Ley 26.994 fue incorporar expresamente la posibilidad de <strong>subsanar</strong> los defectos que colocan a la sociedad dentro del régimen de la Sección IV.</p>
<p>El nuevo sistema procura conservar la empresa y facilitar su adecuación al régimen general, abandonando el criterio predominantemente sancionatorio del régimen anterior.</p>
<p>Vítolo considera que esta posibilidad constituye una de las modificaciones más importantes introducidas por la reforma. :contentReference<span data-index="0">oaicite:0</span></p>
</section>
<section id="qué-significa-subsanar" class="slide level1">
<h1>¿Qué significa subsanar?</h1>
<h2 id="artículo-22-lgs-1">Artículo 22 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Subsanación))
    Corregir defectos
    Completar requisitos
    Obtener inscripción
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Subsanar significa remover la causa que impide la regular constitución de la sociedad.</p>
<p>La finalidad no es crear una nueva sociedad, sino permitir que la organización existente acceda al régimen ordinario previsto por la Ley General de Sociedades.</p>
</section>
<section id="qué-puede-subsanarse" class="slide level1">
<h1>¿Qué puede subsanarse?</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Defectos"]

A --&gt; B["Falta de inscripción"]

A --&gt; C["Defectos instrumentales"]

A --&gt; D["Omisiones subsanables"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La subsanación comprende los supuestos previstos en la Sección IV siempre que el defecto sea susceptible de corrección.</p>
<p>No todo vicio admite subsanación.</p>
<p>Cuando existe un obstáculo insalvable, la sociedad continuará sometida al régimen especial.</p>
</section>
<section id="artículo-23-lgs" class="slide level1">
<h1>Artículo 23 LGS</h1>
<h2 id="representación">Representación</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Sociedad Sección IV"]

--&gt; B["Representación"]

--&gt; C["Actos frente a terceros"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El artículo 23 regula la representación de estas sociedades.</p>
<p>La reforma abandona el criterio rígido del régimen anterior y procura brindar mayor seguridad al tráfico jurídico.</p>
<p>La actuación del representante se analiza atendiendo tanto a la protección de terceros como a la realidad del funcionamiento societario.</p>
</section>
<section id="bienes-registrables" class="slide level1">
<h1>Bienes registrables</h1>
<h2 id="artículo-23-lgs-1">Artículo 23 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Sociedad Sección IV"]

--&gt; B["Adquisición de bienes registrables"]

--&gt; C["Inscripción a nombre de la sociedad"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Una de las novedades más relevantes consiste en admitir que estas sociedades puedan adquirir bienes registrables.</p>
<p>Antes de la reforma, esta cuestión originaba importantes dificultades prácticas.</p>
<p>La nueva regulación facilita el desenvolvimiento normal de la empresa y protege la seguridad del tráfico.</p>
<p>Vítolo destaca este cambio como una de las innovaciones más trascendentes del nuevo régimen. :contentReference<span data-index="1">oaicite:1</span></p>
</section>
<section id="prueba-de-la-sociedad" class="slide level1">
<h1>Prueba de la sociedad</h1>
<h2 id="artículo-23-lgs-2">Artículo 23 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Prueba))
    Instrumento
    Actuación
    Terceros
    Medios generales
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La existencia de la sociedad y sus cláusulas pueden acreditarse por los medios admitidos por el ordenamiento.</p>
<p>La reforma flexibiliza sensiblemente el sistema probatorio, privilegiando la realidad económica sobre el excesivo formalismo.</p>
</section>
<section id="artículo-24-lgs" class="slide level1">
<h1>Artículo 24 LGS</h1>
<h2 id="responsabilidad-de-los-socios">Responsabilidad de los socios</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Obligaciones sociales"]

--&gt; B["Sociedad"]

--&gt; C["Socios"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El régimen de responsabilidad constituye uno de los aspectos más importantes de la Sección IV.</p>
<p>La Ley 26.994 abandonó el sistema uniforme de responsabilidad solidaria e ilimitada que caracterizaba a las antiguas sociedades de hecho e irregulares.</p>
<p>El nuevo régimen debe analizarse a partir del texto del artículo 24 y de las cláusulas pactadas por los socios.</p>
<p>Vítolo y Nissen dedican un extenso desarrollo a esta modificación por las importantes consecuencias prácticas que genera. :contentReference<span data-index="2">oaicite:2</span> :contentReference<span data-index="3">oaicite:3</span></p>
</section>
<section id="artículo-25-lgs" class="slide level1">
<h1>Artículo 25 LGS</h1>
<h2 id="disolución">Disolución</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Sociedad Sección IV"]

--&gt; B["Causal legal"]

--&gt; C["Disolución"]

--&gt; D["Liquidación"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La disolución también fue reformulada.</p>
<p>La finalidad del nuevo sistema consiste en evitar soluciones automáticas incompatibles con la continuidad de empresas económicamente viables.</p>
<p>La conservación de la organización aparece nuevamente como uno de los principios inspiradores de la reforma.</p>
</section>
<section id="artículo-26-lgs" class="slide level1">
<h1>Artículo 26 LGS</h1>
<h2 id="acreedores-particulares">Acreedores particulares</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Acreedor particular"]

--&gt; B["Derechos del socio"]

--&gt; C["Participación social"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El artículo 26 regula las relaciones entre los acreedores particulares de los socios y la sociedad.</p>
<p>La norma procura compatibilizar:</p>
<ul>
<li>la protección del crédito individual;</li>
<li>la continuidad de la empresa;</li>
<li>la estabilidad de la organización societaria.</li>
</ul>
</section>
<section id="balance-de-la-reforma" class="slide level1">
<h1>Balance de la reforma</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Sección IV))
    Subsanación
    Representación
    Bienes registrables
    Responsabilidad
    Disolución
    Protección de terceros
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La Ley 26.994 sustituyó un régimen construido sobre la irregularidad por otro orientado a la <strong>conservación de la empresa</strong>, la <strong>protección del tráfico jurídico</strong> y la <strong>regularización de las organizaciones existentes</strong>.</p>
<p>Vítolo considera que el nuevo régimen abandona definitivamente la lógica sancionatoria que inspiraba el sistema anterior, mientras que Nissen advierte que varias de las soluciones incorporadas plantean importantes desafíos interpretativos. :contentReference<span data-index="4">oaicite:4</span> :contentReference<span data-index="5">oaicite:5</span></p>
</section>
<section id="cláusulas-del-acto-constitutivo" class="slide level1">
<h1>Cláusulas del acto constitutivo</h1>
<h2 id="cláusulas-tipificantes-y-no-tipificantes-1">Cláusulas tipificantes y no tipificantes</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Contrato social"]

--&gt; B["Cláusulas tipificantes"]

A --&gt; C["Cláusulas no tipificantes"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El contenido del contrato social no se agota en las cláusulas exigidas por el artículo 11 de la Ley General de Sociedades.</p>
<p>Los socios pueden incorporar otras estipulaciones en ejercicio de la autonomía de la voluntad, siempre que respeten las normas imperativas y no desnaturalicen el tipo social elegido.</p>
<p>Esta distinción permite diferenciar entre <strong>cláusulas tipificantes</strong> y <strong>cláusulas no tipificantes</strong>. :contentReference<span data-index="0">oaicite:0</span></p>
</section>
<section id="cláusulas-tipificantes" class="slide level1">
<h1>Cláusulas tipificantes</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((Tipificantes))
    Definen el tipo
    Son esenciales
    Surgen de la ley
    No pueden omitirse
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Las cláusulas tipificantes son aquellas indispensables para que la sociedad pueda ser encuadrada dentro de uno de los tipos previstos por la Ley General de Sociedades.</p>
<p>No dependen de la voluntad de los socios.</p>
<p>Su contenido viene impuesto por la ley y constituye uno de los aspectos sometidos al control de legalidad del Registro Público.</p>
</section>
<section id="función-de-las-cláusulas-tipificantes" class="slide level1">
<h1>Función de las cláusulas tipificantes</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Cláusulas tipificantes"]

--&gt; B["Determinan el tipo social"]

--&gt; C["Régimen jurídico aplicable"]

--&gt; D["Protección de terceros"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Las cláusulas tipificantes cumplen una doble función:</p>
<ul>
<li>permiten identificar el tipo societario elegido;</li>
<li>determinan el régimen legal que gobernará la sociedad durante toda su existencia.</li>
</ul>
<p>Por ello, su omisión o contradicción puede impedir la inscripción o provocar el ingreso al régimen de la Sección IV.</p>
</section>
<section id="cláusulas-no-tipificantes" class="slide level1">
<h1>Cláusulas no tipificantes</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">mindmap
  root((No tipificantes))
    Organización interna
    Derechos especiales
    Restricciones
    Mecanismos de solución de conflictos
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Las cláusulas no tipificantes son aquellas incorporadas por decisión de los socios para adaptar el funcionamiento de la sociedad a sus necesidades particulares.</p>
<p>No resultan exigidas por la ley.</p>
<p>Su validez depende de que sean compatibles con el régimen imperativo de la LGS y con el tipo societario adoptado.</p>
</section>
<section id="autonomía-de-la-voluntad" class="slide level1">
<h1>Autonomía de la voluntad</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Autonomía privada"]

--&gt; B["Cláusulas no tipificantes"]

B --&gt; C["Límite"]

C --&gt; D["Normas imperativas"]

C --&gt; E["Tipo societario"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>El contrato social constituye una expresión de la autonomía privada.</p>
<p>Sin embargo, esa autonomía no es absoluta.</p>
<p>Los socios no pueden incorporar estipulaciones incompatibles con normas imperativas ni alterar los elementos esenciales del tipo elegido.</p>
</section>
<section id="el-control-registral-1" class="slide level1">
<h1>El control registral</h1>
<h2 id="arts.-6-y-11-lgs">Arts. 6 y 11 LGS</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR

A["Contrato"]

--&gt; B["Registro Público"]

--&gt; C["Control de legalidad"]

--&gt; D["Inscripción"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Al ejercer el control de legalidad, el Registro Público verifica tanto la presencia de las cláusulas obligatorias como la compatibilidad de las cláusulas incorporadas por los socios con el ordenamiento jurídico.</p>
<p>Las observaciones registrales suelen recaer sobre cláusulas que alteran el régimen legal del tipo societario o contradicen normas imperativas.</p>
</section>
<section id="vítolo-3" class="slide level1">
<h1>Vítolo</h1>
<p>Vítolo explica que el contrato social puede contener numerosas estipulaciones complementarias, pero destaca que la autonomía contractual encuentra su límite en las normas imperativas de la Ley General de Sociedades y en la preservación de la tipicidad societaria. :contentReference<span data-index="1">oaicite:1</span></p>
</section>
<section id="nissen-3" class="slide level1">
<h1>Nissen</h1>
<p>Nissen sostiene que las cláusulas incorporadas por los socios sólo son admisibles cuando no modifican la estructura esencial del tipo societario ni afectan derechos cuya tutela responde a razones de orden público. :contentReference<span data-index="2">oaicite:2</span></p>
</section>
<section id="síntesis-2" class="slide level1">
<h1>Síntesis</h1>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

A["Contrato social"]

A --&gt; B["Cláusulas exigidas por la ley"]

A --&gt; C["Cláusulas incorporadas por los socios"]

B --&gt; D["Tipificantes"]

C --&gt; E["No tipificantes"]

E --&gt; F["Válidas si respetan la LGS"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>La distinción entre cláusulas tipificantes y no tipificantes constituye una manifestación del equilibrio existente en el derecho societario entre dos principios:</p>
<ul>
<li>la <strong>tipicidad</strong>, que garantiza la seguridad jurídica y la protección de terceros;</li>
<li>la <strong>autonomía de la voluntad</strong>, que permite adaptar el contrato social a las necesidades de los socios dentro de los límites fijados por la ley.</li>
</ul>
</section>
<section class="slide level1">



</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 4.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiado");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiado");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>